export {
  ROX_VISIBLE_TERMS,
  COMPATIBILITY_RUNTIME_TERMS,
  TERMINOLOGY_KEY_ALLOWLIST,
  isAllowlistedLocaleKey,
  isCompatibilityRuntimeTerm,
  localeValueViolations,
  type RoxVisibleTerm,
  type CompatibilityRuntimeTerm,
  type CompatibilityContextKind,
  type TerminologyAllowlistEntry,
} from './terms.ts'

export {
  DEFAULT_AGENT_SERIAL,
  generateDefaultAgentIdentity,
  resolveAgentIdentity,
  persistAgentIdentity,
  formatAgentIdentityForPrompt,
  formatSessionAgentLabel,
  gitCoAuthorTrailer,
  type AgentIdentity,
  type AgentIdentitySource,
  type AgentIdentityRecord,
} from './agent-identity.ts'

export {
  ROX_ALIAS_REMOVAL_DEADLINE,
  ROX_BRAND_MIGRATION_VERSION,
  ROX_BRO_ORIGIN,
  ROX_BUNDLE_ID,
  ROX_CONFIG_DIR_ENV,
  ROX_CONFIG_DIR_NAME,
  ROX_DEEPLINK_SCHEME,
  ROX_LEGACY_ALIASES,
  ROX_LEGACY_BUNDLE_ID,
  ROX_LEGACY_CONFIG_DIR_ENV,
  ROX_LEGACY_CONFIG_DIR_NAME,
  ROX_LEGACY_DEEPLINK_SCHEME,
  ROX_LEGACY_UPDATE_CHANNEL,
  ROX_MIGRATION_MANIFEST,
  ROX_PRODUCT_NAME,
  ROX_PUBLIC_ORIGIN,
  ROX_TYPOGRAPHY,
  ROX_UPDATE_CHANNEL,
  isRoxDeeplinkProtocol,
  isRoxDeeplinkUrl,
  type RoxMigrationManifest,
} from './manifest.ts'

export {
  ROX_MIGRATION_STAMP_NAME,
  defaultBrandMigrationPaths,
  exportBrandConfig,
  readMigrationStamp,
  rollbackBrandConfigMigration,
  runBrandConfigMigration,
  stampPath,
  uninstallBrandConfig,
  type BrandMigrationOutcome,
  type BrandMigrationResult,
  type BrandMigrationStamp,
} from './config-migration.ts'
export { UI_BRAND_MANIFEST, UI_BRAND_ALLOWLIST } from './ui-brand.ts'

// W1-13 (#1510): visible Rox home migration (MIG-13, `~/.rox` → `~/rox`).
export {
  ROX_HIDDEN_HOME_LINK_NAME,
  ROX_HOME_MIGRATION_DIR_NAME,
  ROX_HOME_MIGRATION_MANIFEST_NAME,
  ROX_VISIBLE_HOME_DIR_NAME,
  ROX_WORKBENCH_FLAGS_FILE_NAME,
  ROX_STORAGE_VISIBLE_ROOT_FLAG_ID,
  VISIBLE_HOME_USABLE_OUTCOMES,
  ROX_DESKTOP_APP_LOCK_NAME,
  ROX_HOME_MARKER_NAMES,
  ROX_MERGE_INCOMPLETE_MARKER_NAME,
  buildVisibleHomeManifest,
  defaultVisibleHomePaths,
  desktopAppRuntimeLockPath,
  desktopAppRuntimeLockPaths,
  ROX_MIGRATION_LOCK_FILE_NAME,
  ROX_STORAGE_MIGRATION_STATE_FILE_NAME,
  clearStorageMigrationState,
  readStorageMigrationState,
  recordStorageMigrationOutcome,
  storageMigrationStateFilePath,
  writeStorageMigrationState,
  type StorageMigrationState,
  type StorageMigrationStateKind,
  type LockOwnershipOptions,
  type RuntimeLockLocationOptions,
  holdDesktopAppLock,
  isForeignVisibleHome,
  isLockFileLive,
  mergeIncompleteMarkerPath,
  readMergeIncompleteMarker,
  resolveVisibleHomeWithoutMigration,
  symlinkTargetMatches,
  migrateHiddenRoxHome,
  parseMigrationLockContent,
  readPersistedVisibleRootFlag,
  revertVisibleRoxHome,
  roxHomeHasUserData,
  summarizeVisibleHomeManifest,
  visibleHomeManifestsEqual,
  visibleRootEnvOverride,
  visibleRootFlagFilePath,
  writePersistedVisibleRootFlag,
  type MergeIncompleteMarker,
  type MigrateHiddenRoxHomeOptions,
  type VisibleHomeManifestEntry,
  type VisibleHomeMigrationResult,
  type VisibleHomeOutcome,
  type VisibleHomePaths,
} from './config-migration.ts'
