import { mock } from 'bun:test';
import {mkdtempSync,mkdirSync,rmSync,writeFileSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
const root='/Users/t/.codex/worktrees/pocket-id-sso/rox-release-20261003';const temp=mkdtempSync(join(tmpdir(),'pocket-callback-review-'));
try{const ts=join(temp,'tsconfig.json');writeFileSync(ts,JSON.stringify({compilerOptions:{baseUrl:root,paths:{'@rox/shared/*':[join(root,'packages/shared/src/*')],'@rox/core/*':[join(root,'packages/core/src/*')]}}}));
const child=Bun.spawn([process.execPath,'--tsconfig-override',ts,'-e',`
const {mock}=await import('bun:test');const {mkdirSync}=await import('node:fs');const {join}=await import('node:path');
const workspace=join(process.env.ROX_CONFIG_DIR,'workspace');mkdirSync(workspace);
const {saveConfig}=await import('./packages/shared/src/config/storage.ts');saveConfig({workspaces:[{id:'ws',name:'Fixture',rootPath:workspace,createdAt:1}],activeWorkspaceId:'ws',activeSessionId:null});
const {createPocketFixture,pocketSnapshot}=await import('./packages/shared/src/auth/__tests__/pocket-test-fixture.ts');const {setRoxAccountAuthority}=await import('./packages/shared/src/auth/rox-account-authority.ts');
const f=createPocketFixture();setRoxAccountAuthority(f.authority);const caller={issuer:'fixture',subject:'a'};await f.store.write(caller,{accountId:'account-a',authGeneration:'generation-a',accessToken:'account-a',refreshToken:'synthetic-refresh',expiresAt:Date.now()+900000});const ca=await f.authority.capture(caller);
const real=await import('@rox/shared/agent/backend');let core,sink;const fake={postInit:async()=>({authInjected:true}),getSummarizeCallback:()=>undefined,setPermissionMode(){},setBackgroundEventSink(fn){sink=fn},destroy(){}};
const connection={slug:'fixture',name:'Fixture',providerType:'omp',authType:'none',defaultModel:'rox/standard'};
mock.module('@rox/shared/agent/backend',()=>({...real,resolveOmpSessionContext:()=>({connection,resolvedModel:'rox/standard',provider:'omp',capabilities:{needsHttpPoolServer:false}}),createOmpSessionBackendFromResolvedContext:options=>{core=options.coreConfig;return fake}}));
const {SessionManager,createManagedSession,setSessionPlatform}=await import('./packages/server-core/src/sessions/SessionManager.ts');setSessionPlatform({appRootPath:workspace,resourcesPath:workspace,isPackaged:false,logger:{info(){},warn(){},error(){},debug(){}}});
const sm=new SessionManager();const ws={id:'ws',name:'Fixture',rootPath:workspace,createdAt:1};const managed=createManagedSession({id:'s1',name:'Original'},ws,{messagesLoaded:true});sm.sessions.set('s1',managed);sm.roxExecutions.set('s1',ca);await f.authority.bind('session:ws:s1',ca);sm.persistSession=()=>{};sm.flushSession=async()=>{};sm.sendEvent=()=>{};sm.tryRefreshAgentRuntime=async()=>{};let writes=0,sends=[];sm.processEvent=async()=>{writes++};sm.sendMessage=async(...args)=>{sends.push({id:args[0],account:args[8]?.roxExecutionContext?.cloudAccountId,generation:args[8]?.roxExecutionContext?.authGeneration})};let children=0;sm.createSession=async()=>{const id='child-'+(++children);const m=createManagedSession({id,name:id},ws,{messagesLoaded:true});sm.sessions.set(id,m);return m};
await sm.getOrCreateAgent(managed);const {getSessionScopedToolCallbacks}=await import('./packages/shared/src/agent/session-scoped-tool-callback-registry.ts');const registry=getSessionScopedToolCallbacks('s1');
core.onSdkSessionIdUpdate('sdk-a');sink({type:'complete'});await Bun.sleep(5);await fake.onSpawnSession({name:'Child',prompt:'fixture'});await registry.sendAgentMessageFn('target','fixture');
const positive={sdk:managed.sdkSessionId,writes,sends:[...sends]};
await f.authority.logout(caller);f.client.wait=async()=>({status:'approved',accessToken:'account-b',refreshToken:'fixture-b',tokenType:'Bearer',expiresIn:900,user:{id:'account-b',email:'same@example.test',name:'Cloud'}});f.setSnapshot(pocketSnapshot('account-b'));await f.authority.start(caller);await f.authority.state(caller);const cb=await f.authority.capture(caller);sm.roxExecutions.set('s1',cb);
core.onSdkSessionIdUpdate('late-sdk-a');sink({type:'complete'});await Bun.sleep(5);let spawnError,sendError;try{await fake.onSpawnSession({name:'Late',prompt:'fixture'})}catch(e){spawnError=e.message}try{await registry.sendAgentMessageFn('target','late')}catch(e){sendError=e.message}
const result={coreAccount:core.roxExecutionContext?.cloudAccountId,positive,late:{sdk:managed.sdkSessionId,writes,sends:sends.length,children,spawnError,sendError},newAccount:cb.cloudAccountId};managed.mcpPool?.destroy?.();console.log(JSON.stringify(result));
`],{cwd:root,env:{...process.env,NODE_ENV:'test',ROX_CONFIG_DIR:temp,CRAFT_CONFIG_DIR:temp},stdout:'pipe',stderr:'pipe'});const [exit,out,err]=await Promise.all([child.exited,new Response(child.stdout).text(),new Response(child.stderr).text()]);console.log(JSON.stringify({exit,stdout:out,stderr:err}));if(exit)process.exitCode=exit;
}finally{rmSync(temp,{recursive:true,force:true})}
