/**
 * RPC channel names — organized by domain namespace.
 * Wire-format strings (values) are the stable API contract.
 * Key paths are internal and may be reorganized freely.
 */
export const RPC_CHANNELS = {
  cloudRuns: {
    GET_CONFIG: 'cloudRuns:getConfig',
    SET_CONFIG: 'cloudRuns:setConfig',
    SUBMIT: 'cloudRuns:submit',
    RESUME: 'cloudRuns:resume',
    SESSION_TOPIC: 'cloudRuns:sessionTopic',
    LIST_SCHEDULES: 'cloudRuns:listSchedules',
    SAVE_SCHEDULE: 'cloudRuns:saveSchedule',
    DELETE_SCHEDULE: 'cloudRuns:deleteSchedule',
    READ_ARTIFACT: 'cloudRuns:readArtifact',
    GET_EVENTS: 'cloudRuns:getEvents',
    SHARE: 'cloudRuns:share',
    REVOKE_SHARE: 'cloudRuns:revokeShare',
    LIST: 'cloudRuns:list',
    GET_STATUS: 'cloudRuns:getStatus',
    CANCEL: 'cloudRuns:cancel',
    LIST_ARTIFACTS: 'cloudRuns:listArtifacts',
    IMPORT: 'cloudRuns:import',
    AGGREGATE: 'cloudRuns:aggregate',
  },
  remote: {
    TEST_CONNECTION: 'remote:testConnection',
  },
  server: {
    GET_WORKSPACES: 'server:getWorkspaces',
    CREATE_WORKSPACE: 'server:createWorkspace',
    GET_STATUS: 'server:getStatus',
    GET_HEALTH: 'server:getHealth',
    GET_ACTIVE_SESSIONS: 'server:getActiveSessions',
    SHUTTING_DOWN: 'server:shuttingDown',
    STATUS_CHANGED: 'server:statusChanged',
    HOME_DIR: 'server:homeDir',
  },
  sessions: {
    GET: 'sessions:get',
    GET_UNREAD_SUMMARY: 'sessions:getUnreadSummary',
    MARK_ALL_READ: 'sessions:markAllRead',
    UNREAD_SUMMARY_CHANGED: 'sessions:unreadSummaryChanged',
    CREATE: 'sessions:create',
    DELETE: 'sessions:delete',
    GET_MESSAGES: 'sessions:getMessages',
    SEND_MESSAGE: 'sessions:sendMessage',
    CANCEL: 'sessions:cancel',
    KILL_SHELL: 'sessions:killShell',
    RESPOND_TO_PERMISSION: 'sessions:respondToPermission',
    RESPOND_TO_CREDENTIAL: 'sessions:respondToCredential',
    COMMAND: 'sessions:command',
    GET_PENDING_PLAN_EXECUTION: 'sessions:getPendingPlanExecution',
    GET_PERMISSION_MODE_STATE: 'sessions:getPermissionModeState',
    SET_MEMORY_MODE: 'sessions:setMemoryMode',
    GET_PROVENANCE: 'sessions:getProvenance',
    EVENT: 'session:event',
    GET_MODEL: 'session:getModel',
    SET_MODEL: 'session:setModel',
    GET_FILES: 'sessions:getFiles',
    GET_NOTES: 'sessions:getNotes',
    SET_NOTES: 'sessions:setNotes',
    WATCH_FILES: 'sessions:watchFiles',
    UNWATCH_FILES: 'sessions:unwatchFiles',
    FILES_CHANGED: 'sessions:filesChanged',
    SEARCH_CONTENT: 'sessions:searchContent',
    EXPORT: 'sessions:export',
    IMPORT: 'sessions:import',
    EXPORT_REMOTE_TRANSFER: 'sessions:exportRemoteTransfer',
    IMPORT_REMOTE_TRANSFER: 'sessions:importRemoteTransfer',
  },
  transfer: {
    START: 'transfer:start',
    CHUNK: 'transfer:chunk',
    COMMIT: 'transfer:commit',
    ABORT: 'transfer:abort',
  },
  tasks: {
    // Legacy: background-task output (disabled-feature remnant). Kept for back-compat; retire later.
    GET_OUTPUT: 'tasks:getOutput',
    // Conductor — the Tasks DAG runner.
    VALIDATE: 'tasks:validate',
    CREATE: 'tasks:create',
    GENERATE: 'tasks:generate',
    // Push: the authored spec (or an error) for an async tasks:generate, keyed by orchestratorSessionId.
    GENERATED: 'tasks:generated',
    RUN: 'tasks:run',
    PAUSE: 'tasks:pause',
    RESUME: 'tasks:resume',
    STOP: 'tasks:stop',
    GET: 'tasks:get',
    LIST: 'tasks:list',
    // Storage-backed read of a run's outcome (verdict + per-node output). Survives restart.
    GET_RESULTS: 'tasks:getResults',
  },
  workspaces: {
    GET: 'workspaces:get',
    CREATE: 'workspaces:create',
    CHECK_SLUG: 'workspaces:checkSlug',
    UPDATE_REMOTE: 'workspaces:updateRemote',
  },
  window: {
    GET_WORKSPACE: 'window:getWorkspace',
    GET_MODE: 'window:getMode',
    OPEN_WORKSPACE: 'window:openWorkspace',
    OPEN_SESSION_IN_NEW_WINDOW: 'window:openSessionInNewWindow',
    SWITCH_WORKSPACE: 'window:switchWorkspace',
    CLOSE: 'window:close',
    CLOSE_REQUESTED: 'window:closeRequested',
    CONFIRM_CLOSE: 'window:confirmClose',
    CANCEL_CLOSE: 'window:cancelClose',
    SET_TRAFFIC_LIGHTS: 'window:setTrafficLights',
    FOCUS_STATE: 'window:focusState',
    GET_FOCUS_STATE: 'window:getFocusState',
  },
  file: {
    READ: 'file:read',
    READ_DATA_URL: 'file:readDataUrl',
    READ_PREVIEW_DATA_URL: 'file:readPreviewDataUrl',
    READ_BINARY: 'file:readBinary',
    OPEN_DIALOG: 'file:openDialog',
    READ_ATTACHMENT: 'file:readAttachment',
    READ_USER_ATTACHMENT: 'file:readUserAttachment',
    STORE_ATTACHMENT: 'file:storeAttachment',
    GENERATE_THUMBNAIL: 'file:generateThumbnail',
  },
  fs: {
    SEARCH: 'fs:search',
    LIST_DIRECTORY: 'fs:listDirectory',
  },
  notes: {
    LIST: 'notes:list',
    READ: 'notes:read',
    SAVE: 'notes:save',
    CREATE: 'notes:create',
    RENAME: 'notes:rename',
    DELETE: 'notes:delete',
    RENAME_FOLDER: 'notes:renameFolder',
    DELETE_FOLDER: 'notes:deleteFolder',
    SEARCH: 'notes:search',
    GET_BACKLINKS: 'notes:getBacklinks',
    GET_RENAME_IMPACT: 'notes:getRenameImpact',
    GET_DAILY_NOTE: 'notes:getDailyNote',
    IMPORT_ASSET: 'notes:importAsset',
    LIST_ASSETS: 'notes:listAssets',
    DELETE_ASSET: 'notes:deleteAsset',
    RENAME_ASSET: 'notes:renameAsset',
    UPDATE_PROPERTIES: 'notes:updateProperties',
    WATCH: 'notes:watch',
    UNWATCH: 'notes:unwatch',
    CHANGED: 'notes:changed',
  },
  // knowledge — P1 read-only knowledge provider (spec 03) plus P3 write-back
  // mutation-proposal channels (spec 05) plus P4 Session→Knowledge publication
  // pipeline (spec 06). Engine lifecycle (engineStart/engineStop) remains P7
  // and MUST NOT be added here.
  knowledge: {
    LIST_CONNECTIONS: 'knowledge:listConnections',
    CAPABILITIES: 'knowledge:capabilities',
    SEARCH: 'knowledge:search',
    GET: 'knowledge:get',
    GET_CONTEXT: 'knowledge:getContext',
    GET_BACKLINKS: 'knowledge:getBacklinks',
    SNAPSHOT_CREATE: 'knowledge:snapshotCreate',
    SNAPSHOT_GET: 'knowledge:snapshotGet',
    ENGINE_STATUS: 'knowledge:engineStatus',
    CHANGED: 'knowledge:changed',
    // P3 write-back, spec 05 — safe mutation-proposal lifecycle. All seven are
    // REMOTE_ELIGIBLE (workspace data lives on the workspace-owning server);
    // proposals broadcast via CHANGED (ref of target + change:'updated').
    PROPOSE_MUTATION: 'knowledge:proposeMutation',
    APPROVE_PROPOSAL: 'knowledge:approveProposal',
    REJECT_PROPOSAL: 'knowledge:rejectProposal',
    APPLY_PROPOSAL: 'knowledge:applyProposal',
    ROLLBACK_PROPOSAL: 'knowledge:rollbackProposal',
    GET_PROPOSAL: 'knowledge:getProposal',
    LIST_PROPOSALS: 'knowledge:listProposals',
    // P4 publication pipeline, spec 06 — Session→Knowledge distill/prepare/
    // apply/finalize. All eight are REMOTE_ELIGIBLE (drafts/publications/links
    // live under {workspaceRoot}/knowledge/).
    PUBLISH_DISTILL: 'knowledge:publishDistill',
    PUBLISH_GET_DRAFT: 'knowledge:publishGetDraft',
    PUBLISH_UPDATE_DRAFT: 'knowledge:publishUpdateDraft',
    PUBLISH_PREPARE: 'knowledge:publishPrepare',
    PUBLISH_APPLY: 'knowledge:publishApply',
    PUBLISH_FINALIZE: 'knowledge:publishFinalize',
    PUBLISH_LIST: 'knowledge:publishList',
    LIST_LINKS: 'knowledge:listLinks',
    // P5 saved knowledge views + work envelopes (spec K-09 §3.5 / S-08).
    // All six are REMOTE_ELIGIBLE (views.json + work-envelopes.jsonl live under
    // the workspace root on the workspace-owning server).
    ENVELOPE_GET: 'knowledge:envelopeGet',
    ENVELOPE_UPSERT: 'knowledge:envelopeUpsert',
    ENVELOPE_LIST: 'knowledge:envelopeList',
    VIEWS_LIST: 'knowledge:viewsList',
    VIEW_RUN: 'knowledge:viewRun',
    VIEW_SET_ATTRIBUTE: 'knowledge:viewSetAttribute',
    // P6 knowledge change watcher (poll) — start/stop per connection; emits into AutomationSystem.
    WATCH: 'knowledge:watch',
    UNWATCH: 'knowledge:unwatch',
    // P7-prep G1 metrics (workspace data → REMOTE_ELIGIBLE) + external-local detect (LOCAL_ONLY).
    // Full managed kernel remains blocked on G1 thresholds + G2 legal decision.
    METRICS_GET: 'knowledge:metricsGet',
    DETECT_ENGINE: 'knowledge:detectEngine',
  },
  // siyuan — P2 native knowledge surface (spec 03/P2): embedded SiYuan desktop
  // hosted in a browser pane, keyed by durable document keys (`siyuan:{kind}:{id}`)
  // for dedup + restore. Surface lifecycle manages local BrowserView compositing —
  // all channels are LOCAL_ONLY (browserPane precedent), never proxied.
  siyuan: {
    CREATE_EMBEDDED: 'siyuan:createEmbedded',
    DESTROY: 'siyuan:destroy',
    LIST: 'siyuan:list',
    SYNC_BOUNDS: 'siyuan:syncBounds',
    FOCUS: 'siyuan:focus',
    STATE_CHANGED: 'siyuan:stateChanged',
    REMOVED: 'siyuan:removed',
  },
  debug: {
    LOG: 'debug:log',
  },
  theme: {
    GET_SYSTEM_PREFERENCE: 'theme:getSystemPreference',
    SYSTEM_CHANGED: 'theme:systemChanged',
    APP_CHANGED: 'theme:appChanged',
    GET_APP: 'theme:getApp',
    GET_PRESETS: 'theme:getPresets',
    LOAD_PRESET: 'theme:loadPreset',
    GET_COLOR_THEME: 'theme:getColorTheme',
    SET_COLOR_THEME: 'theme:setColorTheme',
    BROADCAST_PREFERENCES: 'theme:broadcastPreferences',
    PREFERENCES_CHANGED: 'theme:preferencesChanged',
    GET_WORKSPACE_COLOR_THEME: 'theme:getWorkspaceColorTheme',
    SET_WORKSPACE_COLOR_THEME: 'theme:setWorkspaceColorTheme',
    GET_ALL_WORKSPACE_THEMES: 'theme:getAllWorkspaceThemes',
    BROADCAST_WORKSPACE_THEME: 'theme:broadcastWorkspaceTheme',
    WORKSPACE_THEME_CHANGED: 'theme:workspaceThemeChanged',
  },
  system: {
    VERSIONS: 'system:versions',
    HOME_DIR: 'system:homeDir',
    IS_DEBUG_MODE: 'system:isDebugMode',
  },
  update: {
    CHECK: 'update:check',
    GET_INFO: 'update:getInfo',
    INSTALL: 'update:install',
    DISMISS: 'update:dismiss',
    GET_DISMISSED: 'update:getDismissed',
    AVAILABLE: 'update:available',
    DOWNLOAD_PROGRESS: 'update:downloadProgress',
  },
  shell: {
    OPEN_URL: 'shell:openUrl',
    OPEN_FILE: 'shell:openFile',
    SHOW_IN_FOLDER: 'shell:showInFolder',
  },
  menu: {
    NEW_CHAT: 'menu:newChat',
    NEW_WINDOW: 'menu:newWindow',
    OPEN_SETTINGS: 'menu:openSettings',
    KEYBOARD_SHORTCUTS: 'menu:keyboardShortcuts',
    TOGGLE_FOCUS_MODE: 'menu:toggleFocusMode',
    TOGGLE_SIDEBAR: 'menu:toggleSidebar',
    QUIT: 'menu:quit',
    MINIMIZE: 'menu:minimize',
    MAXIMIZE: 'menu:maximize',
    ZOOM_IN: 'menu:zoomIn',
    ZOOM_OUT: 'menu:zoomOut',
    ZOOM_RESET: 'menu:zoomReset',
    TOGGLE_DEV_TOOLS: 'menu:toggleDevTools',
    UNDO: 'menu:undo',
    REDO: 'menu:redo',
    CUT: 'menu:cut',
    COPY: 'menu:copy',
    PASTE: 'menu:paste',
    SELECT_ALL: 'menu:selectAll',
  },
  deeplink: {
    NAVIGATE: 'deeplink:navigate',
  },
  auth: {
    LOGOUT: 'auth:logout',
    SHOW_LOGOUT_CONFIRMATION: 'auth:showLogoutConfirmation',
    SHOW_DELETE_SESSION_CONFIRMATION: 'auth:showDeleteSessionConfirmation',
    SHOW_DELETE_WORKSPACE_CONFIRMATION: 'auth:showDeleteWorkspaceConfirmation',
  },
  credentials: {
    HEALTH_CHECK: 'credentials:healthCheck',
  },
  identity: {
    GET_STATE: 'identity:getState',
    UPDATE_PROFILE: 'identity:updateProfile',
    CONNECT: 'identity:connect',
    DISCONNECT: 'identity:disconnect',
    REFRESH_STATUS: 'identity:refreshStatus',
    CHANGED: 'identity:changed',
  },
  extensions: {
    LIST_CATALOG: 'extensions:listCatalog',
    LIST_INSTALLED: 'extensions:listInstalled',
    SET_ENABLED: 'extensions:setEnabled',
    GET_STATE: 'extensions:getState',
    CHANGED: 'extensions:changed',
  },

  // pluginBridge — SiYuan plugin bridge projections (W6). LOCAL_ONLY.
  // Kernel plugin list is residual; handlers fail-soft / fixture-backed.
  pluginBridge: {
    LIST_PLUGINS: 'pluginBridge:listPlugins',
    GET_PROJECTIONS: 'pluginBridge:getProjections',
    SET_ENABLED: 'pluginBridge:setEnabled',
    OPEN_COMPAT: 'pluginBridge:openCompat', // returns route descriptor only
  },

  // extensionHost — Craft Extension Host lifecycle scaffold (W6).
  // Does NOT execute SiYuan plugins.
  extensionHost: {
    STATUS: 'extensionHost:status',
    RESTART: 'extensionHost:restart',
  },


  onboarding: {
    GET_AUTH_STATE: 'onboarding:getAuthState',
    VALIDATE_MCP: 'onboarding:validateMcp',
    START_MCP_OAUTH: 'onboarding:startMcpOAuth',
    START_CLAUDE_OAUTH: 'onboarding:startClaudeOAuth',
    EXCHANGE_CLAUDE_CODE: 'onboarding:exchangeClaudeCode',
    HAS_CLAUDE_OAUTH_STATE: 'onboarding:hasClaudeOAuthState',
    CLEAR_CLAUDE_OAUTH_STATE: 'onboarding:clearClaudeOAuthState',
    DEFER_SETUP: 'onboarding:deferSetup',
  },
  llmConnections: {
    LIST: 'LLM_Connection:list',
    LIST_WITH_STATUS: 'LLM_Connection:listWithStatus',
    GET: 'LLM_Connection:get',
    GET_API_KEY: 'LLM_Connection:getApiKey',
    SAVE: 'LLM_Connection:save',
    DELETE: 'LLM_Connection:delete',
    TEST: 'LLM_Connection:test',
    SET_DEFAULT: 'LLM_Connection:setDefault',
    SET_WORKSPACE_DEFAULT: 'LLM_Connection:setWorkspaceDefault',
    REFRESH_MODELS: 'LLM_Connection:refreshModels',
    CHANGED: 'LLM_Connection:changed',
  },
  chatgpt: {
    START_OAUTH: 'chatgpt:startOAuth',
    COMPLETE_OAUTH: 'chatgpt:completeOAuth',
    CANCEL_OAUTH: 'chatgpt:cancelOAuth',
    GET_AUTH_STATUS: 'chatgpt:getAuthStatus',
    LOGOUT: 'chatgpt:logout',
  },
  copilot: {
    START_OAUTH: 'copilot:startOAuth',
    CANCEL_OAUTH: 'copilot:cancelOAuth',
    GET_AUTH_STATUS: 'copilot:getAuthStatus',
    LOGOUT: 'copilot:logout',
    DEVICE_CODE: 'copilot:deviceCode',
  },
  settings: {
    SETUP_LLM_CONNECTION: 'settings:setupLlmConnection',
    TEST_LLM_CONNECTION_SETUP: 'settings:testLlmConnectionSetup',
    GET_DEFAULT_THINKING_LEVEL: 'settings:getDefaultThinkingLevel',
    SET_DEFAULT_THINKING_LEVEL: 'settings:setDefaultThinkingLevel',
    GET_NETWORK_PROXY: 'settings:getNetworkProxy',
    SET_NETWORK_PROXY: 'settings:setNetworkProxy',
    GET_SERVER_CONFIG: 'settings:getServerConfig',
    SET_SERVER_CONFIG: 'settings:setServerConfig',
    GET_SERVER_STATUS: 'settings:getServerStatus',
    GET_ENV_OVERRIDES: 'settings:getEnvOverrides',
    SET_ENV_OVERRIDES: 'settings:setEnvOverrides',
  },
  pi: {
    GET_API_KEY_PROVIDERS: 'pi:getApiKeyProviders',
    GET_PROVIDER_BASE_URL: 'pi:getProviderBaseUrl',
    GET_PROVIDER_MODELS: 'pi:getProviderModels',
  },
  dialog: {
    OPEN_FOLDER: 'dialog:openFolder',
  },
  preferences: {
    READ: 'preferences:read',
    WRITE: 'preferences:write',
  },
  drafts: {
    GET: 'drafts:get',
    SET: 'drafts:set',
    DELETE: 'drafts:delete',
    GET_ALL: 'drafts:getAll',
  },
  sources: {
    GET: 'sources:get',
    CREATE: 'sources:create',
    DELETE: 'sources:delete',
    START_OAUTH: 'sources:startOAuth',
    SAVE_CREDENTIALS: 'sources:saveCredentials',
    CHANGED: 'sources:changed',
    GET_PERMISSIONS: 'sources:getPermissions',
    GET_MCP_TOOLS: 'sources:getMcpTools',
  },
  oauth: {
    START: 'oauth:start',
    COMPLETE: 'oauth:complete',
    CANCEL: 'oauth:cancel',
    REVOKE: 'oauth:revoke',
  },
  workspace: {
    GET_PERMISSIONS: 'workspace:getPermissions',
    READ_IMAGE: 'workspace:readImage',
    WRITE_IMAGE: 'workspace:writeImage',
    SETTINGS_GET: 'workspaceSettings:get',
    SETTINGS_UPDATE: 'workspaceSettings:update',
  },
  permissions: {
    GET_DEFAULTS: 'permissions:getDefaults',
    DEFAULTS_CHANGED: 'permissions:defaultsChanged',
  },
  skills: {
    GET: 'skills:get',
    GET_FILES: 'skills:getFiles',
    DELETE: 'skills:delete',
    OPEN_EDITOR: 'skills:openEditor',
    OPEN_FINDER: 'skills:openFinder',
    IMPORT_OMP: 'skills:importOmp',
    // S4: usage metrics from {workspace}/skills/.usage.jsonl + prune (archive, never delete)
    GET_USAGE: 'skills:getUsage',
    PRUNE_UNUSED: 'skills:pruneUnused',
    // T1: copy a workspace skill into {projectRoot}/.agents/skills/<slug>
    EXPORT_TO_PROJECT: 'skills:exportToProject',
    CHANGED: 'skills:changed',
  },
  skillsPending: {
    LIST: 'skillsPending:list',
    APPROVE: 'skillsPending:approve',
    DISMISS: 'skillsPending:dismiss',
    DIFF: 'skillsPending:diff',
    CHANGED: 'skillsPending:changed',
  },
  memory: {
    LIST_LESSONS: 'memory:listLessons',
    ADD_LESSON: 'memory:addLesson',
    UPDATE_LESSON: 'memory:updateLesson',
    DELETE_LESSON: 'memory:deleteLesson',
    GET_CONTEXT: 'memory:getContext',
    GET_PROJECT_MEMORY: 'memory:getProjectMemory',
    UPDATE_CONTEXT: 'memory:updateContext',
    LIST_HISTORY: 'memory:listHistory',
    PROMOTION_CANDIDATES: 'memory:promotionCandidates',
    PROMOTE_LESSON: 'memory:promoteLesson',
    EXPORT: 'memory:export',
    IMPORT: 'memory:import',
    // Y1: 7-day dashboard counters aggregated from both audit.jsonl files,
    // plus the Y4 onboarding marker state.
    INSIGHTS: 'memory:insights',
    MARK_ONBOARDED: 'memory:markOnboarded',
    CHANGED: 'memory:changed',
  },
  statuses: {
    LIST: 'statuses:list',
    REORDER: 'statuses:reorder',
    CHANGED: 'statuses:changed',
  },
  toolchain: {
    STATUS: 'toolchain:status',
    STATUS_CHANGED: 'toolchain:statusChanged',
    UPDATE: 'toolchain:update',
    GET_DISABLED: 'toolchain:getDisabled',
    SET_DISABLED: 'toolchain:setDisabled',
  },
  labels: {
    LIST: 'labels:list',
    CREATE: 'labels:create',
    DELETE: 'labels:delete',
    CHANGED: 'labels:changed',
  },
  views: {
    LIST: 'views:list',
    SAVE: 'views:save',
  },
  toolIcons: {
    GET_MAPPINGS: 'toolIcons:getMappings',
  },
  logo: {
    GET_URL: 'logo:getUrl',
  },
  notification: {
    SHOW: 'notification:show',
    NAVIGATE: 'notification:navigate',
    GET_ENABLED: 'notification:getEnabled',
    SET_ENABLED: 'notification:setEnabled',
  },
  input: {
    GET_AUTO_CAPITALISATION: 'input:getAutoCapitalisation',
    SET_AUTO_CAPITALISATION: 'input:setAutoCapitalisation',
    GET_SEND_MESSAGE_KEY: 'input:getSendMessageKey',
    SET_SEND_MESSAGE_KEY: 'input:setSendMessageKey',
    GET_SPELL_CHECK: 'input:getSpellCheck',
    SET_SPELL_CHECK: 'input:setSpellCheck',
  },
  power: {
    GET_KEEP_AWAKE: 'power:getKeepAwake',
    SET_KEEP_AWAKE: 'power:setKeepAwake',
  },
  appearance: {
    GET_RICH_TOOL_DESCRIPTIONS: 'appearance:getRichToolDescriptions',
    SET_RICH_TOOL_DESCRIPTIONS: 'appearance:setRichToolDescriptions',
    GET_DEFAULT_ZOOM_LEVEL: 'appearance:getDefaultZoomLevel',
    SET_DEFAULT_ZOOM_LEVEL: 'appearance:setDefaultZoomLevel',
  },
  tools: {
    GET_BROWSER_TOOL_ENABLED: 'tools:getBrowserToolEnabled',
    SET_BROWSER_TOOL_ENABLED: 'tools:setBrowserToolEnabled',
  },
  caching: {
    GET_EXTENDED_PROMPT_CACHE: 'caching:getExtendedPromptCache',
    SET_EXTENDED_PROMPT_CACHE: 'caching:setExtendedPromptCache',
    GET_ENABLE_1M_CONTEXT: 'caching:getEnable1MContext',
    SET_ENABLE_1M_CONTEXT: 'caching:setEnable1MContext',
  },
  rtk: {
    GET_ENABLED: 'rtk:getEnabled',
    SET_ENABLED: 'rtk:setEnabled',
    GET_STATUS: 'rtk:getStatus',
    GET_GAIN: 'rtk:getGain',
  },
  badge: {
    REFRESH: 'badge:refresh',
    SET_ICON: 'badge:setIcon',
    DRAW: 'badge:draw',
    DRAW_WINDOWS: 'badge:draw-windows',
  },
  releaseNotes: {
    GET: 'releaseNotes:get',
    GET_LATEST_VERSION: 'releaseNotes:getLatestVersion',
  },
  git: {
    GET_BRANCH: 'git:getBranch',
  },
  gitbash: {
    CHECK: 'gitbash:check',
    BROWSE: 'gitbash:browse',
    SET_PATH: 'gitbash:setPath',
  },
  browserPane: {
    CREATE: 'browser-pane:create',
    CREATE_EMBEDDED: 'browser-pane:create-embedded',
    SYNC_BOUNDS: 'browser-pane:sync-bounds',
    DESTROY: 'browser-pane:destroy',
    LIST: 'browser-pane:list',
    NAVIGATE: 'browser-pane:navigate',
    GO_BACK: 'browser-pane:go-back',
    GO_FORWARD: 'browser-pane:go-forward',
    RELOAD: 'browser-pane:reload',
    STOP: 'browser-pane:stop',
    FOCUS: 'browser-pane:focus',
    RESIZE: 'browser-pane:resize',
    SNAPSHOT: 'browser-pane:snapshot',
    CLICK: 'browser-pane:click',
    CLICK_AT: 'browser-pane:click-at',
    FILL: 'browser-pane:fill',
    TYPE: 'browser-pane:type',
    KEY: 'browser-pane:key',
    SELECT: 'browser-pane:select',
    SCREENSHOT: 'browser-pane:screenshot',
    EVALUATE: 'browser-pane:evaluate',
    SCROLL: 'browser-pane:scroll',
    LAUNCH: 'browser-empty-state:launch',
    STATE_CHANGED: 'browser-pane:state-changed',
    REMOVED: 'browser-pane:removed',
    INTERACTED: 'browser-pane:interacted',
  },
  automations: {
    GET: 'automations:get',
    TEST: 'automations:test',
    SET_ENABLED: 'automations:setEnabled',
    DUPLICATE: 'automations:duplicate',
    DELETE: 'automations:delete',
    GET_HISTORY: 'automations:getHistory',
    GET_LAST_EXECUTED: 'automations:getLastExecuted',
    REPLAY: 'automations:replay',
    CHANGED: 'automations:changed',
  },
  resources: {
    EXPORT: 'resources:export',
    IMPORT: 'resources:import',
  },
  projects: {
    GET: 'projects:get',
    GET_ONE: 'projects:getOne',
    CREATE: 'projects:create',
    UPDATE: 'projects:update',
    DELETE: 'projects:delete',
    LIST_ASSETS: 'projects:listAssets',
    UPLOAD_ASSET: 'projects:uploadAsset',
    DELETE_ASSET: 'projects:deleteAsset',
    CHANGED: 'projects:changed',
  },
  kanban: {
    GET_CONFIG: 'kanban:getConfig',
    SET_CONFIG: 'kanban:setConfig',
    CHANGED: 'kanban:changed',
  },

  messaging: {
    // WhatsApp subprocess → Gateway (subprocess invokes on server)
    WA_REGISTER: 'messaging:wa:register',
    WA_INCOMING: 'messaging:wa:incoming',
    WA_BUTTON_PRESS: 'messaging:wa:buttonPress',
    WA_STATUS: 'messaging:wa:status',
    WA_QR: 'messaging:wa:qr',
    // Gateway → WhatsApp subprocess (server invokes on client)
    WA_SEND: 'messaging:wa:send',
    WA_SEND_BUTTONS: 'messaging:wa:sendButtons',
    WA_SEND_TYPING: 'messaging:wa:sendTyping',
    WA_SEND_FILE: 'messaging:wa:sendFile',
    WA_CONNECT: 'messaging:wa:connect',
    WA_DISCONNECT: 'messaging:wa:disconnect',
    // Gateway → UI clients (broadcast)
    BINDING_CHANGED: 'messaging:bindingChanged',
    PLATFORM_STATUS: 'messaging:platformStatus',
    /** Broadcast when the workspace's pending-senders list mutates. */
    PENDING_CHANGED: 'messaging:pendingChanged',
    // UI ↔ Server (config/binding CRUD)
    GET_CONFIG: 'messaging:getConfig',
    UPDATE_CONFIG: 'messaging:updateConfig',
    TEST_TELEGRAM: 'messaging:testTelegram',
    SAVE_TELEGRAM: 'messaging:saveTelegram',
    TEST_LARK: 'messaging:testLark',
    SAVE_LARK: 'messaging:saveLark',
    TEST_DISCORD: 'messaging:testDiscord',
    SAVE_DISCORD: 'messaging:saveDiscord',
    // UI ↔ Server — WeChat (微信) iLink QR login flow
    WECHAT_START_CONNECT: 'messaging:wechat:startConnect',
    WECHAT_SUBMIT_CODE: 'messaging:wechat:submitCode',
    WECHAT_UI_EVENT: 'messaging:wechat:uiEvent',
    DISCONNECT: 'messaging:disconnect',
    FORGET: 'messaging:forget',
    GET_BINDINGS: 'messaging:getBindings',
    GENERATE_CODE: 'messaging:generateCode',
    UNBIND: 'messaging:unbind',
    UNBIND_BINDING: 'messaging:unbindBinding',
    /** Workspace-supergroup pairing (Telegram forum support). UI ↔ Server. */
    GENERATE_SUPERGROUP_CODE: 'messaging:generateSupergroupCode',
    GET_SUPERGROUP: 'messaging:getSupergroup',
    UNBIND_SUPERGROUP: 'messaging:unbindSupergroup',
    // UI ↔ Server — WhatsApp pairing/connection flow (Baileys subprocess adapter)
    WA_START_CONNECT: 'messaging:wa:startConnect',
    WA_SUBMIT_PHONE: 'messaging:wa:submitPhone',
    /** Broadcast to UI clients: QR string, pairing code, status, unavailable, error. */
    WA_UI_EVENT: 'messaging:wa:uiEvent',
    // UI ↔ Server — Access control (per-platform owners + per-binding allow-list)
    GET_PLATFORM_OWNERS: 'messaging:access:getOwners',
    SET_PLATFORM_OWNERS: 'messaging:access:setOwners',
    GET_PLATFORM_ACCESS_MODE: 'messaging:access:getMode',
    SET_PLATFORM_ACCESS_MODE: 'messaging:access:setMode',
    GET_PENDING_SENDERS: 'messaging:access:getPending',
    DISMISS_PENDING_SENDER: 'messaging:access:dismissPending',
    ALLOW_PENDING_SENDER: 'messaging:access:allowPending',
    SET_BINDING_ACCESS: 'messaging:access:setBindingAccess',
    // UI ↔ Server — WeChat QR-login flow (in-process, iLink long-poll)
    WC_START_CONNECT: 'messaging:wc:startConnect',
    WC_CANCEL_CONNECT: 'messaging:wc:cancelConnect',
    /** Broadcast to UI clients: QR image url, scaned, confirmed, expired, error. */
    WC_UI_EVENT: 'messaging:wc:uiEvent',
  },
  contextDocs: {
    LIST: 'contextDocs:list',
    READ: 'contextDocs:read',
    WRITE: 'contextDocs:write',
    DELETE: 'contextDocs:delete',
    READ_TEMPLATE: 'contextDocs:readTemplate',
    ACCEPT_TEMPLATE: 'contextDocs:acceptTemplate',
    KEEP_MINE_TEMPLATE: 'contextDocs:keepMineTemplate',
    CHANGED: 'contextDocs:CHANGED',
  },
  bundledSkills: {
    LIST: 'bundledSkills:list',
    GET_DISABLED: 'bundledSkills:getDisabled',
    SET_DISABLED: 'bundledSkills:setDisabled',
    CHANGED: 'bundledSkills:CHANGED',
  },
  marketplace: {
    CATALOG: 'marketplace:catalog',
    STATS: 'marketplace:stats',
    INSTALL: 'marketplace:install',
    REMOVE: 'marketplace:remove',
    UPDATE: 'marketplace:update',
    REFRESH: 'marketplace:refresh',
    /** Progress push during install/update (clone/verify/install/fetch). */
    PROGRESS: 'marketplace:progress',
    CHANGED: 'marketplace:CHANGED',
  },
} as const

// IPC_CHANNELS compat alias removed — all consumers now use RPC_CHANNELS

/**
 * Flatten all channel string values from the nested RPC_CHANNELS object.
 * Used by the exhaustive routing test to ensure every channel is classified.
 */
export function getAllChannelValues(): string[] {
  const values: string[] = []
  for (const namespace of Object.values(RPC_CHANNELS)) {
    for (const channel of Object.values(namespace)) {
      values.push(channel)
    }
  }
  return values
}
