import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const root=process.cwd(), base='e780e73ae84c977cf81546b49140d318dfcd6049';
const wp=read('plans/macro-integration/work-packages.json').workPackages;
const slices=read('plans/macro-integration/cloud/ui-slices.json');
const sources=['collaboration','domain','shared'].map(n=>({path:`plans/macro-integration/${n}-screen-contracts.json`,data:read(`plans/macro-integration/${n}-screen-contracts.json`)}));
const screens=sources.flatMap(s=>s.data.screenContracts.map(x=>({...x,contractSource:s.path})));
for(const s of screens){const owner=slices.screenPrimaryUiOwners?.[s.id];if(!owner)continue;if(!s.workPackages.includes(owner))throw new Error('screen UI owner absent from prerequisites '+s.id);const paths=[...(s.implementationFiles?.extend||[]),...(s.implementationFiles?.new||[])];slices.explicitUiOwnership[owner]=[...new Set([...(slices.explicitUiOwnership[owner]||[]),...paths])];}
const out='plans/macro-integration/cloud'; fs.mkdirSync(`${out}/packets`,{recursive:true});
const domainLanes={};
function lanes(w){const p=w.id;if(p==='WP-48')return ['linux-domain']; const l=['linux-domain']; const allFiles=[...w.affectedFiles,...(slices.explicitUiOwnership[p]||[])];if(allFiles.some(f=>f.includes('renderer'))||screens.some(s=>s.workPackages.includes(p)))l.push('linux-renderer'); if(allFiles.some(f=>f.includes('apps/electron'))||['WP-35','WP-46','WP-51'].includes(p))l.push('macos-native'); if(['WP-17','WP-18','WP-19','WP-20','WP-21','WP-27','WP-28','WP-29','WP-31','WP-32','WP-33','WP-34','WP-47','WP-52'].includes(p))l.push('provider-live'); return l;}
const packets=wp.map(w=>{const ui=screens.filter(s=>s.workPackages.includes(w.id)); return {schemaVersion:1,id:w.id,title:w.title,status:'planned',repository:'rox-one/rox-one',sourceBaseline:base,integrationBasePolicy:'scheduler supplies exact current inputSha; original source baseline is reference, never reset over prerequisite commits',ownerRole:w.ownerRole,dependencies:w.dependencies,allowedPaths:[...new Set([...w.affectedFiles,...w.newFiles])].sort(),sharedFileRule:'one owner per overlapping exact file/directory; registry/transport/migration/shared contracts/lockfiles serialized; agents propose interface change to owner',readFirst:['AGENTS.md','cloud/macro-integration/AGENTS.md','docs/macro-integration/product/PRD.md','docs/macro-integration/product/UI-UX-CONTRACT.md','docs/macro-integration/19-target-architecture.md','docs/macro-integration/18-licensing.md',...new Set(ui.map(s=>s.contractSource)),...w.affectedFiles],goal:w.goal,expectedResults:w.acceptanceCriteria,screenRefs:ui.map(s=>({id:s.id,contractSource:s.contractSource,controls:s.controls.map(c=>c.id),placement:s.navigation?.placement||s.placement||s.currentDestination,proposedRoute:s.navigation?.proposedRoute||s.proposedRoute,uiStatus:s.implementationStatus||s.status})),domainSpecification:w,lanes:lanes(w),requiredEvidence:['commitSha','inputSha','specDigest','changedPaths','test command/output hash/expected-observed','negativeControl and reproduction seed','reload/recovery evidence','per-lane outcome','screenshots/ARIA for visible change','permission and source provenance checks','provider read-back if external effect','independent review'],delivery:{branch:`impl/macro-${w.id.toLowerCase()}`,output:'commit + patch/draft PR + completion receipt; no automatic merge/deploy',receiptPath:`plans/macro-integration/cloud/receipts/${w.id}.json`,state:'verified only when every required lane passes; blocked/pending lanes keep implementation incomplete'},failurePolicy:'stop dependent step on required missing input; continue independent allowed work; no fake provider/device success',testScope:'project targeted tests first, then required gates; no optional entire-repo sweeps; current baseline failures recorded separately',license:'behavior reimplementation unless exact source origin approved; no blind AGPL/proprietary UI source copy'};});
const manifest={schemaVersion:1,program:'macro-integration-revision-3',referenceCodeSha:base,specDigest:null,launchState:'PREPARED_NOT_LAUNCHED',scope:'cloud coding packets; no credentials/purchase/deployment performed',lanes:{'linux-domain':{environment:'Linux24.04, pinned Bun1.3.14, Node22, PostgreSQL for integration; targeted tests',proof:'domain/API/DB/concurrency/recovery and negative controls'},'linux-renderer':{environment:'Linux Chromium Playwright synthetic fixtures explicitly fixture',proof:'interactions/ARIA/loading/empty/error/keyboard/narrow/reduced-motion screenshots'},'macos-native':{environment:'macOS Electron pinned source build, controlled test workspace',proof:'IPC/preload/fonts/capture/import/device permissions actual runtime'},'provider-live':{environment:'dedicated test tenant/self-host media/provider sandbox, scoped ephemeral credentials',proof:'external read-back and callback/retry/reconciliation; never inferred from fixture'}},minimumResources:{linuxDomainDiskGiB:8,linuxRendererDiskGiB:16,ramGiB:8,cpus:4,meaning:'conservative preflight minimum; install/build footprint measured before expanding lane, not actual benchmark'},environment:{bun:'1.3.14',node:'22',lockfile:'bun.lock',ci:'existing CI is self-hosted; this packet preparation does not provision a new runner'},workPackages:packets.map(p=>({id:p.id,dependencies:p.dependencies,allowedPaths:p.allowedPaths,lanes:p.lanes,packet:`${out}/packets/${p.id}.json`,prompt:`cloud/macro-integration/packets/${p.id}.md`}))};
for(const p of packets){p.uiSlice={goal:slices.slices[p.id],boundary:slices.rule,assignedUiPaths:slices.explicitUiOwnership[p.id]||[],existingUiSeams:(slices.explicitUiOwnership[p.id]||[]).filter(f=>fs.existsSync(f)),newUiFiles:(slices.explicitUiOwnership[p.id]||[]).filter(f=>!fs.existsSync(f)),screenFinalDoD:'Referenced full-screen contracts are shared final behavior; this WP owns only uiSlice goal. Reuse prerequisite code. Do not mark full screen done before other feature owners finish.'};p.contractSupplement={path:'plans/macro-integration/cloud/contract-amendments.json',precedence:'Revision3 supplement + leaf contracts refine original primary schemas; extend/test typed schemas before new control dispatch; alias means one authority'};p.readFirst.push(p.contractSupplement.path);p.readFirst=[...new Set([...p.readFirst,...p.uiSlice.existingUiSeams])];p.allowedPaths.push(...p.uiSlice.assignedUiPaths);if(p.lanes.includes('linux-renderer'))p.allowedPaths.push(...['de','en','es','fr','hu','ja','pl','ru','zh-Hans','zh-Hant'].map(l=>`packages/shared/src/i18n/locales/${l}.json`));p.allowedPaths=[...new Set(p.allowedPaths)].sort();const row=manifest.workPackages.find(w=>w.id===p.id);row.allowedPaths=p.allowedPaths;}
const specPaths=[...sources.map(s=>s.path),'plans/macro-integration/cloud/ui-slices.json','plans/macro-integration/cloud/contract-amendments.json','docs/macro-integration/product/PRD.md','docs/macro-integration/product/UI-UX-CONTRACT.md','docs/macro-integration/19-target-architecture.md','docs/macro-integration/18-licensing.md','plans/macro-integration/work-packages.json','plans/macro-integration/dependency-dag.json','cloud/macro-integration/AGENTS.md','cloud/macro-integration/SPEC.md','cloud/macro-integration/completion.schema.json','scripts/macro-integration/cloud/gates.mjs','scripts/macro-integration/cloud/cli.mjs','scripts/macro-integration/cloud/build.mjs'];
manifest.specInputs=specPaths.map(p=>({path:p,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')}));
const digest=crypto.createHash('sha256').update(JSON.stringify(packets)).update(JSON.stringify(manifest.specInputs)).digest('hex'); manifest.specDigest=digest;
fs.mkdirSync('cloud/macro-integration/packets',{recursive:true});
for(const p of packets){p.specDigest=digest;fs.writeFileSync(`${out}/packets/${p.id}.json`,JSON.stringify(p,null,2)+'\n');let md=`# ${p.id}: ${p.title}\n\nStatus: planned. Specification digest: ${digest}. Exact integration inputSha supplied by scheduler; reference code ${base}.\n\n## Mission and expected result\n\n${p.goal}\n\n${p.expectedResults.map(x=>'- '+x).join('\n')}\n\n## Prerequisites\n\n${p.dependencies.length?p.dependencies.join(', '):'No WP prerequisites; authenticated bootstrap constraints still apply.'}\n\nRead prerequisite verified receipts; commits must be ancestors of inputSha. Never checkout the original baseline over dependency changes.\n\n## Read first\n\n${p.readFirst.map(x=>'- '+x).join('\n')}\n\n## Owned files\n\n${p.allowedPaths.map(x=>'- '+x).join('\n')}\n\n${p.sharedFileRule}. New unexpected files require scheduler ownership update.\n\n## Exact UI/UX\n\n`;for(const s of p.screenRefs)md+=`- ${s.id} in ${s.contractSource}; controls ${s.controls.join(', ')}; use leaf inputs/outputs/hover/focus/click/keyboard/states/DoD.\n`;if(!p.screenRefs.length)md+='Backend/deployment slice: no new product screen unless domain specification explicitly requires one; observable receipt/API behavior is mandatory.\n';md+=`\n## Domain / persistence / API / realtime\n\nCanonical specification: ${out}/packets/${p.id}.json → domainSpecification (complete original work package including commands, request/response schemas, DB migration and events).\n\nAPI: ${p.domainSpecification.apiChanges}. DB: ${p.domainSpecification.dbChanges}.\n\nEvents: ${p.domainSpecification.events.join(', ')}.\n\nPermissions: authenticated Actor and resource gateway; every existing RPC/IPC/tool/storage path guarded; no renderer-assigned principal.\n\n## DoD and proof\n\n${p.requiredEvidence.map(x=>'- [ ] '+x).join('\n')}\n\nRequired lanes: ${p.lanes.join(', ')}. A lane is pending until actual environment passes. Targeted RED→GREEN with seeded failing control→reload/restart/reconnect→adjacent regression→independent review. Product runtime gates are not satisfied by these planning artifact validators.\n\n## Cloud return contract\n\nReturn ${p.delivery.receiptPath}, exact commit/diff, redacted test logs/hashes and screenshots, open questions with actionable missing state. Output ${p.delivery.output}. No secrets in logs/artifacts. Fixture vs live triad retained. No merge/deploy.\n`;md+=`\n## Assigned UI slice and stage boundary\n\n${p.uiSlice.goal}\n\n${p.uiSlice.boundary}\n\n${p.uiSlice.screenFinalDoD}\n`;fs.writeFileSync(`cloud/macro-integration/packets/${p.id}.md`,md);const row=manifest.workPackages.find(w=>w.id===p.id);row.packetSha256=crypto.createHash('sha256').update(fs.readFileSync(row.packet)).digest('hex');row.promptSha256=crypto.createHash('sha256').update(fs.readFileSync(row.prompt)).digest('hex');}
fs.writeFileSync(`${out}/manifest.json`,JSON.stringify(manifest,null,2)+'\n');
fs.writeFileSync(`${out}/screen-index.json`,JSON.stringify({schemaVersion:1,screens:screens.map(s=>({id:s.id,title:s.title||s.titleRu,source:s.contractSource,workPackages:s.workPackages,controls:s.controls.map(c=>c.id)}))},null,2)+'\n');
console.log(JSON.stringify({packets:packets.length,screens:screens.length,controls:screens.reduce((n,s)=>n+s.controls.length,0),specDigest:digest}));
