import fs from 'node:fs';
import os from 'node:os';
import cp from 'node:child_process';
import {readJSON,ready,validateReceipt,safeProof,git,isAncestor,machinePreflight,sha256} from './gates.mjs';
import {loadInputs,validateHandoff} from '../control-handoff.mjs';
const root=process.cwd(),manifest=readJSON('plans/macro-integration/cloud/manifest.json');
const [cmd,arg,...rest]=process.argv.slice(2);
function verifyArtifactBytes(){for(const i of manifest.specInputs)if(sha256(fs.readFileSync(i.path))!==i.sha256)throw new Error('spec input drift '+i.path);for(const p of manifest.workPackages){if(sha256(fs.readFileSync(p.packet))!==p.packetSha256||sha256(fs.readFileSync(p.prompt))!==p.promptSha256)throw new Error('packet/prompt bytes drift '+p.id);}}
if(['render','ready','validate'].includes(cmd))verifyArtifactBytes();
if(cmd==='render'){const p=manifest.workPackages.find(p=>p.id===arg);if(!p)throw new Error('unknown WP');process.stdout.write(fs.readFileSync(p.prompt,'utf8'));}
else if(cmd==='validate'){
 const {catalogs,ownership}=loadInputs(root),handoff=readJSON('plans/macro-integration/control-handoff.json'),handoffErrors=validateHandoff(handoff,catalogs,ownership);if(handoffErrors.length)throw Error(handoffErrors.join('\n'));
 for(const c of handoff.controls){const owner=manifest.workPackages.find(w=>w.id===c.primaryUiOwner);if(!owner?.allowedPaths.includes(c.testFile))throw Error('unallocated primary control test '+c.id);}
 for(const i of manifest.specInputs)if(sha256(fs.readFileSync(i.path))!==i.sha256)throw new Error('spec input drift '+i.path);
 const screens=readJSON('plans/macro-integration/cloud/screen-index.json').screens,ids=new Set(),wps=new Set(manifest.workPackages.map(p=>p.id));for(const s of screens){if(ids.has(s.id))throw new Error('duplicate screen');ids.add(s.id);if(new Set(s.controls).size!==s.controls.length)throw new Error('duplicate control');for(const w of s.workPackages)if(!wps.has(w))throw new Error('unknown screen WP');}
 const slices=readJSON('plans/macro-integration/cloud/ui-slices.json');for(const n of ['collaboration','domain','shared'])for(const s of readJSON(`plans/macro-integration/${n}-screen-contracts.json`).screenContracts){for(const f of [...(s.implementationFiles?.extend||[]),...(s.implementationFiles?.new||[])]){if(!manifest.workPackages.some(p=>s.workPackages.includes(p.id)&&p.allowedPaths.some(a=>f===a||f.startsWith(a+'/'))))throw new Error('unallocated screen implementation file '+s.id+' '+f);}const owner=slices.screenPrimaryUiOwners?.[s.id];if(owner&&!s.workPackages.includes(owner))throw new Error('unlinked screen owner '+s.id);}
 for(const seam of slices.additionalRoutedSeams||[])for(const owner of seam.owners)for(const f of seam.files){const p=manifest.workPackages.find(p=>p.id===owner);if(!p||!p.allowedPaths.some(a=>f===a||f.startsWith(a+'/')))throw new Error('unallocated routed seam '+owner+' '+f);if(!fs.existsSync(f))throw new Error('missing existing routed seam '+f);}
 const visited=new Set(),active=new Set();function walk(p){if(active.has(p.id))throw new Error('DAG cycle');if(visited.has(p.id))return;active.add(p.id);for(const d of p.dependencies){const dep=manifest.workPackages.find(x=>x.id===d);if(!dep)throw new Error('missing dependency');walk(dep);}active.delete(p.id);visited.add(p.id);}for(const p of manifest.workPackages){walk(p);const q=readJSON(p.packet);if(sha256(fs.readFileSync(p.packet))!==p.packetSha256||sha256(fs.readFileSync(p.prompt))!==p.promptSha256)throw new Error('packet/prompt bytes drift');if(q.specDigest!==manifest.specDigest)throw new Error('packet digest mismatch');if(q.id!==p.id||JSON.stringify(q.dependencies)!==JSON.stringify(p.dependencies))throw new Error('packet identity/deps drift');if(!fs.existsSync(p.prompt))throw new Error('missing prompt');for(const s of q.screenRefs){if(!ids.has(s.id))throw new Error('unknown packet screen');const i=screens.find(x=>x.id===s.id);if(JSON.stringify(i.controls)!==JSON.stringify(s.controls))throw new Error('control drift');}for(const f of q.domainSpecification.affectedFiles)if(!fs.existsSync(f))throw new Error('missing existing path '+f);}
 console.log(JSON.stringify({status:'passed',kind:'planning-integrity-only',packets:manifest.workPackages.length,screens:screens.length,controls:screens.reduce((n,s)=>n+s.controls.length,0)},null,2));
}else if(cmd==='ready'){
 if(!/^[a-f0-9]{40}$/.test(arg||''))throw new Error('exact inputSha required');if(git(root,'rev-parse','HEAD')!==arg)throw new Error('checkout does not match inputSha');const dir='plans/macro-integration/cloud/receipts',receipts={};if(fs.existsSync(dir))for(const f of fs.readdirSync(dir).filter(f=>f.endsWith('.json'))){const r=readJSON(dir+'/'+f);receipts[r.wpId]=r;}
 for(const i of manifest.specInputs)if(sha256(fs.readFileSync(i.path))!==i.sha256)throw new Error('spec input drift '+i.path);
 const result=ready(manifest,receipts,{active:rest,verify:(r,p)=>validateReceipt(r,p,manifest,{root,inputSha:arg,verifyProof:true,isAncestor:(a,b)=>isAncestor(root,a,b),actualChangedPaths:(a,b)=>git(root,'diff','--name-only',a,b).split('\n').filter(Boolean)})});console.log(JSON.stringify({inputSha:arg,execution:'not-launched',...result},null,2));
}else if(cmd==='preflight'){
 const stats=fs.statfsSync(root),run=c=>{try{return cp.execFileSync(c[0],c.slice(1),{encoding:'utf8'}).trim();}catch{return 'unavailable';}};
 const lane=rest[0]||'linux-domain';if(!Object.keys(manifest.lanes).includes(lane))throw new Error('unknown lane');
 const r=machinePreflight({actualSha:git(root,'rev-parse','HEAD'),expectedSha:arg,dirty:git(root,'status','--porcelain').length>0,diskGiB:stats.bavail*stats.bsize/2**30,ramGiB:os.totalmem()/2**30,cpus:os.cpus().length,platform:os.platform(),lane,bunVersion:run(['bun','--version']),nodeMajor:Number(run(['node','--version']).replace(/^v/,'').split('.')[0])});console.log(JSON.stringify({...r,kind:'machine-prerequisites-only',providers:'not-probed, no secret access or launch'},null,2));if(r.status!=='ready')process.exitCode=2;
}else throw new Error('usage: cli.mjs validate | render WP-ID | ready <40-char inputSha> [activeWP...] | preflight <inputSha> [lane]');
