import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
const root = process.argv[2] ?? process.cwd();
const dest = join(root,'plans/macro-integration');
const snapshots=JSON.parse(readFileSync(join(dest,'source-snapshots.json'),'utf8')).snapshots;
const p = 'packages/core/src/rox2/platform-contract.ts';
const domains={
  identity:[p,'packages/server-core/src/transport/types.ts','packages/server-core/src/handlers/rpc/identity.ts','packages/shared/src/orgs/types.ts'],
  graph:[p,'packages/core/src/rox2/project-membership.ts','packages/core/src/rox2/surface-context.ts'],
  commands:[p,'packages/server-core/src/handlers/rpc/command-gateway.ts','packages/server-core/src/transport/types.ts'],
  search:['packages/server-core/src/handlers/rpc/knowledge.ts','packages/server-core/src/handlers/rpc/memory.ts','packages/core/src/rox2/surface-context.ts'],
  attention:['packages/shared/src/team/state.ts','packages/shared/src/team/sync.ts','apps/electron/src/main/notifications.ts','apps/electron/src/renderer/pages/inbox/inbox-model.ts'],
  messaging:['packages/shared/src/team/types.ts','packages/shared/src/team/state.ts','packages/server-core/src/handlers/rpc/messaging.ts','packages/shared/src/agent/session-tool-defs.ts'],
  pages:['packages/shared/src/pages/types.ts','packages/shared/src/pages/storage.ts','packages/server-core/src/handlers/rpc/pages.ts','apps/electron/src/renderer/components/pages/PageView.tsx'],
  tasks:['packages/core/src/tasks/personal/types.ts','packages/server-core/src/tasks/personal-tasks-service.ts','packages/server-core/src/handlers/rpc/personal-tasks.ts','apps/electron/src/renderer/pages/tasks/TaskDetail.tsx'],
  projects:['packages/shared/src/projects/types.ts','packages/shared/src/projects/storage.ts','packages/server-core/src/handlers/rpc/projects.ts','packages/core/src/rox2/project-membership.ts'],
  notes:['packages/core/src/rox2/notes-engine.ts','packages/server-core/src/handlers/rpc/notes.ts','apps/electron/src/renderer/pages/notes/NotesViewHost.tsx'],
  mail:['packages/shared/src/mail/jmap-client.ts','apps/electron/src/main/mail/mail-service.ts','apps/electron/src/renderer/pages/inbox/mail/useMail.ts'],
  crm:['apps/electron/src/renderer/pages/extra-screens/dossier/dossier-model.ts','apps/electron/src/renderer/pages/extra-screens/dossier/DossierPage.tsx',p],
  calendar:['packages/core/src/calendar/types.ts','packages/core/src/calendar/adapters.ts','packages/core/src/calendar/store.ts','packages/core/src/calendar/occurrences.ts'],
  calls:['packages/core/src/meetings/model.ts','packages/server-core/src/meetings/rooms.ts','packages/server-core/src/handlers/rpc/meetings.ts','apps/electron/src/renderer/pages/meetings/MeetingsWorkspace.tsx'],
  agents:['packages/shared/src/agent/session-tool-defs.ts','packages/core/src/rox2/surface-context.ts','packages/server-core/src/meetings/executor.ts'],
  automation:['packages/shared/src/automations/types.ts','packages/shared/src/automations/meeting-followup.ts','packages/server-core/src/handlers/rpc/automations.ts'],
  files:['packages/server-core/src/handlers/rpc/files.ts','packages/shared/src/projects/storage.ts','packages/shared/src/pages/share-bundle.ts'],
};
// Each row supplies a distinct independently observable operation, persistence and failure contract.
// id,title,domain,deps,entities,API,DB,events,acceptance,risk,complexity
const seeds=[
['01','Private shared Project: authenticated actor and workspace boundary','identity',[],['principal','workspace','project'],'CreateSharedProject / GetProject; Actor injected in RPC and HTTP','principal, auth_subject_alias, workspace_member, project; unique workspace membership','workspace.member_joined, project.created','A opens private Project in native ROX; B without membership gets 403 and no title through RPC/HTTP; client cannot forge principal/workspace','Existing RequestContext lacks authenticated principal; local profile must not become remote identity by email','XL'],
['02','Canonical Rox2 registry, alias import and typed backlinks','graph',['01'],['entity','entity_alias','entity_link'],'RegisterEntity / LinkEntity / GetBacklinks; extend kinds additively','entity/alias/link scoped composite keys; type+source provenance; cycle guards','entity.created, entity.linked','Retry same provider binding reuses one entity; collision quarantines; backlink is symmetric query; cross-workspace and forbidden cycle rejected','Legacy path IDs and provider accounts collide; typed enum migration must preserve unknown payloads','L'],
['03','Unified resource grants and revocation during open surface','identity',['01','02'],['permission_grant','policy_epoch'],'Authorize / Grant / Revoke / Subscribe; add resource-scoped action vocabulary','grant subject/resource/action/expiry; epoch monotonic in revoke tx','permission.changed','Viewer cannot edit/share; editor loses subscription and future reads after revoke; agent allow-all still denied; preview/link/search hide revoked target','Cached plaintext cannot be made unread retroactively; channels/mail inheritance must be explicit','XL'],
['04','Durable revisioned command and outbox receipt in Project update','commands',['02','03'],['command_receipt','domain_event','outbox','project'],'UpdateProject expectedRevision/idempotencyKey; native adapter uses same gateway','project mutation+receipt+event atomic; consumer inbox unique; immutable request hash','entity.updated, project.updated','Crash after commit before response: retry yields same Project revision/event; stale version 409; same key altered payload rejected; event replay dedup','Legacy direct store writes can bypass gateway; revision continuity across import','L'],
['05','Shared client projection and offline replay with policy rejection','commands',['04'],['client_projection','local_outbox'],'SyncSince(cursor) / ReplayCommand / GetCommandReceipt','SQLite shared projection/outbox, durable cursor; personal local-authority adapter separate','projection.advanced, command.rejected','Offline task edit remains queued; reconnect accepted once; revoked queued mutation rejected and draft quarantined; restart restores queue; standalone personal task regression','Dual writable authorities and silent personal-to-team exposure','XL'],
['06','Search and Memory projection for authorized Page/Task','search',['04'],['search_document','memory_provenance'],'Search scoped by actor / GetProjectionWatermark / Reindex','FTS projection/chunks revision + ACL epoch; provenance refs; durable consumer inbox','search.indexed, memory.context_updated','New task/Page searchable and agent-readable after watermark; revoke before index update prevents snippet leakage; tombstone disappears; worker crash replay does not lose document','Projection consistency and derived memory leakage; metadata titles leak without read-time ACL','L'],
['07','Assignment and mention attention with one durable Notification','attention',['04','03'],['notification','read_state','activity'],'ListNotifications / MarkSeen / MarkDone / SubscribeActivity','recipient/event/reason unique; seen/done timestamp; cursor read_state','notification.created, activity.recorded','Assignment delivers once to assignee after restart/replay; mark done survives second device; permission-filtered payload; 100 edits coalesce without 100 pings','Notification amplification, private snippets and mixed session unread versus entity notifications','L'],
['08','Human Channel and entity Discussion on common Message store','messaging',['04','03'],['channel','discussion','message','thread'],'CreateChannel / PostMessage / EditMessage / DeleteMessage / GetTimeline','channel/member, discussion parent ref, message revisions, thread parent validation','message.created, message.edited, message.deleted','Two users exchange channel messages; same API posts Company discussion; edit/delete/replies persist and notify authorized subscribers; agent transcript stays separate','Human messages confused with agent runtime tool/thinking records; legacy team comment ID preservation','XL'],
['09','Cross-entity mention extraction, linking and recipient policy','graph',['08','07','06'],['mention','entity_link'],'CreateMention / ResolveMention / RemoveOccurrence','mention source revision + occurrence key unique; targets canonical refs','mention.created, mention.deleted','Company and teammate mention opens authorized target; teammate receives one notification; edited occurrence removes backlink; text mention grants no implicit access','Offset drift and undesired auto-share; mention of company must not ping entire team','L'],
['10','Two-user collaborative document inside existing ROX Pages','pages',['05','03','06','09'],['page','collaborative_document','crdt_update','snapshot'],'CreatePage(contentKind) / OpenSync / PushUpdate / Materialize','page discriminated content kind; durable CRDT WAL/snapshot; policy lease; update receipts','document.content_materialized, document.shared','A+B edit one Page concurrently; presence/cursor; offline reload/reconnect converges; durable ack survives crash; revoked updates refused; HTML pages still work','Editor binding is substantial; Loro adapter needs schema/undo compatibility; no direct Macro licensed copy','XL'],
['11','Chat → RoxTask with backlink, assignment and Project membership','tasks',['08','09','07','04'],['task','message','project_link'],'CreateTaskFromMessage / AssignTask / GetSourceContext','RoxTask description/source refs; legacy PersonalTask mapping; one canonical task id','task.created, task.assigned, entity.linked','Create from message twice with same key yields one task; source backlink visible; assignee notified; Project lists task; agent retrieves authorized conversation','PersonalTask global namespace and workflow TaskSpec confusion','L'],
['12','Project as context container with typed domain memberships','projects',['11','02'],['project','entity_link','project_member'],'LinkToProject / ProjectOverview / AddMember','migrate TaskProject aliases; project membership relation role/visibility; cwd/assets preserved','project.member_added, project.entity_linked','Project shows Page/task/channel/meeting/file/agent context; private mail linked remains private; task project migration no title-based merge','Inheritance must not silently share private linked entities; duplicate project stores','L'],
['13','Task status, priority, assignee and date command completeness','tasks',['11'],['task','principal'],'UpdateTask expectedRevision / QueryTasks filters','status transitions, priority, start/due timezone, creator/assignee refs, checklist revision','task.updated, task.completed','Concurrent assignee/status updates conflict deterministically; filters list/board agree; dates survive timezone/restart; done notification dedup','Existing string enums/date semantics differ from imported document properties','M'],
['14','Recurring task completion and reminder scheduler','tasks',['13','07'],['task','recurrence','reminder'],'CompleteOccurrence / SnoozeReminder / ListOccurrences','series RRULE/timezone; occurrence key unique; job leases; recurrence exceptions','task.occurrence_created, reminder.due','Completing recurring task creates exactly next occurrence; DST and missed execution replay tested; completed task does not duplicate after retry','Existing recurrence data migration and schedule timezone ambiguity','L'],
['15','Document anchors, history and collaborative undo','pages',['10','08'],['document_revision','comment_anchor','message'],'CreateAnchoredComment / ReadRevision / UndoLocal / RestoreAsNewRevision','stable CRDT position anchors; immutable snapshot metadata; revision evidence','document.revision_created, message.created','Comment remains on intended content after concurrent insert; deleted selection becomes orphan anchor; A undo does not erase B edit; history permissions checked','Index offsets are invalid remote anchors; restore may overwrite concurrent data','XL'],
['16','Notes bridge and portable files as one Page/Document graph','notes',['02','06','10'],['note','page','file_alias'],'ImportNote / SaveNote expectedRevision / ExportMarkdown','stable note UUID path alias; revision CAS; content-kind adapter; preserve local Markdown files','document.content_materialized','Rename Note preserves backlinks; stale save rejected; authorized Note searchable/linkable; Markdown export/import round-trip content and mention refs','Existing frontend not passing expectedRevision; filesystem paths are mutable identity','L'],
['17','Preserve JMAP Mail and expose provider-neutral domain','mail',['04','03','06'],['mail_account','mail_thread','mail_message','mail_label'],'GetMailThread / QueryInbox / SendMail adapter port; retain JMAP bridge','provider account aliases; mail entity metadata and immutable message body; token references separate','mail.message_received, mail.message_sent','Existing Stalwart inbox/detail/draft/send still work; threads canonical/searchable; other user cannot read account; actual send uses provider receipt','Existing loopback sender restrictions must remain capability-based; API connection not mailbox authority','L'],
['18','Mail sync cursor, webhook dedup and full refresh recovery','mail',['17','05'],['provider_cursor','mail_message','sync_job'],'SyncMail / HandleProviderChange / ResumeBackfill','account cursor transaction after durable ingest; inbox dedup; tombstone; reset/backfill leases','mail.sync_advanced, provider.sync_failed','Duplicate/out-of-order webhook imports message once; expired cursor rebuilds without loss; disconnect reconnect resumes; deletion replay does not resurrect','Gmail history/JMAP state/IMAP UIDVALIDITY have different semantics','XL'],
['19','Compose, reply, forward and draft attachment upload','mail',['17','18'],['mail_draft','mail_attachment','file'],'SaveDraft / Reply / Forward / UploadAttachment / SendDraft','versioned draft recipients/body; object upload finalize; provider send idempotency receipt','mail.draft_updated, mail.message_sent','Crash while send queued retries without duplicate recipient delivery; reply references/thread correct; attachments integrity; failed upload draft recoverable','SMTP ambiguous timeout cannot safely retry without provider-specific reconcile','L'],
['20','Gmail and Microsoft mail adapters behind capability contract','mail',['18','19'],['provider_connection','mail_account'],'ConnectOAuth / RefreshToken / ListDelta / Send / ManageLabel','encrypted token ref + scopes; separate account/remote binding; retry/backoff cursor','provider.connection_changed, mail.sync_advanced','Sandbox Gmail and Microsoft read/send/change label verify remote read-back; insufficient OAuth scope typed error; multi-account no cross-account merge','Vendor delta/send guarantees differ; OAuth test accounts required at execution','XL'],
['21','IMAP/SMTP adapter and scheduled-send durable jobs','mail',['18','19'],['mail_account','scheduled_send'],'ConnectIMAP / SendSMTP / ScheduleSend / CancelScheduledSend','UIDVALIDITY+UID keys, durable schedule lease, provider receipt, SMTP ambiguity state','mail.send_scheduled, mail.message_sent','UID reset reimports stable aliases without duplicates; scheduled send/cancel race executes at most one intended send; ambiguous SMTP result requires reconcile','Exactly-once external SMTP delivery cannot be asserted solely via job dedup','XL'],
['22','New inbound sender creates Contact/Company with provenance','crm',['17','18','02'],['contact','company','contact_source','interaction'],'IngestExternalParticipant / GetCompanyInteractions','normalized email/domain uniqueness workspace/team scoped; generic domains; source provenance; interaction event key','crm.contact_created, crm.company_created, crm.interaction_recorded','New external inbound email creates Contact and non-generic Company once; repeat updates last interaction; gmail.com produces contact without fake company; Company opens authorized email','Macro creates new companies on SENT, inbound behavior is enhancement; ingestion consent versus Email Sync visibility','XL'],
['23','Dossier person/company migration and reversible identity merge','crm',['22'],['contact','company','entity_alias'],'ImportDossier / SuggestMerge / MergeEntities / UndoMerge','dossier card UUID aliases; field provenance; merge journal; duplicate quarantine','crm.record_merged, entity.alias_registered','Dossier notes/promises/agent brief retained in Company view; same display name not merged; undo restores relationships; contact login identity unchanged','Renderer text touches are not reliable entity links','L'],
['24','CRM board/list stages, owner, revenue and scoped admin controls','crm',['22','03'],['company','crm_stage','property_definition'],'UpdatePipeline / SetOwner / SetRevenue / QueryCRM grouped filters','stage IDs/rank/revision; amount+currency; owner principal; allowed admin actions','crm.company_updated, crm.stage_changed','Board drag/list filter use same query; concurrent move revision conflict; revenue currency precise; nonadmin cannot edit pipeline; owner mention resolves','Arbitrary property JSON and pipeline enum drift','L'],
['25','CRM Company/Contact shared discussions and mention notifications','crm',['24','08','09','07'],['discussion','message','company','contact'],'GetCompanyDiscussion / PostMessage(parent=company/contact)','reuse common discussion/message tables; legacy imported IDs aliases; no CRM comment table','message.created, mention.created','Teammate mention in Company discussion notifies once; text indexed; agent Company context includes authorized discussion; deleting message tombstones result','Macro legacy adapter may not pass mention payload; permission inheritance must be validated','M'],
['26','CRM visibility, hidden records and email-derived context controls','crm',['22','25'],['company','contact','crm_visibility'],'HideRecord / SetEmailContextVisibility / QueryCompanyContext','hidden flags per user/team; source ingestion policy separate from presentation; audit','crm.visibility_changed','Hidden Company excludes normal lists, not destructive delete; disabled email context hides bodies from team/agents; opted-out account stops target ingestion as defined','Macro email_sync is read visibility, not stopping writes; choose explicit target consent contract','L'],
['27','Google Calendar sync replaces unavailable production adapter','calendar',['04','03','02'],['calendar_account','calendar','calendar_event'],'ConnectCalendar / ListDelta / HandleWatch / GetEvent','provider aliases; sync token/watch renewal; recurrence master+exceptions; event revision','calendar.event_created, calendar.event_updated','Real sandbox event appears in existing ROX meeting/calendar context; token expiry full sync; duplicate watch dedup; disconnected provider remains unavailable','Factory currently always unavailable; credential flag must not be treated live','XL'],
['28','Create event, attendees, move and resize with provider read-back','calendar',['27','06','09'],['calendar_event','calendar_attendee'],'CreateEvent / UpdateEvent / RSVP / MoveEvent / ResizeEvent','attendee response; conditional etag command; provider pending receipt; timezone and duration constraints','calendar.event_updated, calendar.attendee_responded','Create+attendees+drag+resize changes provider state verified; stale etag surfaces conflict; event searchable/mentionable; DST/all-day correctness','Provider optimistic UI must not report success before receipt/read-back','L'],
['29','Calendar recurrence exceptions, multi-calendar and availability','calendar',['28'],['calendar_event','availability','working_hours'],'ChangeOccurrence / ChangeSeries / FreeBusy / GetAvailability','RRULE/exdate/override occurrence keys; working hours timezone; authorized calendars','calendar.series_updated','Change one occurrence does not alter series; move across calendar semantics explicit; free/busy hides titles; working-hours DST; multical overlap','Macro working hours/availability not proven parity: target extension','XL'],
['30','Calendar-linked Meetings and contacts/projects context','calls',['28','12','22'],['call','calendar_event','entity_link'],'PlanMeeting / LinkEventCall / GetMeetingContext','existing call kind + planned subtype; occurrence→Call relation; no second Meeting store','call.planned, entity.linked','Meeting opens calendar participants/project/company refs; recurrence generates distinct actual calls; existing Meeting IDs remain canonical call aliases','MEETING_KIND call compatibility; avoid duplicate planned vs actual identity','L'],
['31','Launch LiveKit call from authorized human Channel','calls',['08','03','04'],['call','call_participant'],'StartCall / MintRoomToken / EndCall / GetCall','call room binding unique; participant principal; server auth token short-lived','call.started, call.ended','Three users join one channel call audio/video; nonmember denied; shared call ID; end call archives metadata even without transcript; local recording mode regression','Rooms currently disabled; LiveKit self-host needs TURN/network ops','XL'],
['32','Guest access, screen sharing and participant lifecycle','calls',['31'],['guest_grant','call_participant'],'InviteGuest / RevokeGuest / Join / Leave / UpdateMedia','guest token hashed expiry/revocation; participant join history; not separate login users','call.participant_joined, call.participant_left','Guest link joins permitted room only; expiry/revoke disconnect; screen-share stop cleans tracks; device reconnect single participant identity','Browser media permissions/OS capture plus guest ACL leakage','L'],
['33','Consent-based recording and preview with durable egress receipts','calls',['31','32'],['recording','file','media_job'],'StartRecording / StopRecording / HandleEgressWebhook / GetPreview','consent version; egress unique; object finalize checksum; bounded ffmpeg job; retention','call.recording_ready, recording.preview_ready','Recording after consent stores playable media; duplicate webhook one record; killed preview worker retries; partial object unavailable; signed URL expires','LiveKit egress object format/CDN auth; ffmpeg sandbox/codecs/license','XL'],
['34','Transcript diarization, summary evidence and search archive','calls',['33','06'],['transcript_segment','summary','call'],'Transcribe / CorrectSpeaker / GenerateSummary / SearchCall','segment seq/revision; speaker mapping; provenance/summary source revision; job dedup','call.transcript_ready, call.summary_ready','Ended call lists participants/duration/recording/transcript/summary; searchable spans seek recording; failed STT retry no duplicate; empty transcript call still discoverable by title','Macro Deepgram live pipeline differs from local whisper; summary hallucination/provenance','XL'],
['35','Retain local Meetings recording/import/finalize and recovery','calls',['30','04'],['call','recording','transcript'],'FinalizeLocalMeeting / ImportMedia / ResumeCapture','map LocalMeetingStore IDs to call aliases; preserve journals/Whisper evidence; shared upload optional','call.recording_ready, call.transcript_ready','Offline local recording+ffmpeg/Whisper+summary still works after migration; restart finalization resumes; no media upload without cloud-send consent','Replacing local pipeline accidentally removes existing usable capability','L'],
['36','Agent/MCP domain actions use same ACL and command receipts','agents',['04','06','09'],['agent_session','tool_action','entity_context'],'read/search/create/update/delete/link/comment/mention/share registered per kind','tool action audit; principal delegation grant + budget; context snapshot refs','agent.action_applied, agent.action_denied','Agent creates task from authorized message; third user resource denied despite allow-all; share/send/destroy preview policy; wrong revision stale rejected','Raw filesystem/store tool paths bypass shared authority; agent prompt injection via content','XL'],
['37','Automations consume canonical events with dedup and budgets','automation',['07','36'],['automation','automation_run'],'RegisterTrigger / ExecuteRun / CancelRun / DryRun','trigger predicate schema; event/run unique; bounded causation depth; budget/consent','automation.run_started, automation.run_finished','Email→task workflow runs once after duplicate event; own writes do not loop; revoked source halts; queued external send obeys approval/budget','Notification/agent runaway loops and unbounded cross-surface graph context','L'],
['38','Company account workspace aggregates every linked surface','crm',['12','25','28','34','36'],['company','contact','mail_thread','task','call','page'],'GetEntityContext(company, filters, depth, budget)','typed link indexes; source revisions; principal+epoch cache; pagination','entity.context_changed','Company shows contacts/emails/tasks/meetings/calls/documents/discussion and agent account answer with citations; unauthorized private mail absent incl title/count','N×N adapters and whole-graph traversal; derived context leaks','L'],
['39','Files/attachments complete upload, ACL, preview and retention','files',['02','03','04','06'],['file','attachment','upload_job'],'StartUpload / FinalizeUpload / Attach / SignedDownload / DeleteFile','object checksum/size/mime; quarantine; attachment ref; entity policy and retention','file.uploaded, file.quarantined, file.deleted','Task/chat/Page attachments open same file identity; bad MIME/oversize fails; signed URL revoke short expiry; delete retained asset references handled','Blob object ACL differs from parent and cross-surface grants; malware/parser risks','XL'],
['40','Favorites, recents and deep links across canonical kinds','graph',['02','03','06'],['favorite','recent','entity_alias'],'SetFavorite / Reorder / GetRecents / ResolveDeepLink','user+entity unique; sort rank; viewed history private; aliases retained','favorite.changed, entity.opened','Favorite Company/event/task/call opens existing surface after rename/restart; revoked entity does not expose title; old Macro/ROX links resolve mapped aliases','Favorites reorder races; stale identifiers should not resurrect private cache','M'],
['41','Integrated E2E scenarios, seeded failures and disaster restore','commands',['10','15','16','21','26','29','34','35','37','38','39','40'],['all registered kinds'],'Run conformance / RestoreSnapshot / ReplayOutbox','test fixtures isolated; backups/migration receipts; watermarks verified after restore','audit.validation_recorded','All seven required scenarios pass actual ROX UI and provider sandbox; deliberate ACL bypass/drop-event/broken CRDT detected; restore replays with no duplicates','Passing static docs/fixtures must never be reported as runtime parity','XL'],
['42','Spreadsheet headless domain and React Page representation','pages',['10','15'],['page','spreadsheet_document'],'CreateSpreadsheet / EditCell / ImportWorkbook / ExportWorkbook','typed spreadsheet CRDT schema+formula validation; limits; cell anchor refs','document.content_materialized','Two users edit different cells; formulas recompute consistently; permission denies writes; reload/export round-trip; formula invalid errors explicit','Macro spreadsheet package scope/gating; no blind second framework transplant','XL'],
['43','Canvas representation with safe revisioned whole-file edits','pages',['10','39'],['page','canvas_document'],'SaveCanvas expectedRevision / LinkCanvasNode / ExportCanvas','canvas JSON schema; optimistic revision; node stable IDs; attachments','document.content_materialized','Concurrent canvas save detects conflict instead of silent overwrite; node entity links searchable; existing Pages route; no unsupported CRDT promise','Macro canvas simpleSave is whole-file; spatial model not assumed collaborative','L'],
['44','PDF, code, image and video contextual viewers','files',['39','15'],['file','document','comment_anchor'],'OpenFileViewer / AnnotatePDF / SaveCodeRevision / SeekVideo','viewer prefs private; text extraction; immutable binary versions; comments anchored','file.text_extracted, document.revision_created','PDF annotation share/read authorization; code edit version conflict; video seek; attachment source preserved; unknown format safe download','Parser sandbox/preview XSS and binary conversion failures','XL'],
['45','Coding agent PR review and reusable Skill surfaces','agents',['36','12'],['agent_session','skill','foreign_entity'],'BindPullRequest / ReviewChanges / ActivateSkill','external GitHub account/PR aliases; agent change refs; immutable diff evidence','agent.change_proposed, review.recorded','Project opens authorized PR diff and source agent session; review approval applies exact revision; Skills remain existing ROX destination','Commercial provider terms, side effect approvals and stale branch data','L'],
['46','Mobile/desktop reconnect and capability-specific UX contract','commands',['41'],['device_session','capability'],'GetDeviceCapabilities / ResumeSync / OpenDeepLink','device cursors + credentials revoke; no shared secret in renderer','device.session_changed','Desktop and narrow web client show same entity refs; offline/revoke UX no false success; reduced motion/key focus; media unavailable clearly','Electron APIs absent on mobile/web; transport session mismatch','L'],
['47','Self-host deployment, telemetry and retention runbook','commands',['31','33','39','04'],['service_config','retention_job'],'Health/Ready / Metrics / RetentionSweep / BackupRestore','DB/object store/job leases; encrypted provider refs; signed asset host','retention.completed, provider.sync_failed','Isolated self-host stack runs one full Page+call+mail scenario; outages show backlog; restore and retention revoke index/assets; private text absent logs','TURN, object egress, indexing and token secrets operational burden','XL'],
['48','Exact artifact SBOM and code-origin release gate','commands',[],['license_component'],'ProduceSBOM / AuditFileOrigin / ValidateReleaseNotices','release component manifest only; no user DB mutation','audit.license_reviewed','Lock-pinned workspace/sync/media/Electron SBOM; root/web conflicts marked; copied file denied absent scoped decision; notices and exact build flags reviewed','AGPL/web all-rights-reserved scope; optional models/codecs/commercial plugins','L'],
['49','Editor binding spike: Tiptap/Loro versus React Lexical/Loro','pages',['02','03'],['collaborative_document'],'ProbeEditorRoundTrip / ProbeSelectiveUndo / ProbeCursor','isolated versioned editor/CRDT schema fixtures only; no production migration','audit.editor_binding_verified','Both candidates run same rich-text/list/entity-node + concurrent/offline/undo/anchor fixtures; pick passing lower migration cost; failed Tiptap binding falls back to React Lexical document subtype','Loro binding existing Tiptap not demonstrated; adding Yjs and Loro together creates dual document authority','L'],
['50','Agent transcript provenance and safe mixed-audience sharing','agents',['36','03'],['agent_session','artifact_provenance'],'GetSessionShareDecision / RevalidateContext / RedactDerivedArtifact','source-ref/revision/ACL taint per prompt/tool/result/summary artifact; safe audience intersection','agent.artifact_policy_changed','Agent reads private email then session share to teammate denied/redacted; revoke invalidates retrieval and exported summary; existing authorized owner transcript retained privately','Persisted raw session/tool text outlives search/memory revoke; impossible un-read promise','XL'],
['51','Single-writer mode guard and sync revocation fence','commands',['03','04','05'],['workspace_authority','policy_fence'],'ResolveWriterMode / FenceDocument / ConfirmRevokeApplied','workspace authority epoch; leased sync shard epoch; revoked grants fail append; projection routing','permission.revoke_applied, workspace.writer_mode_changed','Direct legacy Notes/Page/Task/Project/IPC/tool writes rejected for shared IDs; partitioned sync shard rejects after bounded lease; successful revoke response waits fenced durable append/broadcast boundary','Adding new gateway alone leaves legacy bypass; DB and CRDT storage not atomic','XL'],
];
// Dependency amendments from source/independent review: prerequisites before their consumers.
for(const row of seeds) {
 if(row[0]==='10') row[3].push('49','51');
 if(row[0]==='36') row[3].push('51');
 if(row[0]==='38') row[3].push('50');
 if(row[0]==='41') row[3].push('50','51');
}
const extraFiles={
 '01':['packages/server-core/src/handlers/rpc/projects.ts','packages/shared/src/projects/storage.ts','apps/electron/src/renderer/hooks/useProjects.ts','packages/server-core/src/transport/server.ts'],
 '04':['packages/server-core/src/handlers/rpc/projects.ts','packages/shared/src/projects/storage.ts'],
 '05':['packages/core/src/tasks/personal/cache.ts','packages/core/src/tasks/personal/store.ts','apps/electron/src/renderer/lib/personal-tasks-sync.ts'],
 '08':['packages/shared/src/team/sync.ts','apps/electron/src/renderer/pages/ChatPage.tsx','packages/messaging-gateway/src/index.ts'],
 '10':['packages/ui/src/components/markdown/TiptapMarkdownEditor.tsx','apps/electron/src/renderer/components/pages/PageFrame.tsx','apps/electron/src/renderer/hooks/usePages.ts'],
 '11':['packages/server-core/src/tasks/personal-persist.ts','apps/electron/src/renderer/pages/tasks/atoms.ts','packages/core/src/tasks/personal/rpc.ts'],
 '12':['packages/core/src/tasks/personal/types.ts','packages/core/src/rox2/surface-context.ts','apps/electron/src/renderer/components/app-shell/ProjectsHomeInMain.tsx'],
 '16':['apps/electron/src/renderer/pages/NotesPage.tsx','packages/core/src/rox2/notes-repository.ts'],
 '17':['apps/electron/src/main/mail/local-ipc.ts','apps/electron/src/main/mail/mail-model.ts','apps/electron/src/shared/mail-local.ts'],
 '19':['apps/electron/src/renderer/pages/inbox/mail/MailPanels.tsx','apps/electron/src/main/mail/mail-model.ts'],
 '30':['apps/electron/src/main/meetings/local-model.ts','packages/server-core/src/meetings/journal.ts'],
 '33':['packages/server-core/src/meetings/finalize.ts','packages/server-core/src/meetings/sharing.ts'],
 '34':['packages/core/src/meetings/model.ts','packages/server-core/src/meetings/finalize.ts','apps/electron/src/main/meetings/local-asr.ts'],
 '35':['apps/electron/src/main/meetings/local-store.ts','apps/electron/src/main/meetings/local-asr.ts','apps/electron/src/main/meetings/local-ipc.ts','apps/electron/src/renderer/lib/meetings/recorder.ts','apps/electron/src/renderer/pages/meetings/local-meetings-model.ts'],
 '36':['packages/session-tools-core/src/tool-defs.ts','packages/server-core/src/handlers/rpc/sessions.ts'],
 '46':['apps/ios/CraftAgentKit/Sources/CraftAgentKit/Client/RPCClient.swift','apps/ios/CraftAgentKit/Sources/CraftAgentKit/Protocol/ProtocolVersionPolicy.swift','packages/server-core/src/transport/capabilities.ts','packages/server-core/src/transport/client.ts','packages/server-core/src/transport/server.ts'],
 '49':['packages/ui/src/components/markdown/TiptapMarkdownEditor.tsx','apps/electron/src/renderer/pages/NotesPage.tsx'],
 '50':['packages/shared/src/sessions/storage.ts','packages/server-core/src/handlers/rpc/sessions.ts','packages/core/src/rox2/surface-context.ts'],
 '51':['packages/server-core/src/handlers/rpc/notes.ts','packages/server-core/src/handlers/rpc/pages.ts','packages/server-core/src/handlers/rpc/personal-tasks.ts','packages/server-core/src/handlers/rpc/projects.ts','packages/server-core/src/handlers/rpc/command-gateway.ts','packages/shared/src/agent/session-tool-defs.ts','apps/electron/src/main/meetings/local-ipc.ts'],
};
const fullChecklist=['UI','routing','entity model','persistence','commands','queries','realtime where needed','permissions','sharing','search','mentions','notifications','activity','agent access','API/MCP where applicable','observability','tests','documentation','failure states','loading states','empty states','offline/reconnect where applicable'];
const packages=seeds.map(([n,title,domain,dep,entities,api,db,events,accept,risk,complexity])=>{
 const id=`WP-${n}`;
 const affectedFiles=[...new Set([...domains[domain],...(extraFiles[n]??[])])];
 for(const path of affectedFiles) if(!existsSync(join(root,path))) throw new Error(`${id}: missing existing ${path}`);
 const actionSlug=title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
 return {id,title,goal:accept,why:`Закрыть проверяемый сценарий ${title}; source behavior и ROX границы в docs/macro-integration, baseline fixed`,status:'planned',ownerRole:`${domain}-implementation`,dependencies:dep.map(d=>`WP-${d}`),affectedRepositories:['rox-one/rox-one'],sourceReferenceRepositories:['macro-inc/macro'],baseline:snapshots,affectedFiles,newFiles:[`packages/shared/src/workspace-domain/${domain}/${actionSlug}.ts`,`apps/workspace-service/src/modules/${domain}/${actionSlug}.ts`,`tests/macro-integration/${id.toLowerCase()}.test.ts`],domainEntities:entities,apiChanges:api,dbChanges:db,events:events.split(', '),permissions:{authority:'authenticated server actor + workspace/resource policy; local standalone explicit mode',specific:domain==='mail'?'Account owner/delegated inbox; links never grant email-body access':domain==='calls'?'Call/channel grant + guest expiry + recording consent':domain==='crm'?'Team/member policy + email source consent + admin pipeline roles':'Resource read/write/action grants; deny forged actor/workspace; recheck linked refs',executionPolicy:'agent allow-all does not override resource ACL; outbound side effects obey explicit execution grants'},ui:{existingSurface:domain,newBehavior:title,states:['loading','empty','permission_denied','offline_queued','retryable_error','applied_verified']},realtime:{durability:'domain events from transaction outbox; lossy presence separate',specific:domain==='pages'?'CRDT where content-kind supports it; WAL ack/reconnect/anchors':domain==='calls'?'media tracks+webhooks; call state via durable events':domain==='calendar'||domain==='mail'?'provider cursor/watch changes and verified read-back':'revisioned invalidation + replay cursor'},tests:[{kind:'integration',assertion:accept},{kind:'negative-control',assertion:`Seed broken ${domain} boundary: unauthorized actor or dropped/duplicated event must fail ${id} acceptance`},{kind:'persistence-recovery',assertion:`Restart between persisted command and reply while running ${title}; state/receipt/canonical ID remain consistent`}],acceptanceCriteria:accept.split('; ').map(s=>s.trim()),risks:[risk],estimatedComplexity:complexity,estimateMeaning:'relative engineering scope; M=bounded adapter, L=multi-layer slice, XL=new runtime/provider/domain; no calendar commitment',observability:{required:['commandId','causationId','correlationId','aggregateRevision','policyEpoch','projectionWatermark','retry/DLQ counters'],privacy:'no raw email/body/transcript/tokens in logs'},documentation:[`docs/macro-integration/21-implementation-plan.md#${id.toLowerCase()}`,`docs/macro-integration/22-test-plan.md`],featureCompleteness:fullChecklist,licensePolicy:n==='48'?'LICENSE_REVIEW_REQUIRED':'BEHAVIOR_REIMPLEMENTATION; upstream DEPENDENCY_ONLY after exact license audit',verificationGate:'No complete status until real changed surface and relevant failure/reload path observed; fixture is not live receipt'};
});
writeFileSync(join(dest,'work-packages.json'),JSON.stringify({schemaVersion:1,architectureRevision:2,baseline:snapshots,scope:'implementation-ready plan, not implemented features',workPackages:packages},null,2)+'\n');
const edges=packages.flatMap(w=>w.dependencies.map(d=>({from:d,to:w.id,reason:`${w.id} uses accepted interface/behavior delivered by ${d}`})));
const done=new Set(),order=[]; while(order.length<packages.length){const ready=packages.filter(w=>!done.has(w.id)&&w.dependencies.every(d=>done.has(d)));if(!ready.length)throw new Error('cycle');for(const w of ready){done.add(w.id);order.push(w.id);}}
writeFileSync(join(dest,'dependency-dag.json'),JSON.stringify({schemaVersion:1,architectureRevision:2,nodes:packages.map(w=>({id:w.id,title:w.title,owner:w.ownerRole,inputs:w.dependencies,artifact:w.newFiles,verification:w.acceptanceCriteria,status:'planned'})),edges,topologicalOrder:order,criticalPath:['WP-01','WP-02','WP-03','WP-04','WP-05','WP-08','WP-09','WP-10','WP-11','WP-12','WP-38','WP-41'],note:'criticalPath lists integration chain/frontier; duration-based longest path not estimated'},null,2)+'\n');
let md='# Implementation plan: 48 independently verifiable work packages\n\nВсе пакеты **PROPOSED / planned**, а не внедренные функции. Источник полных API/DB/event/ACL/UI/realtime/test полей — `plans/macro-integration/work-packages.json`. Baseline и authority boundaries — 19 Revision 2.\n\n';
md+='## Scheduling и gates\n\nWP-48 запускается сразу независимо: юридическая проверка не блокирует самостоятельное воспроизведение поведения, но literal copy запрещён без ее результата. WP-01–04 реализуют работающий private shared Project/Task, а не один абстрактный backend. Работу поверхностей вести по dependency DAG; overlapping contract/RPC files имеют одного integration owner. Стоимости M/L/XL относительные; часов и capacity команды в запросе нет.\n\n';
for(const w of packages) md+=`## ${w.id}\n\n**${w.title}** (${w.estimatedComplexity}); dependencies: ${w.dependencies.join(', ')||'нет'}.\n\nЦель и acceptance: ${w.goal}.\n\nИзменить: ${w.affectedFiles.map(f=>'`'+f+'`').join(', ')}. Новые implementation/test paths указаны в JSON, являются proposed.\n\nAPI: ${w.apiChanges}. DB: ${w.dbChanges}. Events: ${w.events.join(', ')}.\n\nРиск: ${w.risks.join('; ')}. Проверка: интеграционный пользовательский сценарий + seeded negative control + restart/reload receipts. Общий conformance contract из 22 дополняет конкретные assertions, не заменяет их.\n\n`;
writeFileSync(join(root,'docs/macro-integration/21-implementation-plan.md'),md);
console.log(JSON.stringify({workPackages:packages.length,edges:edges.length,topologicalOrder:order.length}));
