import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
const root=process.argv[2]??process.cwd(),out=join(root,'plans/macro-integration');
const doc=JSON.parse(readFileSync(join(out,'work-packages.json'),'utf8'));
const evidence=readdirSync(out).filter(f=>/^evidence-.*\.json$/.test(f)).flatMap(f=>JSON.parse(readFileSync(join(out,f),'utf8')));
// Typed primary command per package. Additional queries/actions in apiChanges must use the same envelope.
const ops={
 '01':['project.createShared',{name:'string',workspaceName:'string',visibility:'private|members'},['project','workspace','workspace_member','principal','auth_subject_alias'],'forge actor in payload'],
 '02':['entity.link',{from:'ref',to:'ref',relationKind:'string',sourceKey:'string'},['entity','entity_alias','entity_link'],'drop account namespace and merge remote IDs'],
 '03':['permission.revoke',{resource:'ref',subjectPrincipalId:'string',actions:'string[]'},['permission_grant','policy_epoch'],'honor cached client grants after revoke'],
 '04':['project.update',{project:'ref',name:'string?'},['command_receipt','domain_event','outbox','consumer_inbox'],'ACK before transaction commit'],
 '05':['command.replay',{commands:'object[]',cursor:'string?'},['client_projection','local_outbox','projection_cursor'],'mark rejected offline draft synced'],
 '06':['search.reindex',{entities:'ref[]',minimumRevision:'string?'},['search_document','search_chunk','memory_provenance','projection_watermark'],'apply stale update after tombstone'],
 '07':['notification.markDone',{notificationId:'string',done:'boolean'},['notification','notification_read_state','activity'],'insert processed inbox before effect'],
 '08':['message.post',{parent:'ref',body:'string',threadRoot:'ref?',attachments:'ref[]'},['channel','channel_member','discussion','message','thread','message_revision','message_reaction','message_read_state'],'reply into thread from another parent'],
 '09':['mention.create',{source:'ref',target:'ref',sourceRevision:'string',occurrenceKey:'string'},['mention','entity_link'],'grant access when mention created'],
 '10':['page.createDocument',{title:'string',contentKind:'collaborative_document',editorSchemaVersion:'integer'},['page','collaborative_document','crdt_wal','crdt_snapshot','sync_lease'],'ACK before durable CRDT write'],
 '11':['task.createFromMessage',{sourceMessage:'ref',project:'ref?',title:'string',assigneePrincipalIds:'string[]'},['task','task_personal_placement','entity_link'],'create duplicate on retried message intent'],
 '12':['project.linkEntity',{project:'ref',entity:'ref',role:'primary|context|attachment',inheritPermissions:'boolean'},['project_member','entity_link','project_alias'],'share private mail via project link'],
 '13':['task.update',{task:'ref',status:'string?',priority:'none|low|medium|high?',due:'object?',start:'object?',assigneePrincipalIds:'string[]?'},['task','task_checklist','task_property'],'lose other user assignee change'],
 '14':['task.completeOccurrence',{task:'ref',occurrenceKey:'string',completedAt:'string'},['task_recurrence','task_occurrence','reminder','scheduler_job'],'generate two next occurrences'],
 '15':['document.comment',{document:'ref',anchor:'object',body:'string',sourceRevision:'string'},['document_revision','comment_anchor','message'],'anchor uses DOM offsets after remote insert'],
 '16':['note.import',{legacyPath:'string',content:'string',sourceHash:'string'},['entity_alias','note_location','document_revision'],'rename changes canonical identity'],
 '17':['mail.openThread',{account:'ref',thread:'ref'},['mail_account','mail_thread','mail_message','mail_label','provider_connection'],'read another account body via thread alias'],
 '18':['mail.ingestDelta',{account:'ref',providerCursor:'string',changeBatchKey:'string'},['provider_sync_cursor','provider_event_inbox','mail_sync_job'],'advance cursor before durable ingest'],
 '19':['mail.sendDraft',{account:'ref',draft:'ref',draftRevision:'string'},['mail_draft','mail_attachment','provider_intent','provider_receipt'],'retry ambiguous send without reconcile'],
 '20':['provider.connectMail',{provider:'gmail|microsoft',accountHint:'string',scopes:'string[]'},['provider_connection','credential_ref','provider_sync_cursor'],'accept insufficient OAuth scope as connected'],
 '21':['mail.scheduleSend',{account:'ref',draft:'ref',sendAt:'string',timeZone:'string'},['scheduled_send','provider_intent','provider_receipt'],'race cancel and send creates duplicate delivery'],
 '22':['crm.ingestParticipant',{sourceMessage:'ref',externalEmail:'string',direction:'inbound|outbound',interactionAt:'string'},['contact','company','company_domain','contact_source','crm_interaction'],'group gmail.com into one company'],
 '23':['crm.mergeRecords',{survivor:'ref',candidate:'ref',expectedSourceRevisions:'object'},['entity_alias','crm_merge_journal','crm_import_batch'],'merge same display name without explicit candidate'],
 '24':['crm.updateCompany',{company:'ref',stageId:'string?',ownerPrincipalId:'string?',revenue:'object?'},['crm_stage','crm_stage_policy','company_property'],'nonadmin changes stage definitions'],
 '25':['message.postCompanyDiscussion',{company:'ref',body:'string',mentions:'ref[]',threadRoot:'ref?'},['discussion','message','mention'],'drop mention payload in legacy adapter'],
 '26':['crm.setVisibility',{record:'ref',hidden:'boolean',emailContextVisibility:'private|team'},['crm_visibility','crm_source_policy'],'hidden record leaks email body to agent'],
 '27':['calendar.sync',{account:'ref',syncToken:'string?',watchEventKey:'string?'},['calendar_account','calendar','calendar_event','calendar_source','calendar_occurrence','calendar_sync_job'],'expired token resurrects deleted event'],
 '28':['calendar.updateEvent',{event:'ref',start:'object?',end:'object?',attendees:'object[]?',providerEtag:'string'},['calendar_attendee','calendar_provider_intent','provider_receipt'],'optimistic move reports success on provider 412'],
 '29':['calendar.updateOccurrence',{event:'ref',occurrenceKey:'string',scope:'one|series|following',patch:'object'},['calendar_override','calendar_working_hours','calendar_availability'],'edit occurrence mutates entire series'],
 '30':['call.planFromEvent',{event:'ref',title:'string',project:'ref?',company:'ref?'},['call','call_calendar_link','entity_alias'],'duplicate Meeting and Call for same migrated ID'],
 '31':['call.start',{channel:'ref',mediaMode:'audio|video'},['call','call_room_binding','call_participant'],'room token uses client-supplied participant identity'],
 '32':['call.inviteGuest',{call:'ref',expiresAt:'string',allowedActions:'string[]'},['call_guest_grant','call_participant_event'],'expired guest token still connects'],
 '33':['call.startRecording',{call:'ref',consentVersion:'string',consentingPrincipalIds:'string[]'},['recording','media_job','object_asset','provider_receipt'],'recording ready before object finalize'],
 '34':['call.transcribe',{call:'ref',recording:'ref',sourceChecksum:'string',pipelineVersion:'string'},['transcript_segment','speaker_binding','call_summary','media_job'],'archive rollup deletes cited raw segments'],
 '35':['call.importLocal',{legacyMeetingId:'string',workspaceId:'string',uploadMedia:'boolean'},['entity_alias','local_artifact_mapping','media_job'],'local finalization uploads without cloud consent'],
 '36':['agent.invokeDomain',{session:'ref',toolName:'string',arguments:'object',contextRefs:'ref[]'},['agent_action_receipt','delegation_grant','artifact_provenance'],'allow-all bypasses resource ACL'],
 '37':['automation.run',{automation:'ref',triggerEventId:'string',dryRun:'boolean'},['automation','automation_run','automation_effect_intent'],'self-generated event loops unbounded'],
 '38':['entity.getContext',{entity:'ref',depth:'integer',limit:'integer',purpose:'string'},['entity_context_cache','context_provenance'],'return hidden node totals/cached titles'],
 '39':['file.finalize',{file:'ref',uploadId:'string',checksum:'string',sizeBytes:'integer'},['file','object_asset','attachment','upload_job'],'attach private foreign upload by ID'],
 '40':['favorite.set',{entity:'ref',favorite:'boolean',rank:'number?'},['favorite','recent_entity'],'revoked title persists in favorite cache'],
 '41':['audit.validateScenario',{scenarioId:'string',fixtureId:'string',seed:'integer'},['test_receipt'],'remove declared dependency and run against hidden fixture implementation'],
 '42':['spreadsheet.editCell',{document:'ref',sheetId:'string',cellId:'string',value:'object'},['collaborative_document','document_revision'],'formula recompute differs after reconnect'],
 '43':['canvas.save',{document:'ref',canvas:'object',schemaVersion:'integer'},['canvas_document','document_revision'],'whole-file save silently overwrites concurrent nodes'],
 '44':['file.annotate',{file:'ref',anchor:'object',body:'string'},['comment_anchor','document_revision','file_preview_job'],'preview reads unauthorized blob metadata'],
 '45':['agent.bindPullRequest',{session:'ref',project:'ref',providerAccount:'string',pullRequestId:'string'},['foreign_entity_alias','agent_change_evidence','review_receipt'],'approve stale change revision'],
 '46':['device.resume',{deviceId:'string',cursor:'string',protocolVersion:'integer',capabilities:'string[]'},['device_session','projection_cursor'],'Electron-only action advertised on iOS'],
 '47':['operations.restore',{backupId:'string',isolatedWorkspaceId:'string',verifyChecksums:'boolean'},['backup_receipt','retention_job'],'restore replay duplicates provider effects'],
 '48':['audit.releaseLicense',{artifactDigest:'string',sbomDigest:'string',decisionManifest:'object'},[], 'allow copied unreviewed web source'],
 '49':['audit.editorBinding',{candidate:'tiptap_loro|react_lexical_loro',fixtureSet:'string',seed:'integer'},[], 'drop remote insertion on local undo'],
 '50':['session.shareAuthorized',{session:'ref',audiencePrincipalIds:'string[]',redactionMode:'deny|redact'},['artifact_provenance','artifact_audience','session_share_receipt'],'strip source provenance before viewer upload'],
 '51':['authority.applyFence',{resource:'ref',targetPolicyEpoch:'integer',authorityEpoch:'integer'},['workspace_authority','policy_fence','sync_delivery_lease'],'legacy direct write changes shared entity'],
};
const ref={$ref:'#/$defs/Rox2EntityRef'};
function fieldSpec(type){let optional=type.endsWith('?');if(optional)type=type.slice(0,-1);let value;if(type.endsWith('[]'))value={type:'array',maxItems:1000,items:fieldSpec(type.slice(0,-2)).value};else if(type==='ref')value=ref;else if(type.includes('|'))value={type:'string',enum:type.split('|')};else if(type==='object')value={type:'object',description:'Domain DTO, constrained below where applicable; reject unknown mutation fields'};else if(!['string','number','integer','boolean'].includes(type))value={type:'string',const:type};else value={type,...(type==='string'?{minLength:1,maxLength:10000}:{}),...(type==='integer'?{minimum:0}:{})};return{optional,value};}
for(const wp of doc.workPackages){
 const n=wp.id.slice(3), [operation,fields,tables,mutation]=ops[n];
 const props={},required=[];for(const[key,type]of Object.entries(fields)){const x=fieldSpec(type);props[key]=x.value;if(!x.optional)required.push(key);}
 const schema={type:'object',additionalProperties:false,properties:props,required,$defs:{Rox2EntityRef:{type:'object',additionalProperties:false,properties:{workspaceId:{type:'string',minLength:1},entityId:{type:'string',pattern:'^[a-z][a-z0-9-]*:.+$'},revisionId:{type:'string'},accountNamespace:{type:'string'}},required:['workspaceId','entityId']}}};
 wp.inputs=wp.dependencies.map(id=>({producer:id,requiredArtifacts:['accepted typed interface','applied migration receipt','scenario verification receipt']}));
 wp.operations=[{name:operation,kind:/getContext|openThread/.test(operation)?'query':/audit\.|operations\./.test(operation)?'operator':'command',transport:{http:`POST /v1/workspaces/{workspaceId}/commands/${operation}`,nativeRpc:`domain.${operation}`,authentication:'transport-derived principal; body actor field rejected',envelope:'RoxCommand v2 idempotencyKey/expectedRevision/workspaceId; query pagination+authorized cursor'},requestSchema:schema,response:{status:'Rox2CanonicalResult',entity:'Rox2EntityRef',receipt:'commandId/requestHash/observedRevision/verifiedAt; provider result remains queued/unknown until reconciled',queryData:'authorized typed domain DTO; no hidden total/title'},errors:['UNAUTHENTICATED','FORBIDDEN','WORKSPACE_MISMATCH','INVALID_PAYLOAD','REVISION_CONFLICT','IDEMPOTENCY_CONFLICT','PROVIDER_UNAVAILABLE','UNKNOWN_EXTERNAL_EFFECT','SCHEMA_VERSION_UNSUPPORTED','REVOKE_FENCE_PENDING'],expectedRevisionPolicy:'required for mutable existing aggregate; create idempotency required; CRDT update uses document causal frontier + policy fence instead of scalar content CAS'}];
 wp.migrations=tables.length?[{artifact:`apps/workspace-service/migrations/${n}-domain-contract.sql`,status:'proposed migration identifier; actual filename generated by selected migrator, no fabricated timestamp',tables,commonColumns:{workspace_id:'uuid NOT NULL except globally auth principals',entity_id:'text canonical kind:id for entity-owned tables',schema_version:'integer NOT NULL CHECK >0',revision:'bigint NOT NULL CHECK >=0',created_at:'timestamptz',updated_at:'timestamptz',deleted_at:'timestamptz NULL for retained entities'},constraints:[{name:'entity_identity',definition:'Entity-owned row composite FK (workspace_id,entity_id) -> entity; principal/receipt/job tables own typed key'},{name:'idempotency',definition:'UNIQUE(workspace_id, actor_principal_id, idempotency_key) for command_receipt; request_hash checked on conflict'},{name:'alias_identity',definition:'UNIQUE(workspace_id,provider,account,remote_type,remote_id) in alias tables'},{name:'event_delivery',definition:'UNIQUE(consumer_id,event_id); claimed lease separate processed; aggregate_revision+policy/tombstone fence enforced'}],domainConstraints:wp.dbChanges,indexes:['workspace + entity primary lookup','domain filter + stable cursor sort','event pending lease/status/time','backlink target/type indexes when links introduced'],forward:'additive migration; backfill with aliases/provenance; reject ambiguous IDs into quarantine',rollback:'before cutover restore writer route and snapshot; after accepted shared writes forward repair or verified reverse replay; never delete recent writes'},]:[];
 wp.newArtifacts=[{path:`packages/shared/src/workspace-domain/${wp.ownerRole.replace('-implementation','')}/contracts.ts`,interface:`${operation} request/result schema + domain ports, no service I/O in core`},{path:`apps/workspace-service/src/modules/${wp.ownerRole.replace('-implementation','')}/commands.ts`,interface:'typed command/query implementation; same policy/idempotency/revision gateway'},{path:`apps/workspace-service/src/modules/${wp.ownerRole.replace('-implementation','')}/repository.ts`,interface:'domain tables/transaction/outbox/inbox; only composition root creates provider adapters'},{path:`tests/macro-integration/${wp.id.toLowerCase()}.test.ts`,interface:'scenario + meaningful seeded failure control + recovery'}];
 wp.newFiles=[...new Set([...wp.newArtifacts.map(a=>a.path),...wp.migrations.map(m=>m.artifact)])];
 wp.entryPoints=wp.affectedFiles.map(path=>({path,symbols:[...new Set(evidence.filter(e=>e.repository==='rox-one/rox-one'&&e.path===path).map(e=>e.symbol))],change:`Route ${operation} through authenticated workspace authority or preserve explicit standalone adapter; use request schema and migration invariant above`,sourceEvidenceIds:evidence.filter(e=>e.repository==='rox-one/rox-one'&&e.path===path).map(e=>e.id)}));
 wp.verification={runner:'bun test tests/macro-integration/'+wp.id.toLowerCase()+'.test.ts; relevant existing package tests; browser/Electron scenario harness for UI',fixtures:{workspace:'W1 shared',actors:['A owner','B member','C outsider'],privateMarker:`PRIVATE_${wp.id}`,providerSandbox:/mail|calendar|calls/.test(wp.ownerRole)?'explicit isolated provider/media sandbox, no hosted production data':'not needed unless operation outbound',seed:20260930+Number(n)},expectedObservations:wp.acceptanceCriteria,negativeControl:{mutation,expected:'specific assertion fails; baseline infrastructure error distinguished from caught mutation',holdout:'independent evaluator injects second failure variant'},artifacts:['UI screenshot/ARIA assertion where changed','typed API read-back','canonical entity ID+revision','DB row/unique key count','command/provider receipts','event/projection watermark','failure trace with reproduction seed'],completeness:wp.featureCompleteness};
 wp.why=`${operation} creates a verified user-visible domain behavior through existing ROX; mechanism gap and preserved capabilities described in its evidence-backed surface audit.`;
}
// Explicit bootstrap and full integration semantics; initial native Project is a minimal secured vertical slice.
const one=doc.workPackages.find(w=>w.id==='WP-01');one.bootstrapContract={owns:['transport-authenticated Actor','workspace membership','minimal Project identity row','owner-only policy enforced server-side','Project create transaction+idempotent receipt','native Project RPC/list/detail'],laterGeneralization:['WP-02 registry kinds/aliases/relations','WP-03 full grant roles/inheritance/revoke','WP-04 generic outbox/inbox/revision command framework'],acceptanceScope:'minimal private Project feature; not complete Project cross-surface parity'};
const twelve=doc.workPackages.find(w=>w.id==='WP-12');twelve.acceptanceCriteria=['Project lists registered Task/Channel and authorized existing Page refs; unsupported not silently rendered live','cwd/assets/details retained; private mail link does not share content','TaskProject→ProjectConfig mapping never merges by name'];twelve.fullConformanceDependency='WP-38 integrates Calendar/Call/File/Pages after individual packages';
doc.workPackages.find(w=>w.id==='WP-38').dependencies.push('WP-39','WP-16');
doc.workPackages.find(w=>w.id==='WP-47').dependencies.push('WP-10','WP-18','WP-34');
doc.workPackages.find(w=>w.id==='WP-50').affectedFiles.push('packages/server-core/src/sessions/share-capability.ts','packages/core/src/types/message.ts');
doc.workPackages.find(w=>w.id==='WP-06').affectedFiles.push('packages/server-core/src/services/search.ts','packages/server-core/src/memory/fts-index.ts','packages/server-core/src/knowledge/vault-index.ts');
doc.workPackages.find(w=>w.id==='WP-07').affectedFiles.push('apps/electron/src/renderer/hooks/useInboxItems.ts','apps/electron/src/renderer/components/team/TeamInboxSection.tsx','apps/electron/src/renderer/pages/InboxPage.tsx');
for(const w of doc.workPackages){w.dependencies=[...new Set(w.dependencies)];for(const f of w.affectedFiles)if(!existsSync(join(root,f)))throw new Error(`missing ${w.id} ${f}`);}
doc.machineContractRevision=2;doc.contractStatus='typed operation schemas and migration/interface artifacts; detailed nested domain DTO completion belongs to owned implementation slice, all PROPOSED';
writeFileSync(join(out,'work-packages.json'),JSON.stringify(doc,null,2)+'\n');
const done=new Set(),order=[];while(order.length<doc.workPackages.length){const ready=doc.workPackages.filter(w=>!done.has(w.id)&&w.dependencies.every(d=>done.has(d)));if(!ready.length)throw new Error('enriched cycle');for(const w of ready){done.add(w.id);order.push(w.id);}}
const dag={schemaVersion:1,architectureRevision:2,nodes:doc.workPackages.map(w=>({id:w.id,title:w.title,owner:w.ownerRole,inputs:w.dependencies,artifact:w.newArtifacts,verification:w.acceptanceCriteria,status:'planned'})),edges:doc.workPackages.flatMap(w=>w.dependencies.map(d=>({from:d,to:w.id,reason:`accepted prerequisite ${d}`}))),topologicalOrder:order,criticalFrontier:['WP-01','WP-02','WP-03','WP-04','WP-05','WP-51','WP-49','WP-10','WP-11','WP-12','WP-38','WP-41'],parallelBranches:['mail+CRM','calendar+planning','media+recording','Page editor binding'],note:'criticalFrontier is dependency frontier, not duration-based longest path'};
writeFileSync(join(out,'dependency-dag.json'),JSON.stringify(dag,null,2)+'\n');
let md=`# Implementation plan: ${doc.workPackages.length} work packages (Revision 2)\n\nПолный machine contract: work-packages.json включает typed operations/request JSON Schema/response/errors, migration artifacts/constraints, exact existing entryPoints/evidence, inputs/dependencies, new module interfaces, verification runner/fixtures/negative controls и feature completeness checklist. Все PROPOSED/planned; никаких claimed feature passes.\n\nWP-01 — минимальный secured Project bootstrap; WP-02/03/04 расширяют уже реализованные baseline invariants. WP-04 выполняет Project update, не Task до WP-11. WP-49 editor spike и WP-51 authority fence обязательны до collaborative Page. WP-50 agent artifact provenance обязательна до Company context sharing. WP-12 initial registered-kind overview, полная cross-surface conformance в WP-38/41.\n\nShared module paths намеренно повторяются: одна domain module authority, не модуль на каждый title. WPs с общим файлом интегрируются последовательно по DAG или одним владельцем domain area. Migration path — proposed identifier, filename создаётся migrator при реализации. M/L/XL — relative scope, не обещание срока.\n\n`;
for(const w of doc.workPackages)md+=`## ${w.id}\n\n**${w.title}** (${w.estimatedComplexity}), dependencies: ${w.dependencies.join(', ')||'нет'}.\n\nGoal: ${w.goal}.\n\nPrimary operation: \`${w.operations[0].name}\`, typed request/result/error schema в JSON. Storage: ${w.dbChanges}.\n\nExisting files: ${w.affectedFiles.map(f=>'`'+f+'`').join(', ')}. New interfaces/migrations/tests: ${w.newFiles.map(f=>'`'+f+'`').join(', ')}.\n\nAcceptance: ${w.acceptanceCriteria.join('; ')}. Negative control: ${w.verification.negativeControl.mutation}.\n\nPermissions: ${w.permissions.specific}. Events: ${w.events.join(', ')}. Risk: ${w.risks.join('; ')}.\n\n`;
writeFileSync(join(root,'docs/macro-integration/21-implementation-plan.md'),md);
console.log(JSON.stringify({enriched:doc.workPackages.length,edges:dag.edges.length}));
