import fs from 'node:fs';
import cp from 'node:child_process';
import path from 'node:path';
const root=process.cwd(), macro=process.env.MACRO_SOURCE_DIR || '/Users/t/Projects/macro-source-audit-20260930';
const current={ 'macro-inc/macro':'5678f9bd777413f66e8bddac58f13f21150d831b','rox-one/rox-one':'e780e73ae84c977cf81546b49140d318dfcd6049'};
const git=(cwd,...args)=>cp.execFileSync('git',args,{cwd,encoding:'utf8',maxBuffer:8*1024*1024}).trim();
const evidence=['rox','collab','domains','inventory'].flatMap(n=>JSON.parse(fs.readFileSync(`plans/macro-integration/evidence-${n}.json`)));
const records=evidence.map(e=>{const cwd=e.repository==='macro-inc/macro'?macro:root; const sha=current[e.repository]; const before=git(cwd,'rev-parse',`${e.sha}:${e.path}`),after=git(cwd,'rev-parse',`${sha}:${e.path}`); return {evidenceId:e.id,repository:e.repository,path:e.path,symbol:e.symbol,originalSha:e.sha,currentSha:sha,originalBlob:before,currentBlob:after,status:before===after?'identical-source':'changed-requires-review'};});
const deltas=[
 ['apps/web/src/features/channel/Channel/ChannelUnreadNotifications.tsx','ChannelUnreadNotifications','Unread navigation resolves parent IDs and viewport-relative chip position.'],
 ['apps/web/src/features/channel/Channel/unread-thread-navigation.ts','unreadThreads / unreadNotificationChip','Unread thread targeting and above/below navigation; verify mounted-message read semantics independently.'],
 ['apps/web/src/features/notifications/components/MarkMessageNotifications.tsx','MarkMessageNotifications','Marks every exact-message notification batch, retries cache regressions up to three; mount effect is not a proof of viewport dwell.'],
 ['apps/web/src/lib/service-clients/service-connection/presence-telemetry.ts','instrumentGatewaySocket / reportHeartbeatLapse / reportReopenOnReconnect','Adds connection/presence telemetry; does not replace CRDT durability or resource ACL.'],
 ['apps/web/src/lib/core/component/LexicalMarkdown/plugins/native-ios-backspace/nativeIosBackspacePlugin.ts','nativeIosBackspacePlugin','Native iOS backspace behavior gains regression tests; desktop React editor needs its own IME/mobile conformance.'],
 ['packages/lexical-core/transformers/katex.ts','E_BLOCK_EQUATION_NODE / $sharesLineWithContent','Mid-sentence double-dollar math renders inline; display math requires isolated content; include conformance cases.'],
 ['crates/notification/src/outbound/mobile/payload.rs','SnsTarget / SnsPayload / stringified_fcm_json','Android data-only FCM serialization/display-clear adapter changes are provider infrastructure, not a reason to insert Tauri into Electron.'],
 ['apps/web/src/features/reminders/reminder-navigation.ts','reminderDetailContent / reminderDetailUrl / openReminderDetail','Canonical reminder detail route and namespace claim preserve same ID across Home/standalone; source navigation lives in detail.'],
 ['apps/web/src/features/reminders/route.tsx','reminderDetailRoute / RemindersRouteView','Feature-gated authenticated native reminder list/detail; remountKey prevents A-to-B stale editor identity.'],
 ['apps/web/src/features/home/route.tsx','homeReminderRoute','Home reminder detail uses same reminder namespace claim and ID, not a second reminder entity.'],
 ['apps/web/src/components/app/split-layout/split-router/legacy-route.ts','decodeLegacyPair / splitLocationFromContent','Legacy component/reminders rejected, persisted reminder content normalizes to route-owned detail; one router authority.']
].map(([p,s,c])=>({repository:'macro-inc/macro',sha:current['macro-inc/macro'],path:p,symbol:s,claim:c,blob:git(macro,'rev-parse',`${current['macro-inc/macro']}:${p}`)}));
for(const e of deltas){const body=git(macro,'show',`${e.sha}:${e.path}`);e.lineStart=1;e.lineEnd=body.split('\n').length;e.url=`https://github.com/${e.repository}/blob/${e.sha}/${e.path}#L${e.lineStart}-L${e.lineEnd}`;}
const changedReview=records.filter(r=>r.status!=='identical-source').map(r=>({...r,reviewStatus:'REVIEWED_DELTA',result:r.evidenceId==='IN014'?'Exact-message notification batch now re-marks cache regressions max3; mounted effect is not viewport-dwell proof':r.evidenceId==='IN004'?'appSplitRoutes adds native reminderDetailRoute; target reminder must use same canonical ref and reload-safe route':'createSplitLayout now tracks navigator readiness/version via signal; route-owned opens require bound navigator; other split/history mechanism retained'}));
const report={schemaVersion:1,checkedAt:new Date().toISOString(),current,intermediateMacroSha:'44a2e9efa62b557c5b0378f6376db0a6c4c6a127',method:'git object comparison of every original evidence path, followed by explicit changed-source review; identical blobs preserve the original evidence, not runtime proof',records,changedReview,deltaEvidence:deltas,counts:{total:records.length,identical:records.filter(r=>r.status==='identical-source').length,changed:records.filter(r=>r.status!=='identical-source').length},runtime:{nativeScreenshot:'INSTALLED_UI_OBSERVED: shell/Tasks screenshot and AX Tasks/Meetings/Dossier/Pages/Inbox navigation after disk recovery; earlier failure and timeout preserved in native-ui-observation.md; binary source SHA/font/new feature behavior NOT_VERIFIED',linuxContainer:'not-run: Docker daemon unavailable',featureE2E:'planned, not implemented'}};
fs.writeFileSync('plans/macro-integration/reverification.json',JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report.counts));
