import {readFileSync,writeFileSync,readdirSync,existsSync,statSync} from 'node:fs';
import {join,resolve,dirname} from 'node:path';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';

export const approaches=new Set(['KEEP_ROX','EXTEND_ROX','PORT_DOMAIN','PORT_SERVICE','PORT_UI_PATTERN','ADAPTER','REIMPLEMENT','REPLACE_INFRA','NEW_ROX_PRIMITIVE','DROP']);
const surfaceFields=['surface','userPurpose','entryPoints','routes','mainUiComponents','childSurfaces','entities','actions','clientState','queries','commands','apis','persistence','realtime','collaboration','permissions','search','notifications','agentAccess','mcp','backgroundProcessing','infrastructure','tests','importantFiles','dependencies'];
const wpFields=['id','title','goal','why','dependencies','affectedRepositories','affectedFiles','newFiles','domainEntities','apiChanges','dbChanges','events','permissions','ui','realtime','tests','acceptanceCriteria','risks','estimatedComplexity','operations','migrations','entryPoints','inputs','verification'];
export function validateMachine(b){
 const errors=[],check=(ok,msg)=>{if(!ok)errors.push(msg);};
 const wps=b.packages.workPackages,ids=new Set(wps.map(w=>w.id)),evidenceIds=new Set(b.evidence.map(e=>e.id));
 check(wps.length>=30,'At least 30 packages required');check(ids.size===wps.length,'Duplicate package ID');check(evidenceIds.size===b.evidence.length,'Duplicate evidence ID');
 for(const w of wps){for(const f of wpFields)check(Object.hasOwn(w,f),`${w.id} missing ${f}`);check(w.status==='planned',`${w.id}: must remain planned`);check(w.acceptanceCriteria.length>0,`${w.id} empty acceptance`);check(!!w.verification.negativeControl?.mutation,`${w.id} missing negative control`);for(const d of w.dependencies)check(ids.has(d)&&d!==w.id,`${w.id} invalid dependency ${d}`);check(JSON.stringify([...w.dependencies].sort())===JSON.stringify(w.inputs.map(x=>x.producer).sort()),`${w.id} stale inputs`);check(w.entryPoints.length===w.affectedFiles.length,`${w.id} stale entrypoints`);for(const p of w.entryPoints)check(w.affectedFiles.includes(p.path),`${w.id} orphan entrypoint`);for(const op of w.operations){check(!!op.requestSchema&&!!op.responseSchema,`${w.id} missing primary schemas`);for(const[label,schema]of [['request',op.requestSchema],['response',op.responseSchema]]){const walk=(node)=>{if(!node||typeof node!=='object')return;if(node.type)check(['string','object','array','number','integer','boolean','null'].includes(node.type),`${w.id} ${label} invalid type ${node.type}`);if(node.$ref?.startsWith('#/')){let value=schema;for(const part of node.$ref.slice(2).split('/'))value=value?.[part];check(!!value,`${w.id} ${label} unresolved ${node.$ref}`);}for(const v of Object.values(node))walk(v);};walk(schema);}}}
 const order=b.dag.topologicalOrder,seen=new Set();check(order.length===wps.length&&new Set(order).size===wps.length,'DAG order coverage');for(const id of order){const w=wps.find(x=>x.id===id);check(!!w,`DAG unknown node ${id}`);if(w)for(const d of w.dependencies)check(seen.has(d),`DAG ${id} before ${d}`);seen.add(id);}
 const expected=wps.flatMap(w=>w.dependencies.map(d=>`${d}->${w.id}`)).sort(),actual=b.dag.edges.map(e=>`${e.from}->${e.to}`).sort();check(JSON.stringify(actual)===JSON.stringify(expected),'DAG edges differ from package prerequisites');check(b.dag.nodes.length===wps.length,'DAG node count');
 for(const s of b.capabilities.surfaces){for(const f of surfaceFields)check(Object.hasOwn(s,f),`${s.id} missing ${f}`);check(s.macroEvidenceIds.length>0,`${s.id} missing code evidence`);for(const id of s.macroEvidenceIds)check(evidenceIds.has(id),`${s.id} unknown evidence ${id}`);check(approaches.has(s.targetApproach),`${s.id} bad approach`);}
 for(const c of b.capabilities.capabilities){check(approaches.has(c.targetApproach),`${c.id} invalid approach`);check(b.capabilities.surfaces.some(s=>s.id===c.surfaceId),`${c.id} unknown surface`);for(const id of c.workPackages)check(ids.has(id),`${c.id} unknown package ${id}`);check(c.evidenceIds.length>0,`${c.id} missing evidence`);}
 for(const e of b.entities.entities){check(e.targetId.format.includes('Rox2EntityRef'),`Entity ${e.macroEntity} duplicate ref format`);check(e.migration.sourceKey.length>=4,`Entity ${e.macroEntity} unscoped alias`);}
 return errors;
}
export function loadBundle(root){const dir=join(root,'plans/macro-integration'),read=n=>JSON.parse(readFileSync(join(dir,n),'utf8'));return{packages:read('work-packages.json'),dag:read('dependency-dag.json'),capabilities:read('capabilities.json'),entities:read('entity-map.json'),evidence:readdirSync(dir).filter(f=>/^evidence-.*\.json$/.test(f)).flatMap(read)};}
const files=(dir)=>readdirSync(dir).flatMap(f=>statSync(join(dir,f)).isDirectory()?files(join(dir,f)):[join(dir,f)]);

async function main(){
 const root=resolve(process.argv[2]??process.cwd()),macro=resolve(process.argv[3]??'/Users/t/Projects/macro-source-audit-20260930'),modules=resolve(process.argv[4]??'/tmp/rox-product-validation-20260930/node_modules');
 const b=loadBundle(root),errors=validateMachine(b),warnings=[],checks=[],check=(ok,msg)=>{if(!ok)errors.push(msg);};
 const Ajv=(await import(pathToFileURL(join(modules,'ajv/dist/2020.js')).href)).default,addFormats=(await import(pathToFileURL(join(modules,'ajv-formats/dist/index.js')).href)).default;
 const ajv=new Ajv({strict:false,allErrors:true});addFormats(ajv);let schemas=0;
 for(const w of b.packages.workPackages)for(const op of w.operations)for(const label of ['request','response']){try{ajv.compile(op[label+'Schema']);schemas++;}catch(e){errors.push(`${w.id} ${label} JSON Schema: ${e.message}`);}}
 const snapshots=JSON.parse(readFileSync(join(root,'plans/macro-integration/source-snapshots.json'),'utf8')).snapshots;
 const repoMap={'macro-inc/macro':{dir:macro,sha:snapshots.macro.sha},'rox-one/rox-one':{dir:root,sha:snapshots.rox.sha}},cache=new Map();
 const recheck=JSON.parse(readFileSync(join(root,'plans/macro-integration/reverification.json'),'utf8'));
 const allowed={'macro-inc/macro':new Set([snapshots.macro.sha,recheck.current['macro-inc/macro'],recheck.intermediateMacroSha]),'rox-one/rox-one':new Set([snapshots.rox.sha,recheck.current['rox-one/rox-one']])};
 const v4=JSON.parse(readFileSync(join(root,'plans/macro-integration/source-reverification-v4.json'),'utf8'));for(const [repository,sha]of Object.entries(v4.current))allowed[repository].add(sha);
 const source=(repo,sha,path)=>{const key=`${repo}@${sha}:${path}`;if(cache.has(key))return cache.get(key);const map=repoMap[repo];if(!map||!allowed[repo].has(sha))throw Error(`unreviewed baseline ${key}`);const t=execFileSync('git',['show',`${sha}:${path}`],{cwd:map.dir,encoding:'utf8',stdio:['ignore','pipe','pipe'],maxBuffer:16*1024*1024});cache.set(key,t);return t;};
 for(const e of b.evidence){try{const t=source(e.repository,e.sha,e.path),lines=t.split('\n');check(e.lineStart>=1&&e.lineEnd>=e.lineStart&&e.lineEnd<=lines.length,`Evidence ${e.id} invalid range`);check(!!e.symbol&&!!e.claim,`Evidence ${e.id} incomplete`);}catch(err){errors.push(`Evidence ${e.id}: ${err.message}`);}}
 for(const w of b.packages.workPackages)for(const path of w.affectedFiles){try{source('rox-one/rox-one',snapshots.rox.sha,path);}catch(err){errors.push(`${w.id} existing file: ${err.message}`);}}
 const docsDir=join(root,'docs/macro-integration'),docs=readdirSync(docsDir).filter(f=>f.endsWith('.md')),required=['executive-summary','macro-product-map','macro-architecture','rox-current-state','surface-parity-matrix','domain-model','entity-graph','collaboration-runtime','chat-and-messaging','tasks-projects','crm','mail','calendar','calls-meetings','permissions-sharing','search-notifications','agent-integration','infrastructure','licensing','target-architecture','migration-dag','implementation-plan','test-plan','open-questions'];
 for(let i=0;i<required.length;i++)check(docs.includes(`${String(i).padStart(2,'0')}-${required[i]}.md`),`Missing doc ${i}`);
 const {JSDOM}=await import(pathToFileURL(join(modules,'jsdom/lib/api.js')).href);const dom=new JSDOM('<!doctype html><html><body></body></html>');globalThis.window=dom.window;globalThis.document=dom.window.document;
 const mermaid=(await import(pathToFileURL(join(modules,'mermaid/dist/mermaid.core.mjs')).href)).default;mermaid.initialize({startOnLoad:false,securityLevel:'strict'});let diagrams=0,links=0;
 const allDocs=[...files(docsDir),...files(join(root,'cloud/macro-integration')),...(existsSync(join(root,'docs/rox-suite'))?files(join(root,'docs/rox-suite')):[])].filter(f=>f.endsWith('.md'));
 for(const path of allDocs){const name=path.slice(root.length+1),text=readFileSync(path,'utf8');for(const m of text.matchAll(/```mermaid\s*\n([\s\S]*?)```/g)){try{await mermaid.parse(m[1]);diagrams++;}catch(err){errors.push(`${name} Mermaid ${diagrams+1}: ${err.message}`);}}
  for(const m of text.matchAll(/\]\(([^\n)]+)\)/g)){const target=m[1].replace(/^<|>$/g,'');if(target.startsWith('https://github.com/')){const hit=/^https:\/\/github.com\/(macro-inc\/macro|rox-one\/rox-one)\/blob\/([a-f0-9]{40})\/([^#]+)(?:#L(\d+)(?:-L(\d+))?)?$/.exec(target);if(hit)try{const t=source(hit[1],hit[2],decodeURIComponent(hit[3]));if(hit[4])check(Number(hit[4])<=t.split('\n').length,`${name} source line out of range ${target}`);links++;}catch(e){errors.push(`${name} broken source link ${target}: ${e.message}`);}continue;}if(/^(https?:|#|mailto:)/.test(target))continue;const local=target.split('#')[0].replace(/:\d+$/,'');if(local)check(existsSync(resolve(dirname(path),local)),`${name} broken local link ${target}`);}
 }
 check(diagrams>=10,'Required diagram families absent');
 // Seeded controls demonstrate validator rejects corrupt review artifacts, not just valid JSON syntax.
 const mutations=[['missing prerequisite',x=>x.packages.workPackages[1].dependencies.push('WP-999')],['duplicate ID',x=>x.packages.workPackages[1].id=x.packages.workPackages[0].id],['invalid approach',x=>x.capabilities.capabilities[0].targetApproach='COPY_BLINDLY'],['unresolved schema ref',x=>x.packages.workPackages[0].operations[0].requestSchema.properties.name={$ref:'#/$defs/Missing'}],['stale DAG',x=>x.dag.edges.pop()],['evidence missing',x=>x.capabilities.surfaces[0].macroEvidenceIds=[]],['invalid schema primitive',x=>x.packages.workPackages[0].operations[0].requestSchema.properties.name={type:'collaborative_document'}]];
 const controls=[];for(const[name,mutate]of mutations){const seeded=structuredClone(b);mutate(seeded);const caught=validateMachine(seeded);controls.push({name,rejected:caught.length>0,reasons:caught.slice(0,3)});check(caught.length>0,`Negative control survived: ${name}`);}
 const artifacts=[...allDocs,...files(join(root,'plans/macro-integration')).filter(f=>f.endsWith('.json')&&!f.includes('validation-report')),...files(join(root,'scripts/macro-integration'))].map(full=>({path:full.slice(root.length+1),sha256:createHash('sha256').update(readFileSync(full)).digest('hex')}));
 const report={schemaVersion:1,status:errors.length?'FAILED':'PASSED',checkedAt:new Date().toISOString(),baseline:snapshots,reverifiedSourceHeads:recheck.current,scope:'Architecture and product/cloud artifacts only; source readback, schema/DAG/evidence/link/Mermaid checks. Product runtime E2Es are future gates and were not executed.',counts:{requiredDocs:required.length,totalDocs:allDocs.length,surfaces:b.capabilities.surfaces.length,capabilities:b.capabilities.capabilities.length,entities:b.entities.entities.length,workPackages:b.packages.workPackages.length,dependencyEdges:b.dag.edges.length,evidenceRecords:b.evidence.length,compiledJsonSchemas:schemas,parsedMermaidDiagrams:diagrams,checkedCommitSourceLinks:links,negativeControls:controls.length},negativeControls:controls,errors,warnings,artifacts,tooling:{bun:Bun.version,mermaid:'11.12.0',ajv:'8.17.1',ajvFormats:'3.0.1'}};
 writeFileSync(join(root,'plans/macro-integration/validation-report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,counts:report.counts,errors:errors.slice(0,30)}));if(errors.length)process.exitCode=1;
}
if(import.meta.main)await main();
