// W1-03 (#1500) — Goals & OKR `goals.*`, `okr.*`, goal check-ins (TECH-SPEC §4.7, §4.9, §20, PLAN §1.3).
import { CATALOGUE_FLAGS as F, moduleCatalogue } from './entry.ts'

export const GOALS_COMMANDS = moduleCatalogue('goals', F.goals, [
  ['goals.create', 'by-target'],
  ['goals.update_name', 'by-target'],
  ['goals.update_description', 'by-target'],
  ['goals.update_parent_goal', 'by-target'],
  ['goals.update_start_date', 'by-target'],
  ['goals.update_due_date', 'by-target'],
  ['goals.update_champion', 'by-target'],
  ['goals.update_reviewer', 'by-target'],
  ['goals.update_space', 'by-target'],
  ['goals.update_access_levels', 'by-target', 'share'],
  ['goals.create_target', 'by-target'],
  ['goals.update_target', 'by-target'],
  ['goals.update_target_value', 'by-target'],
  ['goals.update_target_index', 'by-target'],
  ['goals.delete_target', 'by-target', 'destroy'],
  ['goals.create_check', 'by-target'],
  ['goals.update_check', 'by-target'],
  ['goals.toggle_check', 'by-target'],
  ['goals.update_check_index', 'by-target'],
  ['goals.delete_check', 'by-target', 'destroy'],
  ['goals.close', 'by-target'],
  ['goals.reopen', 'by-target'],
  ['goals.delete', 'by-target', 'destroy'],
  ['goals.align', 'by-target'],
  ['goals.unalign', 'by-target'],
  ['goals.set_target_status_override', 'by-target'],
  ['okr.create_cycle', 'by-target'],
  ['okr.publish_cycle', 'by-target', 'publish'],
  ['okr.publish_objectives', 'by-target', 'publish'],
  ['okr.import_from_cycle', 'by-target'],
  // §4.9 check-ins (package CHK)
  ['goals.create_check_in', 'by-target', 'write', F.goalsCheckins],
  ['goals.update_check_in', 'by-target', 'write', F.goalsCheckins],
  ['goals.delete_check_in', 'by-target', 'destroy', F.goalsCheckins],
  ['goals.acknowledge_check_in', 'by-target', 'write', F.goalsCheckins],
  ['goals.record_check_in_summary', 'by-target', 'write', F.goalsCheckins],
  // §20 X-17 / X-18
  ['checkins.draft_from_activity', 'by-target', 'read', F.xfn],
  ['goals.link_work', 'by-target', 'write', F.xfn],
  ['goals.unlink_work', 'by-target', 'write', F.xfn],
])
