// W1-03 (#1500) — Messenger `im.*` (TECH-SPEC §4.1, §12, §15.1, §20 X-22).
import { CATALOGUE_FLAGS as F, moduleCatalogue } from './entry.ts'

export const IM_COMMANDS = moduleCatalogue('im', F.messenger, [
  ['im.create_chat', 'workspace'],
  ['im.update_chat', 'workspace'],
  ['im.disband_chat', 'workspace', 'destroy'],
  ['im.get_or_create_p2p', 'workspace'],
  ['im.add_members', 'workspace', 'share'],
  ['im.remove_members', 'workspace', 'share'],
  ['im.update_member_state', 'workspace'],
  ['im.update_policy', 'workspace'],
  ['im.send_message', 'workspace'],
  ['im.edit_message', 'workspace'],
  ['im.recall_message', 'workspace', 'destroy'],
  ['im.forward_messages', 'workspace'],
  ['im.pin', 'workspace'],
  ['im.unpin', 'workspace'],
  ['im.set_top_notice', 'workspace'],
  ['im.update_announcement', 'workspace'],
  ['im.create_tab', 'workspace'],
  ['im.update_tab', 'workspace'],
  ['im.delete_tab', 'workspace', 'destroy'],
  ['im.mark_read', 'workspace'],
  ['im.mark_unread', 'workspace'],
  ['im.create_label', 'workspace'],
  ['im.label_chats', 'workspace'],
  ['im.create_space_chat', 'workspace'],
  ['im.create_entity_chat', 'workspace'],
  ['im.join_chat', 'workspace'],
  ['im.leave_chat', 'workspace'],
  ['im.set_visibility', 'workspace', 'share'],
  ['im.share_entity', 'workspace', 'write', F.xfn],
])
