/**
 * W1-15 (#1512) — `@rox/shared/xfn`: the zod schemas of the cross-functional
 * capability contracts X-13…X-26 (TECH-SPEC §20), plus the query / UI entry
 * points that never reach the command bus.
 */
export {
  GOAL_WORK_RELATIONS,
  FORM_ON_SUBMIT_KINDS,
  XFN_QUERY_SCHEMAS,
  XFN_SCHEMAS,
  agendaTodaySchema,
  agentsPanelOpenSchema,
  calendarCreateEventFromEmailSchema,
  calendarCreateTimeBlockSchema,
  checkinsDraftFromActivitySchema,
  commandsBatchSchema,
  decisionsCreateSchema,
  docsCreateFromEmailSchema,
  entitiesDropSchema,
  entitiesPinSchema,
  entitiesReorderPinsSchema,
  formsConfigureOnSubmitSchema,
  goalsLinkWorkSchema,
  goalsUnlinkWorkSchema,
  imShareEntitySchema,
  meetingsPublishOutcomesSchema,
  peopleGetOverviewSchema,
  remindersCancelSchema,
  remindersCreateSchema,
  tablesInsertRowSchema,
  tasksCreateFromEmailSchema,
  vcStartMeetingSchema,
  xfnEntityKindSchema,
  type AgendaTodayPayload,
  type AgentsPanelOpenPayload,
  type CalendarCreateEventFromEmailPayload,
  type CalendarCreateTimeBlockPayload,
  type CheckinsDraftFromActivityPayload,
  type CommandsBatchPayload,
  type DecisionsCreatePayload,
  type DocsCreateFromEmailPayload,
  type EntitiesDropPayload,
  type EntitiesPinPayload,
  type EntitiesReorderPinsPayload,
  type FormOnSubmitKind,
  type FormsConfigureOnSubmitPayload,
  type GoalWorkRelation,
  type GoalsLinkWorkPayload,
  type GoalsUnlinkWorkPayload,
  type ImShareEntityPayload,
  type MeetingsPublishOutcomesPayload,
  type PeopleGetOverviewPayload,
  type RemindersCancelPayload,
  type RemindersCreatePayload,
  type TablesInsertRowPayload,
  type TasksCreateFromEmailPayload,
  type VcStartMeetingPayload,
  type XfnCommandName,
  type XfnQueryName,
} from './schemas'

/** Query and UI entry points, in the order TECH-SPEC §20 lists them. */
export const XFN_QUERIES = ['people.get_overview', 'agenda.today', 'agents.panel_open'] as const