/**
 * W1-06 (#1503) — One ordered scenario that executes every catalogue command
 * through its reference handler. Earlier steps create what later steps need;
 * ids are uuid-shaped so the same scenario runs on the Postgres backend.
 */

import { deterministicId } from '../reference/engine'

export const U = (name: string) => deterministicId('reference-scenario', name)
export const ACTOR_ID = U('actor')
export const BOB = U('bob')
export const WORKSPACE_ID = U('workspace')

export interface ScenarioStep {
  type: string
  target?: { kind: string; id: string }
  payload: Record<string, unknown>
  /** Run as another principal (e.g. deciding someone else's access request). */
  actor?: string
}

const t = (kind: string, name: string) => ({ kind, id: U(name) })
const at = (hour: number) => `2026-10-09T${String(hour).padStart(2, '0')}:00:00.000Z`
const statuses = [{ key: 'todo', label: 'tasks.status.todo', color: 'gray', closed: false, kind: 'open' }, { key: 'done', label: 'tasks.status.done', color: 'green', closed: true, kind: 'done' }]
const sha = 'ab'.repeat(32)
const doc = t('note', 'doc')
const s = (type: string, target: ScenarioStep['target'], payload: Record<string, unknown> = {}, actor?: string): ScenarioStep => ({ type, ...(target ? { target } : {}), payload, ...(actor ? { actor } : {}) })

export const REFERENCE_SCENARIO: readonly ScenarioStep[] = [
  // identity / spaces
  s('workspaces.create', undefined, { id: U('ws2'), name: 'Acme' }),
  s('spaces.create', undefined, { id: U('space'), name: 'Eng', memberIds: [BOB] }),
  s('spaces.update', t('space', 'space'), { purpose: 'Engineering' }),
  s('spaces.update_tools', t('space', 'space'), { tools: { kpis: true } }),
  s('spaces.add_members', t('space', 'space'), { members: [{ principalId: U('carol'), role: 'editor' }] }),
  s('spaces.update_members_permissions', t('space', 'space'), { members: [{ principalId: U('carol'), role: 'viewer' }] }),
  s('spaces.update_general_access', t('space', 'space'), { defaultAccess: 'company_view' }),
  s('spaces.update_task_statuses', t('space', 'space'), { statuses }),
  s('spaces.remove_member', t('space', 'space'), { principalId: U('carol') }),
  // The space owner cannot leave (ownership changes only through a transfer): the round trip runs as BOB (editor).
  s('spaces.leave', t('space', 'space'), {}, BOB),
  s('spaces.join', t('space', 'space'), {}, BOB),
  // messenger
  s('im.create_chat', undefined, { id: U('chat'), kind: 'group', name: 'general', visibility: 'public', members: [BOB] }),
  s('im.update_chat', t('channel', 'chat'), { name: 'general-2' }),
  s('im.add_members', t('channel', 'chat'), { memberIds: [U('carol')] }),
  s('im.remove_members', t('channel', 'chat'), { memberIds: [U('carol')] }),
  s('im.update_member_state', t('channel', 'chat'), { muted: true }),
  s('im.update_policy', t('channel', 'chat'), { postingPolicy: 'all' }),
  s('im.send_message', t('channel', 'chat'), { chatRef: t('channel', 'chat'), body: { doc: 'hello' }, mentions: [], messageId: U('msg') }),
  s('im.edit_message', t('channel', 'chat'), { messageId: U('msg'), content: { doc: 'hello!' } }),
  s('im.pin', t('channel', 'chat'), { messageId: U('msg') }),
  s('im.unpin', t('channel', 'chat'), { messageId: U('msg') }),
  s('im.set_top_notice', t('channel', 'chat'), { content: 'Release on Friday' }),
  s('im.update_announcement', t('channel', 'chat'), { docId: null }),
  s('im.create_tab', t('channel', 'chat'), { id: U('tab'), kind: 'link', title: 'Docs' }),
  s('im.update_tab', t('channel', 'chat'), { tabId: U('tab'), title: 'Docs 2' }),
  s('im.delete_tab', t('channel', 'chat'), { tabId: U('tab') }),
  s('im.mark_read', t('channel', 'chat'), { seq: 1 }),
  s('im.mark_unread', t('channel', 'chat'), { seq: 1 }),
  s('im.create_label', t('channel', 'chat'), { id: U('label'), name: 'todo' }),
  s('im.label_chats', t('channel', 'chat'), { labelId: U('label'), messageIds: [U('msg')] }),
  s('im.forward_messages', t('channel', 'chat'), { messageIds: [U('msg')], toChatId: U('chat') }),
  s('im.share_entity', t('channel', 'chat'), { entity: t('task', 'task'), comment: 'look' }),
  s('im.get_or_create_p2p', undefined, { peerId: BOB }),
  s('im.create_space_chat', undefined, { spaceId: U('space'), name: 'eng-chat' }),
  s('im.create_entity_chat', undefined, { subject: t('project', 'project') }),
  s('im.set_visibility', t('channel', 'chat'), { visibility: 'public' }),
  s('im.leave_chat', t('channel', 'chat')),
  s('im.join_chat', t('channel', 'chat')),
  s('im.recall_message', t('channel', 'chat'), { messageId: U('msg') }),
  // presence (W1-14, §11.1: heartbeat / object presence — ephemeral, no domain event)
  s('presence.heartbeat', undefined, { status: 'online', device: 'desktop' }),
  // docs, drive, wiki
  s('docs.create_document', undefined, { id: U('doc'), title: 'Spec', markdown: '# Spec' }),
  s('presence.join', undefined, { ref: doc }),
  s('presence.leave', undefined, { ref: doc }),
  s('docs.update_title', doc, { title: 'Spec v2' }),
  s('docs.publish_post', doc),
  s('docs.schedule_post', doc, { scheduledAt: at(9) }),
  s('docs.restore_version', doc, { version: 1 }),
  s('docs.set_public_sharing', doc, { enabled: true }),
  s('docs.update_permissions', doc, { entries: [{ principalId: BOB, role: 'editor' }] }),
  s('docs.suggest_changes', doc, { id: U('sugg'), kind: 'insert', anchor: { from: 1 }, summary: 'add intro' }),
  s('docs.decide_suggestion', doc, { suggestionId: U('sugg'), decision: 'accepted' }),
  s('docs.sync_suggestions', doc, { suggestionIds: [U('sugg')] }),
  s('docs.record_view', doc),
  s('docs.move_back_to_private', doc),
  s('docs.move_note_to_shared', { kind: 'note', id: 'Notes/plan.md' }, { id: U('shared-doc'), noteId: 'Notes/plan.md', markdown: '# Plan' }),
  s('docs.apply_patch', { kind: 'note', id: 'Notes/plan.md' }, { noteId: 'Notes/plan.md', patch: '@@ -1 +1 @@' }),
  s('docs.ensure_daily_note', undefined, { date: '2026-10-08' }),
  s('docs.append_daily_link', undefined, { date: '2026-10-08', link: t('task', 'task') }),
  s('docs.create_meeting_notes', undefined, { id: U('minutes'), eventRef: t('calendar-event', 'ev') }),
  s('docs.insert_task_block', doc, { docRef: doc, blockId: 'block-task', task: { title: 'Nested task', assignee: BOB } }),
  s('docs.insert_event_block', doc, { docRef: doc, blockId: 'block-event', event: { title: 'Kickoff', start: at(10), end: at(11) } }),
  s('docs.insert_meeting_block', doc, { docRef: doc, blockId: 'block-meeting', mode: 'now' }),
  s('docs.embed_view', doc, { docRef: doc, blockId: 'block-view', ref: { kind: 'saved-view', ref: t('base-view', 'view') } }),
  // seq 4: 1 = the original message, 2 = the forward, 3 = the shared-entity card.
  s('im.send_message', t('channel', 'chat'), { chatRef: t('channel', 'chat'), body: { doc: 'quote me' }, mentions: [], messageId: U('msg-quote') }),
  s('docs.create_from_messages', t('channel', 'chat'), { id: U('msg-doc'), chatRef: t('channel', 'chat'), seqs: [4], target: { new: { title: 'From chat' } }, format: 'quotes' }),
  s('docs.append_block', doc, { docRef: doc, markdown: 'more' }),
  s('docs.create_from_email', undefined, { id: U('mail-doc'), threadId: 'thread-1' }),
  s('drive.create_folder', undefined, { id: U('folder'), name: 'Specs' }),
  s('drive.rename_folder', t('folder', 'folder'), { name: 'Specs 2' }),
  s('drive.move_items', t('folder', 'folder'), { items: [doc], toFolderId: U('folder') }),
  s('drive.add_link', t('folder', 'folder'), { id: U('dlink'), url: 'https://example.com', title: 'Example', folderId: U('folder') }),
  s('drive.upload_file', t('folder', 'folder'), { id: U('file'), name: 'a.pdf', sizeBytes: 10, folderId: U('folder'), sha256: sha }),
  s('drive.favorite', t('file', 'file'), { item: t('file', 'file'), favorite: true }),
  s('drive.add_shortcut', t('folder', 'folder'), { item: t('file', 'file'), folderId: U('folder') }),
  s('drive.provision', undefined, { quotaBytes: 1000 }),
  s('drive.open_upload', undefined, { id: U('upload'), fileName: 'b.bin', sizeExpected: 5 }),
  s('drive.complete_upload', undefined, { uploadSessionId: U('upload'), sha256: sha }),
  s('drive.open_upload', undefined, { id: U('upload-abort'), fileName: 'c.bin', sizeExpected: 3 }),
  s('drive.abort_upload', undefined, { uploadSessionId: U('upload-abort') }),
  s('drive.import_attachment', undefined, { source: { kind: 'mail-thread', id: 'thread-1' }, attachmentId: 'att-1' }),
  s('wiki.create_space', undefined, { id: U('wiki'), name: 'Wiki' }),
  s('wiki.move_node', t('wiki-space', 'wiki'), { node: doc, parent: null, sortKey: 'a1' }),
  // tasks
  s('task_list_groups.create', undefined, { id: U('group'), name: 'Work' }),
  s('task_list_groups.update', t('task-list-group', 'group'), { collapsed: true }),
  s('task_lists.create', undefined, { id: U('list'), name: 'Sprint', groupId: U('group') }),
  s('task_lists.update', t('task-list', 'list'), { notes: 'two weeks' }),
  s('task_sections.create', t('task-list', 'list'), { id: U('section'), taskListId: U('list'), title: 'Todo' }),
  s('task_sections.update', t('task-section', 'section'), { title: 'Doing' }),
  s('task_sections.move', t('task-section', 'section'), { sortKey: 'a5' }),
  s('tasks.create', undefined, { id: U('task'), title: 'Write tests', listId: U('list') }),
  s('tasks.update', t('task', 'task'), { notes: 'details', priority: 'high' }),
  s('tasks.update_status', t('task', 'task'), { statusKey: 'in_progress' }),
  s('tasks.complete', t('task', 'task')),
  s('tasks.reopen', t('task', 'task')),
  s('tasks.cancel', t('task', 'task')),
  s('tasks.reopen', t('task', 'task')),
  s('tasks.update_assignees', t('task', 'task'), { add: [BOB] }),
  s('tasks.set_user_state', t('task', 'task'), { evening: true }),
  s('tasks.add_to_list', t('task', 'task'), { listId: U('list'), sectionId: U('section') }),
  s('tasks.remove_from_list', t('task', 'task'), { listId: U('list') }),
  s('tasks.move', t('task', 'task'), { sectionId: U('section') }),
  s('tasks.share', t('task', 'task'), { workspaceId: U('ws2') }),
  s('tasks.create', undefined, { id: U('task2'), title: 'Other' }),
  s('tasks.add_dependency', t('task', 'task'), { blocks: U('task2') }),
  s('tasks.update_reminders', t('task', 'task'), { reminderAt: at(8) }),
  s('tasks.duplicate', t('task', 'task'), { id: U('task3') }),
  s('tasks.archive', t('task', 'task3')),
  s('task_statuses.update_set', t('task-list', 'list'), { statuses }),
  s('tasks.create_from_selection', doc, { id: U('sel-task'), origin: { kind: 'doc-block', docRef: `note:${U('doc')}`, blockId: 'block-task' }, title: 'From selection' }),
  s('tasks.create_many_from_checklist', doc, { docRef: doc, blockIds: ['b2', 'b3'], shared: { title: 'From checklist' } }),
  s('tasks.create_from_message', undefined, { id: U('msg-task'), origin: { kind: 'message', chatRef: `channel:${U('chat')}`, seq: 1 }, title: 'From message' }),
  s('tasks.create_from_email', undefined, { id: U('mail-task'), threadId: 'thread-1', title: 'From email' }),
  s('reminders.create', t('task', 'task'), { id: U('rem'), remindAt: at(7) }),
  s('reminders.cancel', t('reminder', 'rem')),
  // goals & OKR
  s('okr.create_cycle', undefined, { id: U('cycle'), name: 'Q4', startsOn: '2026-10-01', endsOn: '2026-12-31' }),
  s('goals.create', undefined, { id: U('goal2'), name: 'Parent' }),
  s('goals.create', undefined, { id: U('goal'), name: 'Grow', okrCycleId: U('cycle'), championId: BOB, targets: [{ id: U('target'), name: 'MAU', fromValue: 0, toValue: 100 }], checks: [{ id: U('check'), name: 'Launch' }] }),
  s('goals.update_name', t('goal', 'goal'), { name: 'Grow fast' }),
  s('goals.update_description', t('goal', 'goal'), { description: 'Why' }),
  s('goals.update_parent_goal', t('goal', 'goal'), { parentGoalId: U('goal2') }),
  s('goals.update_start_date', t('goal', 'goal'), { startOn: '2026-10-01' }),
  s('goals.update_due_date', t('goal', 'goal'), { dueOn: '2026-12-31', duePrecision: 'quarter' }),
  s('goals.update_champion', t('goal', 'goal'), { championId: ACTOR_ID }),
  s('goals.update_reviewer', t('goal', 'goal'), { reviewerId: BOB }),
  s('goals.update_space', t('goal', 'goal'), { spaceId: U('space') }),
  s('goals.update_access_levels', t('goal', 'goal'), { companyAccess: 'view' }),
  s('goals.create_target', t('goal', 'goal'), { id: U('target2'), name: 'Revenue', fromValue: 0, toValue: 10 }),
  s('goals.update_target', t('goal', 'goal'), { targetId: U('target2'), toValue: 20 }),
  s('goals.update_target_value', t('goal', 'goal'), { targetId: U('target'), value: 5 }),
  s('goals.update_target_index', t('goal', 'goal'), { targetId: U('target'), sortKey: 'a2' }),
  s('goals.set_target_status_override', t('goal', 'goal'), { targetId: U('target'), status: 'caution' }),
  s('goals.delete_target', t('goal', 'goal'), { targetId: U('target2') }),
  s('goals.create_check', t('goal', 'goal'), { id: U('check2'), name: 'Docs' }),
  s('goals.update_check', t('goal', 'goal'), { checkId: U('check2'), name: 'Docs 2' }),
  s('goals.toggle_check', t('goal', 'goal'), { checkId: U('check'), done: true }),
  s('goals.update_check_index', t('goal', 'goal'), { checkId: U('check'), sortKey: 'a3' }),
  s('goals.delete_check', t('goal', 'goal'), { checkId: U('check2') }),
  s('goals.create_check_in', t('goal', 'goal'), { id: U('checkin'), status: 'on_track', message: 'Good', targetValues: [{ targetId: U('target'), value: 7 }], checkValues: [{ checkId: U('check'), done: true }] }),
  s('goals.update_check_in', t('check-in', 'checkin'), { message: 'Better' }),
  s('goals.acknowledge_check_in', t('check-in', 'checkin')),
  s('goals.record_check_in_summary', t('goal', 'goal'), { checkInId: U('checkin'), status: 'on_track' }),
  s('checkins.draft_from_activity', t('goal', 'goal'), { id: U('draft-checkin') }),
  s('goals.link_work', t('goal', 'goal'), { work: t('task', 'task') }),
  s('goals.unlink_work', t('goal', 'goal'), { work: t('task', 'task') }),
  s('goals.align', t('goal', 'goal'), { toGoalId: U('goal2') }),
  s('goals.unalign', t('goal', 'goal'), { toGoalId: U('goal2') }),
  s('okr.publish_cycle', t('okr-cycle', 'cycle')),
  s('okr.publish_objectives', t('okr-cycle', 'cycle'), { goalIds: [U('goal')] }),
  s('okr.import_from_cycle', t('okr-cycle', 'cycle'), { fromCycleId: U('cycle'), goalIds: [U('goal')] }),
  s('goals.close', t('goal', 'goal'), { successStatus: 'achieved' }),
  s('goals.reopen', t('goal', 'goal')),
  s('goals.delete_check_in', t('check-in', 'checkin')),
  // projects
  s('projects.create', undefined, { id: U('project'), name: 'Apollo', spaceId: U('space') }),
  s('projects.update_name', t('project', 'project'), { name: 'Apollo 2' }),
  s('projects.update_description', t('project', 'project'), { description: 'Moon' }),
  s('projects.update_parent_goal', t('project', 'project'), { parentGoalId: U('goal') }),
  s('projects.update_champion', t('project', 'project'), { championId: BOB }),
  s('projects.update_reviewer', t('project', 'project'), { reviewerId: ACTOR_ID }),
  s('projects.add_contributor', t('project', 'project'), { personId: BOB, role: 'contributor' }),
  s('projects.update_contributor', t('project', 'project'), { personId: BOB, responsibility: 'QA' }),
  s('projects.remove_contributor', t('project', 'project'), { personId: BOB }),
  s('projects.update_dates', t('project', 'project'), { deadline: '2026-12-01' }),
  s('projects.pause', t('project', 'project')),
  s('projects.resume', t('project', 'project')),
  s('projects.move', t('project', 'project'), { spaceId: null }),
  s('projects.share', t('project', 'project'), { workspaceId: U('ws2') }),
  s('projects.add_resource', t('project', 'project'), { resource: doc }),
  s('projects.remove_resource', t('project', 'project'), { resource: doc }),
  s('projects.update_task_statuses', t('project', 'project'), { statuses }),
  s('milestones.create', t('project', 'project'), { id: U('ms'), projectId: U('project'), title: 'Beta' }),
  s('milestones.update', t('milestone', 'ms'), { title: 'Beta 2' }),
  s('milestones.complete', t('milestone', 'ms')),
  s('milestones.reopen', t('milestone', 'ms')),
  s('milestones.reorder', t('project', 'project'), { order: [U('ms')] }),
  s('projects.create_check_in', t('project', 'project'), { id: U('pcheckin'), status: 'caution', message: 'Risky' }),
  s('projects.update_check_in', t('check-in', 'pcheckin'), { status: 'on_track' }),
  s('projects.acknowledge_check_in', t('check-in', 'pcheckin')),
  s('projects.delete_check_in', t('check-in', 'pcheckin')),
  s('reviews.create', undefined, { id: U('review'), subjectType: 'project', subjectId: U('project'), successStatus: 'achieved' }),
  s('reviews.acknowledge', t('review', 'review')),
  s('reviews.create_cycle_review', undefined, { id: U('creview'), okrCycleId: U('cycle') }),
  s('project_templates.create_from_project', t('project', 'project'), { id: U('tpl'), name: 'Template' }),
  s('project_templates.create_project', t('project-template', 'tpl'), { id: U('project2'), name: 'From template' }),
  s('exports.markdown', t('project', 'project')),
  s('projects.close', t('project', 'project'), { successStatus: 'missed' }),
  // KPIs
  s('kpis.create', undefined, { id: U('kpi'), spaceId: U('space'), name: 'NPS', cadence: 'monthly' }),
  s('kpis.update', t('kpi', 'kpi'), { unit: 'pts' }),
  s('kpis.log_entry', t('kpi', 'kpi'), { id: U('entry'), value: 42, period: '2026-10-01' }),
  s('kpis.edit_entry', t('kpi', 'kpi'), { entryId: U('entry'), value: 43 }),
  s('kpis.add_annotation', t('kpi', 'kpi'), { id: U('annot'), date: '2026-10-02', title: 'Launch' }),
  s('kpis.edit_annotation', t('kpi', 'kpi'), { annotationId: U('annot'), title: 'Launch!' }),
  // calendar & meetings
  s('calendar.create_calendar', undefined, { id: U('cal'), name: 'Team' }),
  s('calendar.subscribe', undefined, { calendarId: U('cal') }),
  s('calendar.create_event', t('calendar', 'cal'), { id: U('ev'), calendarRef: t('calendar', 'cal'), title: 'Sync', start: at(10), end: at(11), tz: 'UTC', attendees: [BOB] }),
  s('calendar.free_busy', undefined, { principals: [ACTOR_ID], range: { start: at(9), end: at(18) } }),
  s('calendar.update_event', t('calendar-event', 'ev'), { title: 'Sync 2' }),
  s('calendar.rsvp', t('calendar-event', 'ev'), { response: 'tentative' }),
  s('calendar.book_room', undefined, { roomId: U('room'), startAt: at(10), endAt: at(11) }),
  s('calendar.create_time_block', undefined, { id: U('block'), title: 'Focus', startAt: at(12), endAt: at(13) }),
  s('calendar.create_event_from_message', undefined, { id: U('ev2'), origin: { kind: 'message', chatRef: `channel:${U('chat')}`, seq: 1 }, title: 'From chat', start: at(14), end: at(15), attendees: 'chat' }),
  s('calendar.create_event_from_email', undefined, { id: U('ev3'), title: 'From mail', startAt: at(16), endAt: at(17), threadId: 'thread-1' }),
  s('calendar.delete_event', t('calendar-event', 'ev3')),
  s('vc.start_meeting', undefined, { id: U('call'), participants: [BOB] }),
  s('vc.join', undefined, { callId: U('call') }),
  s('vc.set_recording', undefined, { callId: U('call'), recording: true }),
  s('meetings.publish_outcomes', t('call', 'call'), { tasks: [{ title: 'Follow up' }], decisions: [{ title: 'Ship' }], toChatId: U('chat') }),
  s('vc.end', undefined, { callId: U('call') }),
  // people & contacts
  s('people.update_profile', undefined, { displayName: 'Me' }),
  s('people.set_manager', t('person', 'bob'), { managerId: U('carol') }),
  s('people.invite', undefined, { id: U('invite'), email: 'dave@example.com' }),
  s('people.add_workspace_member', undefined, { principalId: U('dave'), role: 'member' }),
  s('people.convert_to_guest', t('person', 'dave')),
  s('contacts.create_card', undefined, { id: U('card'), displayName: 'Eve' }),
  s('contacts.create_card', undefined, { id: U('card2'), displayName: 'Eve (dup)' }),
  s('contacts.update_card', t('person', 'card'), { organization: 'Acme' }),
  s('contacts.star', t('person', 'card'), { starred: true }),
  s('contacts.add_touch', t('person', 'card'), { channel: 'email' }),
  s('contacts.merge_cards', t('person', 'card'), { sourceIds: [U('card2')] }),
  // social
  s('comments.create', doc, { id: U('comment'), content: 'Nice' }),
  s('comments.create', doc, { id: U('reply'), content: 'Thanks', threadId: U('comment') }),
  s('comments.edit', t('comment', 'comment'), { content: 'Nice!' }),
  s('comments.react', t('comment', 'comment'), { emoji: '👍' }),
  s('comments.resolve', t('comment', 'comment')),
  s('comments.resolve_thread', doc, { threadId: U('comment') }),
  s('comments.reopen_thread', doc, { threadId: U('comment') }),
  s('comments.convert_to_task', t('comment', 'comment'), { id: U('ctask') }),
  s('comments.delete', t('comment', 'reply')),
  s('reactions.add', doc, { emoji: '🎉' }),
  s('reactions.remove', doc, { emoji: '🎉' }),
  s('subscriptions.subscribe', doc),
  s('subscriptions.unsubscribe', doc),
  s('subscriptions.set_notify_everyone', doc, { enabled: true }),
  // notifications
  s('notifications.mark_read', undefined, { notificationIds: [U('notif')] }),
  s('notifications.mark_all_read', undefined, {}),
  s('notifications.update_prefs', undefined, { prefs: [{ eventType: 'task.task_adding', channel: 'email', enabled: false }] }),
  // ACL
  s('acl.grant', doc, { principal: { kind: 'user', id: BOB }, role: 'editor' }),
  s('acl.set_link', doc, { scope: 'workspace', role: 'viewer' }),
  s('acl.revoke', doc, { principal: { kind: 'user', id: BOB } }),
  s('acl.request_access', doc, { id: U('req'), role: 'viewer' }, BOB),
  s('acl.decide_request', doc, { requestId: U('req'), decision: 'approve' }),
  s('acl.transfer_ownership', doc, { toPrincipalId: BOB }),
  // entities
  s('links.add', t('task', 'task'), { to: t('goal', 'goal'), relation: 'aligned-to' }),
  s('links.remove', t('task', 'task'), { to: t('goal', 'goal'), relation: 'aligned-to' }),
  s('entities.drop', t('project', 'project'), { source: doc, intent: 'link' }),
  s('entities.pin', undefined, { entity: t('goal', 'goal') }),
  s('entities.reorder_pins', undefined, { order: [t('goal', 'goal')] }),
  s('entities.unpin', undefined, { entity: t('goal', 'goal') }),
  // identity & agents
  s('identity.ensure_placeholder', undefined, { id: U('ph'), displayName: 'Frank', email: 'frank@example.com' }),
  s('identity.activate_placeholder', undefined, { placeholderId: U('ph'), principalId: U('frank') }),
  s('identity.ensure_placeholder', undefined, { id: U('ph2'), displayName: 'Gina' }),
  s('identity.merge_placeholder', undefined, { placeholderId: U('ph2'), intoPrincipalId: BOB }),
  s('onboarding.seed_starter_content', t('space', 'space')),
  s('agents.provision_personal_agent', undefined, { id: U('agent'), ownerId: ACTOR_ID }),
  s('agents.invoke', undefined, { id: U('invocation'), agentRef: { kind: 'person', id: U('agent') }, instruction: 'Summarise', origin: { kind: 'comment', commentId: U('comment') } }),
  // agents.invoke opened a pending approval (id = invocation id) for the agent's owner.
  s('agents.decide_approval', undefined, { approvalId: U('invocation'), decision: 'approve' }),
  s('agents.pause', undefined, { agentId: U('agent') }),
  // workplace
  s('mail.share_to_chat', t('channel', 'chat'), { threadId: 'thread-1' }),
  s('mail.create_task_from_thread', { kind: 'mail-thread', id: 'thread-1' }, { id: U('reply-task'), threadId: 'thread-1', title: 'Reply' }),
  s('commands.batch', undefined, { commands: [{ type: 'tasks.complete', target: t('task', 'task'), payload: {} }] }),
  s('forms.configure_on_submit', t('form', 'form'), { formRef: t('form', 'form'), actions: [{ type: 'tasks.create' }] }),
  // teardown (deletes last)
  s('kpis.delete_annotation', t('kpi', 'kpi'), { annotationId: U('annot') }),
  s('kpis.delete_entry', t('kpi', 'kpi'), { entryId: U('entry') }),
  s('kpis.delete', t('kpi', 'kpi')),
  s('milestones.delete', t('milestone', 'ms')),
  s('projects.delete', t('project', 'project2')),
  s('goals.delete', t('goal', 'goal2')),
  s('tasks.delete', t('task', 'task2')),
  s('task_sections.delete', t('task-section', 'section')),
  s('task_lists.archive', t('task-list', 'list')),
  s('task_lists.delete', t('task-list', 'list')),
  s('task_list_groups.delete', t('task-list-group', 'group')),
  s('im.disband_chat', t('channel', 'chat')),
  s('spaces.delete', t('space', 'space'), { confirmName: 'Eng' }),
]
