/**
 * W1-08 (#1505) — lucide icons for the entity kind registry (`IconName`).
 * Typed as `Record<IconName, LucideIcon>` so a new registry icon fails tsc here.
 */
import type { ComponentProps } from 'react'
import {
  AppWindow,
  Bell,
  BookOpen,
  Boxes,
  Brain,
  Building2,
  Calendar,
  CalendarDays,
  CalendarRange,
  CircleCheck,
  ClipboardCheck,
  Copy,
  DoorOpen,
  FileInput,
  FileText,
  Flag,
  Folder,
  FolderKanban,
  Gauge,
  Gavel,
  GitBranch,
  KeyRound,
  Layers,
  LayoutGrid,
  LayoutPanelLeft,
  Link,
  Link2,
  List,
  ListChecks,
  ListTree,
  Mail,
  MailPlus,
  MessageCircle,
  MessageSquare,
  MessageSquareQuote,
  MessagesSquare,
  Network,
  Newspaper,
  Paperclip,
  PlayCircle,
  Plug,
  Radar,
  Repeat,
  Rows3,
  Sparkles,
  Table,
  Table2,
  Target,
  TrendingUp,
  User,
  UsersRound,
  Video,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import { kindDescriptor, type EntityKind, type IconName } from '@rox/core/entities'

export const ENTITY_KIND_ICONS: Record<IconName, LucideIcon> = {
  'app-window': AppWindow,
  'bell': Bell,
  'book-open': BookOpen,
  'boxes': Boxes,
  'brain': Brain,
  'building-2': Building2,
  'calendar': Calendar,
  'calendar-days': CalendarDays,
  'calendar-range': CalendarRange,
  'circle-check': CircleCheck,
  'clipboard-check': ClipboardCheck,
  'copy': Copy,
  'door-open': DoorOpen,
  'file-input': FileInput,
  'file-text': FileText,
  'flag': Flag,
  'folder': Folder,
  'folder-kanban': FolderKanban,
  'gauge': Gauge,
  'gavel': Gavel,
  'git-branch': GitBranch,
  'key-round': KeyRound,
  'layers': Layers,
  'layout-grid': LayoutGrid,
  'layout-panel-left': LayoutPanelLeft,
  'link': Link,
  'link-2': Link2,
  'list': List,
  'list-checks': ListChecks,
  'list-tree': ListTree,
  'mail': Mail,
  'mail-plus': MailPlus,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'message-square-quote': MessageSquareQuote,
  'messages-square': MessagesSquare,
  'network': Network,
  'newspaper': Newspaper,
  'paperclip': Paperclip,
  'play-circle': PlayCircle,
  'plug': Plug,
  'radar': Radar,
  'repeat': Repeat,
  'rows-3': Rows3,
  'sparkles': Sparkles,
  'table': Table,
  'table-2': Table2,
  'target': Target,
  'trending-up': TrendingUp,
  'user': User,
  'users-round': UsersRound,
  'video': Video,
  'zap': Zap,
}

export function entityIconComponent(kind: EntityKind, icon?: string): LucideIcon {
  if (icon && icon in ENTITY_KIND_ICONS) return ENTITY_KIND_ICONS[icon as IconName]
  const fallback = kindDescriptor(kind)?.icon
  return (fallback && ENTITY_KIND_ICONS[fallback]) || Link
}

export function EntityKindIcon({ kind, icon, ...props }: { kind: EntityKind; icon?: string } & ComponentProps<LucideIcon>) {
  const Icon = entityIconComponent(kind, icon)
  return <Icon aria-hidden="true" {...props} />
}
