/** Hub taglines from super.engineering `welcome-phrase-*` strings (binary v6). */
export const SUPER_ENGINEERING_HUB_TAGLINES: readonly string[] = [
  'Frictionless agentic engineering',
  'Welcome to the future',
  'Zero resistance, infinite potential',
  'A room-temperature superconductor',
  'Where electrons flow without friction',
  'Cooper pairs dancing at 300K',
  'The Meissner effect is beautiful',
  'Flux quantization in progress',
  'Resistance is futile (literally)',
  'BCS theory was just the beginning',
  'Critical temperature: room temp',
  'The first neural net was built in 1958',
  'GPT stands for Generative Pre-trained Transformer',
  'Attention is all you need (2017)',
  'AlphaGo beat Lee Sedol 4-1 in 2016',
  'ELIZA (1966) was the first chatbot',
  'The term AI was coined at Dartmouth, 1956',
  'A perceptron has exactly one layer',
  'Backpropagation was popularized in 1986',
  'ImageNet has 14 million labeled images',
  'Deep Blue beat Kasparov in 1997',
  'GPT-2 was deemed too dangerous to release',
  'Transformers replaced RNNs almost overnight',
  'The bitter lesson: compute wins',
  'MNIST is the hello world of ML',
  'Dropout was invented to prevent overfitting',
  'Batch norm made deep networks trainable',
  'ResNets skip connections changed everything',
  'GANs: two networks in a trench coat',
  'The Chinese Room argues syntax isnt semantics',
  "Moore's Law kept AI scaling on track",
  'Reinforcement learning taught itself to walk',
  'Word2Vec: king minus man plus woman equals queen',
  'LSTM gates solved the vanishing gradient',
  'The Turing test was proposed in 1950',
  'Agents can ship pull requests while you sleep',
  'Engineering is the art of feasible systems',
]

export const SUPER_ENGINEERING_SCRAMBLE_CHARSET = '!?@$&~#%*+=<>'
