/**
 * W1-11 (#1508) — Agent governance contract surface (`@rox/core/agents`).
 *
 * TECH-SPEC §13, DATA-MODEL §5.12–§5.14:
 * - `./risk.ts` — how dangerous is this command, with this payload, and which
 *   `.scope` a command belongs to;
 * - `./governance.ts` — bindings, grants, approval policy and the admin floor,
 *   the `approval_request` / `standing_approval` lifecycle, rate limits;
 * - `./policy.ts` — the 10-step evaluation pipeline;
 * - `./audit.ts` — the append-only hash-chained audit log.
 */

// W1-11 (#1508) — risk classes and scopes.
export {
  AGENT_SCOPES,
  COMMAND_RISK,
  COMMAND_SCOPES,
  CONSERVATIVE_RISK_CLASS,
  DELETE_SCOPE,
  EXPLICITLY_CLASSIFIED_COMMANDS,
  MODULE_RISK_DEFAULT,
  OWNER_DM_SCOPE,
  RISK_CLASSES,
  RISK_CLASS_RANK,
  isAgentScope,
  isExplicitlyClassified,
  isRiskClass,
  maxRiskClass,
  riskClassFor,
  scopeForCommand,
  unclassifiedCommandTypes,
  type AgentScope,
  type RiskClass,
  type RiskClassifier,
  type RiskSpec,
  type ScopeResolutionContext,
} from './risk.ts'

// W1-11 (#1508) — bindings, grants, approvals, rate limits.
export {
  AGENT_ALL_SUBJECT,
  AGENT_BINDING_STATUSES,
  AGENT_DISPLAY_NAME,
  AGENT_HANDLE_ALIAS,
  AGENT_PERMISSION_MODES,
  AGENT_USERNAME_PATTERN,
  AGGREGATE_SCOPE,
  APPROVAL_MODES,
  APPROVAL_MODE_RANK,
  APPROVAL_REQUEST_STATUSES,
  APPROVAL_TTL_HOURS,
  DEFAULT_RATE_LIMIT_POLICY,
  DEFAULT_STANDING_APPROVAL_DAYS,
  POLICY_MODES_BY_PERMISSION_MODE,
  RATE_LIMIT_WINDOWS,
  RATE_LIMIT_WINDOW_MS,
  RULE_ALL_SUBJECT,
  STANDING_APPROVAL_NEVER_RISK,
  agentIsRunnable,
  agentRateLimitSubject,
  approvalPolicyForPermissionMode,
  approvalRequestIsExpired,
  approvalRequestIsOpen,
  containerMatches,
  grantMatches,
  isAgentBindingStatus,
  isApprovalMode,
  isApprovalRequestStatus,
  isOwnerDmScope,
  isScopeCovered,
  kindsOf,
  personalAgentDraft,
  policyModeFor,
  rateLimitKey,
  rateLimitScopesFor,
  standingApprovalFromApproval,
  standingApprovalMatches,
  strictestApprovalMode,
  type AgentBinding,
  type AgentBindingStatus,
  type AgentGrant,
  type AgentPermissionMode,
  type AgentRuntime,
  type ApprovalMode,
  type ApprovalPolicy,
  type ApprovalPolicyRule,
  type ApprovalRequest,
  type ApprovalRequestStatus,
  type ContainerRef,
  type GrantSelector,
  type PolicyModeInput,
  type RateLimitBucket,
  type RateLimitDecision,
  type RateLimiter,
  type RateLimitSpend,
  type RateLimitWindow,
  type RememberDecision,
  type ScopeRequest,
  type StandingApproval,
  type StandingRequest,
  type WorkspaceFloor,
} from './governance.ts'

// W1-11 (#1508) — the ten-step pipeline.
export {
  APPROVAL_SUMMARY_COMMANDS,
  APPROVAL_SUMMARY_KEY_PREFIX,
  POLICY_STEPS,
  actingAgentPrincipalId,
  actingOwnerPrincipalId,
  approvalSummaryKeyFor,
  evaluateApprovalGate,
  evaluatePolicy,
  evaluatePreflight,
  policyRiskClass,
  refKey,
  spendRateLimit,
  type ApprovalGatePorts,
  type EvaluatePolicyResult,
  type PolicyAllowance,
  type PolicyAsk,
  type PolicyDecision,
  type PolicyDenial,
  type PolicyDenyReason,
  type PolicyPorts,
  type PolicyPreflight,
  type PolicyRateLimit,
  type PolicyRequest,
  type PolicyStep,
  type PreflightResult,
  type RateLimitPort,
} from './policy.ts'

// W1-11 (#1508) — the audit chain.
export {
  AUDIT_ACTOR_KINDS,
  AUDIT_DECISIONS,
  AUDIT_HASH_ALGORITHM,
  AUDIT_RETENTION_DAYS,
  auditProvenanceFromOrigin,
  auditRequestHash,
  auditRowContent,
  auditRowHash,
  chainAuditRow,
  isAuditActorKind,
  isAuditDecision,
  verifyAuditChain,
  type AuditActorKind,
  type AuditChainBreak,
  type AuditChainVerification,
  type AuditDecision,
  type AuditProvenance,
  type AuditRow,
  type AuditRowInput,
  type AuditTrigger,
} from './audit.ts'