export {
  VOICE_PREFS_VERSION,
  DEFAULT_WAKE_PHRASE,
  STT_ENGINES,
  TTS_ENGINES,
  AUDIO_RETENTION_POLICIES,
  VOICE_CLOUD_LABEL,
  getDefaultVoicePrefs,
  shouldMigrateLegacyLocalDefault,
  isSttEngine,
  isTtsEngine,
  isAudioRetention,
  isModelHealthStatus,
  type SttEngine,
  type TtsEngine,
  type AudioRetention,
  type ModelHealthStatus,
  type AudioDevice,
  type VoicePrefs,
  type VoiceHealth,
  type TranscribeInput,
  type TranscribeResult,
  type SpeakInput,
  type SpeakResult,
  type TranscribeAdapter,
  type SpeakAdapter,
  type VoiceRecordingStatus,
  type VoiceRecording,
  type VoiceTranscriptKind,
  type VoiceExportFormat,
  type VoiceOverlayPosition,
  type VoiceDelivery,
  type VoiceRecognitionLanguage,
  type VoiceTranscriptRevision,
} from './types.ts'

export {
  VOICE_OVERLAY_POSITIONS,
  VOICE_DELIVERIES,
  VOICE_RECOGNITION_LANGUAGES,
  VOICE_EXPORT_FORMATS,
  isVoiceOverlayPosition,
  isVoiceDelivery,
  isVoiceRecognitionLanguage,
  isVoiceExportFormat,
  resolveRecognitionLanguage,
  formatSrtTime,
  formatSrt,
  revisionFromResult,
  resultFromRevision,
  applyTranscriptDelivery,
  joinDraftTranscript,
} from './history.ts'

export {
  DEFAULT_VOICE_TOGGLE_ACCELERATOR,
  DEFAULT_VOICE_CANCEL_ACCELERATOR,
  DEFAULT_VOICE_PTT,
  RESERVED_VOICE_ACCELERATORS,
  PTT_MODIFIERS,
  isVoicePttModifier,
  isToggleChord,
  isCancelChord,
  isPttPress,
  isPttRelease,
  normalizeAccelerator,
  acceleratorsConflict,
  voiceCommandFromInput,
  type VoicePttModifier,
  type VoiceCommandAction,
  type VoiceCommand,
  type VoiceKeyInput,
} from './hotkeys.ts'

export {
  ROX_VOICE_GATEWAY_BASE_URL,
  ROX_VOICE_PUBLIC_MODEL_ID,
  ROX_VOICE_UI_NAME,
  ROX_VOICE_PUBLIC_CLIENT_ID,
  ROX_VOICE_UPSTREAM_ASR_MODEL,
  ROX_VOICE_PROCESS_MODEL,
  ROX_VOICE_PROCESS_FALLBACK,
  ROX_VOICE_LANGUAGE_LABEL,
  ROX_VOICE_BOOTSTRAP_PATH,
  ROX_VOICE_CAPABILITIES_PATH,
  ROX_VOICE_TRANSCRIPTIONS_PATH,
  ROX_VOICE_PROCESS_PATH,
  ROX_VOICE_ACCESS_TOKEN_TTL_MS,
  ROX_VOICE_ALLOWED_SCOPES,
  LAST_KNOWN_GOOD_VOICE_CAPABILITIES,
  parseVoiceCapabilities,
  voiceLanguageLabel,
  scopesAreVoiceOnly,
  type RoxVoiceScope,
  type VoiceTimestampGranularity,
  type VoiceAvailability,
  type VoiceTranscriptSegment,
  type VoiceTranscriptWord,
  type VoiceCapabilities,
  type VoiceBootstrapRequest,
  type VoiceBootstrapResponse,
} from './contracts.ts'

export {
  getCachedVoiceCapabilities,
  rememberVoiceCapabilities,
  resetVoiceCapabilitiesCache,
} from './capabilities.ts'

export {
  usesCloudStt,
  shouldUploadAudio,
  resolveAudioRetention,
  shouldDiscardAudio,
  canStartWakeListening,
  withWakeWordConsent,
  describeLocalSttBackend,
  buildVoiceHealth,
  isVoiceActive,
  type WakeListenDecision,
} from './policy.ts'

export {
  VoicePrivacyError,
  transcribeWithPolicy,
  speakWithPolicy,
  assertEditableTranscript,
} from './transcribe.ts'

export {
  VOICE_PREFS_FILE,
  getVoicePrefsPath,
  normalizeVoicePrefs,
  loadVoicePrefs,
  saveVoicePrefs,
} from './storage.ts'

export {
  applyTranscriptPatch,
  bindSpeaker,
  coverageGaps,
  emptyTranscriptState,
  segmentKey,
  type SpeakerBinding,
  type TranscriptSegmentPatch,
  type TranscriptState,
} from './transcript-reducer.ts'
