import fs from 'node:fs';
import path from 'node:path';
import cp from 'node:child_process';
import crypto from 'node:crypto';
const repo='rox-one/rox-one',root=process.cwd(),hash=x=>crypto.createHash('sha256').update(x).digest('hex');
const call=(args)=>cp.execFileSync('gh',args,{cwd:root,encoding:'utf8',maxBuffer:16*1024*1024}).trim();
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')),out='plans/rox-suite';
const manifests=['product','meetings','collaboration','services'].map(group=>`docs/rox-suite/issue-drafts/${group}/${group}.json`);
function collect(){return manifests.flatMap(p=>{if(!fs.existsSync(p)){const group=p.split('/').at(-1);p='docs/rox-suite/issue-drafts/'+group;}const x=read(p);return Array.isArray(x)?x:x.issues||x.drafts;});}
function validate(items){const errors=[],ids=new Set(items.map(x=>x.id)),source=new Map();if(items.length!==30)errors.push('expected30 requirement issues');if(ids.size!==items.length)errors.push('duplicate ID');for(const x of items){if(!x.title||!x.bodyFile)errors.push('missing title/body '+x.id);const body=fs.readFileSync(x.bodyFile,'utf8');if(body.length<3000)errors.push('thin specification '+x.id);for(const dep of x.dependsOn||[])if(!ids.has(dep))errors.push('unknown prerequisite '+x.id+' '+dep);for(const pattern of [/DoD|Definition of Done/i,/hover/i,/keyboard|клавиатур/i,/input|вход/i,/output|выход/i,/permission|ACL|права/i,/test|тест|E2E/i])if(!pattern.test(body))errors.push('missing detail '+x.id+' '+pattern);let refs=0;for(const m of body.matchAll(/https:\/\/github\.com\/rox-one\/rox-one\/blob\/([a-f0-9]{40})\/([^\s)#]+)(?:#L(\d+)(?:-L(\d+))?)?/g)){refs++;const[,sha,p,a,b]=m,key=sha+':'+p;try{if(!source.has(key))source.set(key,cp.execFileSync('git',['show',key],{encoding:'utf8',maxBuffer:12*1024*1024}));const lines=source.get(key).replace(/\n$/,'').split('\n').length;if(a&&(Number(a)<1||Number(b||a)>lines))errors.push('bad source range '+x.id+' '+key);}catch{errors.push('missing source '+x.id+' '+key);}}if(!refs)errors.push('missing immutable source '+x.id);if(/clipboard-\d{4}|data:image\/|larksuite\.com\/console|-----BEGIN [A-Z ]*PRIVATE KEY-----/i.test(body))errors.push('private screenshot marker '+x.id);}
const seen=new Set(),active=new Set(),order=[];function walk(x){if(active.has(x.id)){errors.push('dependency cycle '+x.id);return;}if(seen.has(x.id))return;active.add(x.id);for(const id of x.dependsOn||[]){const p=items.find(i=>i.id===id);if(p)walk(p);}active.delete(x.id);seen.add(x.id);order.push(x.id);}for(const x of items)walk(x);return{errors,order,sourceFiles:source.size};}
function linkBody(x,receipt){let body=fs.readFileSync(x.bodyFile,'utf8');body+='\n\n## GitHub dependency links (нормативный handoff)\n\n';if(!(x.dependsOn||[]).length)body+='Прямых новых prerequisites нет; использовать общие действующие primitives.\n';for(const d of x.dependsOn||[]){const y=receipt.issues.find(y=>y.id===d);body+=`- Требуется [${d} — #${y.number}](${y.url})\n`; }for(const d of x.relatedRequirementIds||[]){const y=receipt.issues.find(y=>y.id===d);if(!y)throw Error('unknown softlink '+d);body+=`- Связанная новая задача: [${d} — #${y.number}](${y.url})\n`;}for(const n of x.relatedIssues||[])body+=`- Связанный ранее созданный issue: [#${n}](https://github.com/${repo}/issues/${n})\n`;body+=`\nSpecification ID: ${x.id}. Снимок исходного ROX: 249b3b44220bcfbd7d467de9cfc18f76e1c37807. Эти ссылки задают зависимости, а не статус выполненной реализации.\n`;return body;}
function save(p,x){fs.writeFileSync(p,JSON.stringify(x,null,2)+'\n');}
const cmd=process.argv[2],items=collect(),validation=validate(items);for(const x of items){for(const n of x.relatedIssues||[])if(!Number.isInteger(n)||n<1)validation.errors.push('invalid existing issue '+x.id);for(const d of x.relatedRequirementIds||[])if(!items.some(i=>i.id===d))validation.errors.push('invalid related requirement '+x.id+' '+d);}if(validation.errors.length)throw Error(validation.errors.join('\n'));
fs.mkdirSync(out,{recursive:true});
const receiptPath=out+'/publication.json';let receipt=fs.existsSync(receiptPath)?read(receiptPath):{schemaVersion:1,repository:repo,status:'IN_PROGRESS',issues:[],privateImagesPublished:false};
if(receipt.repository!==repo||new Set(receipt.issues.map(x=>x.id)).size!==receipt.issues.length||receipt.issues.some(x=>!items.some(i=>i.id===x.id)||!Number.isInteger(x.number)||x.url!==`https://github.com/${repo}/issues/${x.number}`))throw Error('receipt identity/repository mismatch');
const bundleDigest=hash(JSON.stringify(items.map(x=>({id:x.id,title:x.title,dependsOn:x.dependsOn,relatedIssues:x.relatedIssues,relatedRequirementIds:x.relatedRequirementIds,bodySha256:hash(fs.readFileSync(x.bodyFile))}))));
if(['publish','link-and-verify'].includes(cmd)){if(receipt.status==='PUBLISHED_AND_READBACK_VERIFIED')receipt.previousVerifiedBundle=receipt.bundleDigest;receipt.status='IN_PROGRESS';receipt.bundleDigest=bundleDigest;receipt.attemptStartedAt=new Date().toISOString();save(receiptPath,receipt);}
if(cmd==='collect'){save(out+'/issues.json',{schemaVersion:1,revision:1,status:'PREPARED_NOT_IMPLEMENTED',repository:repo,sourceSha:'249b3b44220bcfbd7d467de9cfc18f76e1c37807',oldProgram:'Macro52WP manifest remains separate; RS requirements need new scheduler task contracts before dispatch',topologicalOrder:validation.order,issues:items.map(x=>({...x,bodySha256:hash(fs.readFileSync(x.bodyFile))}))});console.log(JSON.stringify({status:'VALIDATED_DRAFTS',issues:items.length,sourceFiles:validation.sourceFiles}));}
else if(cmd==='publish'){const existing=JSON.parse(call(['issue','list','--repo',repo,'--state','all','--limit','1000','--json','number,title,url']));for(const x of items){if(receipt.issues.some(i=>i.id===x.id))continue;const matches=existing.filter(i=>i.title.includes(`[${x.id}]`));if(matches.length>1)throw Error('duplicate remote '+x.id);let remote=matches[0];if(!remote){const title=`[ROX Suite][${x.id}] ${x.title.replace(/^\[ROX Suite\]\[[^\]]+\]\s*/,'')}`;const url=call(['issue','create','--repo',repo,'--title',title,'--body-file',x.bodyFile]);remote={url,number:Number(url.split('/').pop()),title};existing.push(remote);}receipt.issues.push({id:x.id,...remote,draftBodySha256:hash(fs.readFileSync(x.bodyFile)),state:'OPEN',createdOrRecovered:true});save(receiptPath,receipt);console.log(JSON.stringify({created:x.id,number:remote.number,url:remote.url}));}}
else if(cmd==='link-and-verify'){if(receipt.issues.length!==items.length)throw Error('publication incomplete');fs.mkdirSync('docs/rox-suite/published',{recursive:true});for(const x of items){const r=receipt.issues.find(i=>i.id===x.id),body=linkBody(x,receipt),p=`docs/rox-suite/published/${x.id}.md`;fs.writeFileSync(p,body);call(['issue','edit',String(r.number),'--repo',repo,'--body-file',p]);const actual=JSON.parse(call(['issue','view',String(r.number),'--repo',repo,'--json','number,title,body,url,state']));if(actual.body!==body||actual.state!=='OPEN'||actual.url!==r.url||!actual.title.includes(`[${x.id}]`))throw Error('readback mismatch '+x.id);r.publishedBodyFile=p;r.publishedBodySha256=hash(actual.body);r.initialDraftBodySha256??=r.draftBodySha256;r.draftBodySha256=hash(fs.readFileSync(x.bodyFile));r.verifiedReadbackAt=new Date().toISOString();save(receiptPath,receipt);console.log(JSON.stringify({verified:x.id,number:r.number}));}receipt.status='PUBLISHED_AND_READBACK_VERIFIED';receipt.requirementCount=items.length;save(receiptPath,receipt);let md='# ROX Suite — новые issues по скриншотам\n\n30 отдельных задач созданы в rox-one/rox-one. UI не реализован; cloud coding не запускался. Частные screenshots не загружались.\n\n| ID | Новая GitHub issue | Раздел | Depends on |\n|---|---|---|---|\n';for(const x of items){const r=receipt.issues.find(i=>i.id===x.id);md+=`| ${x.id} | [#${r.number}: ${x.title.replace(/\|/g,'/')} ](${r.url}) | ${x.area} | ${(x.dependsOn||[]).map(d=>{const y=receipt.issues.find(i=>i.id===d);return`[#${y.number}](${y.url})`;}).join(', ')} |\n`;}md+='\nMachine handoff: [issues.json](../../plans/rox-suite/issues.json), [publication.json](../../plans/rox-suite/publication.json). Exact опубликованные bodies находятся в [published](published/).\n';fs.writeFileSync('docs/rox-suite/README.md',md);console.log(JSON.stringify({status:receipt.status,issues:items.length}));}
else throw Error('usage: issues.mjs collect | publish | link-and-verify');
