import {afterAll,beforeAll,describe,expect,it} from 'bun:test'
import {existsSync} from 'node:fs'
import {resolve} from 'node:path'
import {chromium,expect as playwrightExpect,type Browser,type Page} from 'playwright/test'
const repository=resolve(import.meta.dirname,'../../../../../../..'),fixture=resolve(import.meta.dirname,'fixtures/chat-scroll'),endpoint='http://127.0.0.1:5241'
const executablePath=process.env.CHROMIUM_EXECUTABLE??chromium.executablePath(),timeout=Math.min(150000,Math.max(60000,Number(process.env.ROX_CHAT_SCROLL_BROWSER_TIMEOUT_MS)||60000))
const check=playwrightExpect.configure({timeout:15000}),viewport=(page:Page)=>page.locator('[data-radix-scroll-area-viewport]')
const action=(page:Page,code:string)=>page.evaluate(code)
const positions=(page:Page)=>page.evaluate(()=>({outer:document.getElementById('outer')!.scrollTop,window:window.scrollY}))
const bottom=(page:Page)=>viewport(page).evaluate(e=>e.scrollHeight-e.scrollTop-e.clientHeight)
const scrolls=(page:Page)=>page.evaluate(()=>(window as any).__scrollFixture.scrolls.map((item:any)=>({owned:item.element.hasAttribute('data-radix-scroll-area-viewport'),behavior:item.options.behavior})))
describe.skipIf(!existsSync(executablePath))('production ChatDisplay private output viewport',()=>{
 let server:ReturnType<typeof Bun.spawn>|undefined,browser:Browser,ownedChrome:{pid:number,profile:string}|undefined
 const processText=async(args:string[])=>{const child=Bun.spawn(['ps',...args],{stdout:'pipe',stderr:'ignore'});const value=await new Response(child.stdout).text();await child.exited;return value}
 const stillOwned=async()=>{if(!ownedChrome)return false;const command=(await processText(['-p',String(ownedChrome.pid),'-o','command='])).trim();return command.startsWith(executablePath+' ')&&command.includes('--rox-chat-scroll-fixture')&&command.includes(ownedChrome.profile)}
 const stop=async()=>{server?.kill('SIGKILL');if(browser){await Promise.race([browser.close().catch(()=>{}),Bun.sleep(5000)]);if(await stillOwned()){process.kill(ownedChrome!.pid,'SIGTERM');await Bun.sleep(500);if(await stillOwned())process.kill(ownedChrome!.pid,'SIGKILL')}}await server?.exited}
 beforeAll(async()=>{try{server=Bun.spawn(['node',resolve(repository,'node_modules/vite/bin/vite.js'),'--config',resolve(fixture,'vite.config.ts'),'--port','5241'],{cwd:repository,stdout:'ignore',stderr:'ignore'});const deadline=Date.now()+30000;for(;;){if(server.exitCode!==null)throw Error('ChatDisplay fixture exited');try{const response=await fetch(endpoint);if(response.ok){if(!(await response.text()).includes('rox-chat-scroll-fixture'))throw Error('Foreign owner occupies fixture port');break}}catch(error){if(error instanceof Error&&error.message.includes('Foreign owner'))throw error}if(Date.now()>deadline)throw Error('ChatDisplay fixture startup timeout');await Bun.sleep(100)}browser=await chromium.launch({executablePath,headless:true,args:['--no-sandbox','--rox-chat-scroll-fixture']});const rows=(await processText(['-axo','pid=,command='])).split('\n').map(line=>line.trim().match(/^(\d+)\s+(.*)$/)).filter((row):row is RegExpMatchArray=>!!row&&row[2].startsWith(executablePath+' ')&&row[2].includes('--rox-chat-scroll-fixture'));if(rows.length!==1)throw Error('Owned Chrome process identity unavailable');const profile=rows[0][2].match(/--user-data-dir=\S+/)?.[0];if(!profile)throw Error('Owned Chrome profile unavailable');ownedChrome={pid:Number(rows[0][1]),profile}}catch(error){await stop();throw error}},45000)
 afterAll(stop,timeout)
 const withPage=async(run:(page:Page)=>Promise<void>,reducedMotion:'reduce'|'no-preference'='reduce')=>{const context=await browser.newContext({viewport:{width:1200,height:900},reducedMotion}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));try{await page.goto(endpoint,{waitUntil:'domcontentloaded',timeout});await check(viewport(page)).toBeVisible();await check.poll(()=>viewport(page).evaluate(e=>e.scrollHeight>e.clientHeight)).toBe(true);await check.poll(()=>bottom(page)).toBeLessThan(2);await page.waitForTimeout(600);await action(page,"document.getElementById('outer').scrollTop=80;window.scrollTo(0,40);window.__scrollFixture.clear()");await run(page);expect(errors).toEqual([])}catch(error){throw Error('Production ChatDisplay fixture failed; pageErrors='+JSON.stringify(errors)+'; body='+await page.locator('body').innerText(),{cause:error})}finally{await context.close()}}
 it('stream output stays in the real nested viewport and leaves outer workspace/window unchanged',()=>withPage(async page=>{const before=await positions(page);expect(before.window).toBe(40);await action(page,'window.__scrollFixture.api.grow()');await check.poll(()=>bottom(page)).toBeLessThan(2);await check.poll(()=>scrolls(page)).not.toHaveLength(0);expect(await scrolls(page)).toEqual(expect.arrayContaining([{owned:true,behavior:'instant'}]));expect((await scrolls(page)).every(item=>item.owned)).toBeTrue();expect(await positions(page)).toEqual(before);expect(await action(page,'window.__scrollFixture.jumps.length')).toBe(0)}),timeout)
 it('focused readers stay on history while output grows; unfocused panels preserve instant follow',()=>withPage(async page=>{await viewport(page).evaluate(e=>{e.scrollTop=e.scrollHeight-e.clientHeight-400;e.dispatchEvent(new Event('scroll'))});const top=await viewport(page).evaluate(e=>e.scrollTop);await action(page,'window.__scrollFixture.api.grow()');await page.waitForTimeout(600);expect(await viewport(page).evaluate(e=>e.scrollTop)).toBe(top);expect(await scrolls(page)).toEqual([]);await action(page,'window.__scrollFixture.api.focus(false);window.__scrollFixture.api.grow()');await check.poll(()=>bottom(page)).toBeLessThan(2);expect((await scrolls(page)).at(-1)).toEqual({owned:true,behavior:'instant'})}),timeout)
 it('hidden document blocks stream and submitted output, and visible reduced-motion follow is instant',()=>withPage(async page=>{const before=await positions(page);await action(page,'window.__scrollFixture.hidden(true);window.__scrollFixture.api.grow();window.__scrollFixture.api.submit()');await page.waitForTimeout(600);expect(await scrolls(page)).toEqual([]);expect(await positions(page)).toEqual(before);expect(await action(page,'window.__scrollFixture.sends')).toEqual(['Synthetic question']);await action(page,'window.__scrollFixture.hidden(false);window.__scrollFixture.api.grow()');await check.poll(()=>scrolls(page)).not.toHaveLength(0);expect((await scrolls(page)).at(-1)?.behavior).toBe('instant')}),timeout)
 it('focused normal-motion follow stays smooth and both submit/committed user callbacks use the viewport',()=>withPage(async page=>{await action(page,'window.__scrollFixture.api.grow()');await check.poll(()=>scrolls(page)).not.toHaveLength(0);expect((await scrolls(page)).at(-1)).toEqual({owned:true,behavior:'smooth'});await action(page,'window.__scrollFixture.clear();window.__scrollFixture.api.submit()');await check.poll(()=>scrolls(page)).not.toHaveLength(0);expect((await scrolls(page)).at(-1)).toEqual({owned:true,behavior:'smooth'});await action(page,'window.__scrollFixture.clear();window.__scrollFixture.api.commitUser()');await check.poll(()=>scrolls(page)).not.toHaveLength(0);expect((await scrolls(page)).at(-1)).toEqual({owned:true,behavior:'smooth'});expect(await action(page,'window.__scrollFixture.jumps.length')).toBe(0)},'no-preference'),timeout)
 it('queued submit and obsolete ResizeObserver callbacks cannot follow a replacement A→B→A session',()=>withPage(async page=>{const result=await page.evaluate(()=>{const f=(window as any).__scrollFixture,old=f.captureResize();f.api.focus(false);f.hold();f.api.submit();f.api.scope('B');f.api.scope('A');f.clear();f.fireResize(old);const released=f.release();return {released,oldCount:old.length,scrolls:f.scrolls.length,jumps:f.jumps.length}});expect(result.released).toBeGreaterThan(0);expect(result.oldCount).toBeGreaterThan(0);expect(result.scrolls).toBe(0);expect(result.jumps).toBe(0)}),timeout)
 it('queued callbacks do not scroll after ChatDisplay unmounts',()=>withPage(async page=>{const before=await positions(page);const result=await page.evaluate(()=>{const f=(window as any).__scrollFixture;f.hold();f.api.submit();f.api.mount(false);f.clear();const released=f.release();return {released,scrolls:f.scrolls.length,jumps:f.jumps.length}});expect(result.released).toBeGreaterThan(0);expect(result.scrolls).toBe(0);expect(result.jumps).toBe(0);expect(await positions(page)).toEqual(before)}),timeout)
 it('lazy-loaded history keeps its private height anchor and explicit message jumps remain available',()=>withPage(async page=>{const before=await viewport(page).evaluate(e=>e.scrollHeight);await viewport(page).evaluate(e=>{e.scrollTop=0;e.dispatchEvent(new Event('scroll'))});await check.poll(()=>viewport(page).evaluate(e=>e.scrollHeight)).toBeGreaterThan(before);await check.poll(()=>viewport(page).evaluate(e=>e.scrollTop)).toBeGreaterThan(100);await action(page,'window.__scrollFixture.clear();window.__scrollFixture.api.jump()');await check.poll(()=>action(page,'window.__scrollFixture.jumps.length')).toBeGreaterThan(0)}),timeout)
})
