/**
 * W1-15 (#1512) — Agent panel contracts (TECH-SPEC §18; UI-SPEC §25).
 *
 * `context.ts` is what the agent may see of the current surface; `session.ts`
 * is the runtime envelope (origin `agent-panel`, `contextSnapshot`, persisted
 * UI state). Named re-export blocks, mirroring `../entities/index.ts`.
 */

export {
  AGENT_CONTEXT_CHARS_PER_TOKEN,
  AGENT_CONTEXT_DEBOUNCE_MS,
  AGENT_CONTEXT_MAX_REFS,
  AGENT_CONTEXT_MAX_TOKENS,
  AGENT_EXCERPT_MAX_CHARS,
  AGENT_PANEL_AUTO_CONTEXT_POLICY_KEY,
  CONTEXT_EXPANSION_ORDER,
  FALLBACK_QUICK_ACTION_KEYS,
  MAX_QUICK_ACTIONS,
  MAX_VISIBLE_QUICK_ACTIONS,
  NEVER_AUTO_ATTACH_PRIVATE_KINDS,
  NON_RAIL_AGENT_SURFACES,
  consentCandidates,
  contextForDispatch,
  contextGroupRefs,
  cutExcerpt,
  estimateContextTokens,
  fallbackQuickActions,
  fallbackSurfaceContext,
  filterAutoAttach,
  fitContextBudget,
  mayAutoAttachRef,
  normalizeContextSnapshot,
  redactExpandedRefs,
  type AgentContextProvider,
  type AgentPanelSurface,
  type AutoAttachFacts,
  type ConsentCandidate,
  type ContextExpansionGroup,
  type ExpandedContextRef,
  type QuickAction,
  type SurfaceContext,
  type TextSelectionSnapshot,
} from './context.ts'

export {
  AGENT_APPROVALS_EVENT_TYPE,
  AGENT_APPROVALS_TOPIC,
  AGENT_PANEL_DEFAULT_WIDTH,
  AGENT_PANEL_DOCK_MODES,
  AGENT_PANEL_DRAFTS_FILE,
  AGENT_PANEL_LABEL,
  AGENT_PANEL_MAX_WIDTH,
  AGENT_PANEL_MIN_WIDTH,
  AGENT_PANEL_ORIGIN,
  AGENT_PANEL_SHARED_DOCK_MIN_WINDOW,
  AGENT_PANEL_STATE_FILE,
  AGENT_PANEL_STATUSES,
  AGENT_PANEL_SURFACE_CLASSES,
  CHROME_STATE_FILE,
  DEFAULT_AGENT_PANEL_DRAFTS_STATE,
  DEFAULT_AGENT_PANEL_UI_STATE,
  DEFAULT_CHROME_UI_STATE,
  LOCAL_PINS_FILE,
  agentApprovalsWireTopic,
  agentPanelCommandOrigin,
  asAgentPanelProposal,
  clampAgentPanelWidth,
  hasContextSnapshot,
  needsContextDivider,
  withContextSnapshot,
  type AgentPanelCommandOrigin,
  type AgentPanelDockMode,
  type AgentPanelDraftsState,
  type AgentPanelSession,
  type AgentPanelStatus,
  type AgentPanelSurfaceClass,
  type AgentPanelUiState,
  type AgentPanelUserMessage,
  type ChromeUiState,
  type CreateAgentPanelSessionInput,
} from './session.ts'