/**
 * Rox History — clipboard polling monitor.
 *
 * Polls an injected `ClipboardAdapter` (production builds it from Electron's
 * async/W3C-shaped `clipboard`; tests inject a fake) and hands captures to a
 * `ClipboardEntrySink`. Timers and the clock are injectable so the adaptive
 * 300 ms → 750 ms cadence is deterministic under test. A tick never throws out:
 * failures go to `onError`, and overlapping ticks are discarded (an in-flight
 * tick holds the flag until its awaited reads settle).
 */

import { createHash } from 'node:crypto'
import type { ClipChangedPayload } from '@rox/shared/clipboard-history'
import {
  ClipEntryRejectedError,
  MAX_IMAGE_BYTES,
  MAX_TEXT_BYTES,
  type ClipEntryInput,
  type ClipImageFormat,
  type ClipboardEntrySink,
} from './store'

/** Pixel size plus a ≤240×160 PNG preview decoded from image bytes. */
export interface ClipboardImagePreview {
  width: number
  height: number
  thumbnailPng: Buffer
}

/**
 * Minimal clipboard surface the monitor depends on, shaped like Electron 44`s
 * async `clipboard` module. `decodeImage` keeps the monitor Electron-free: the
 * production adapter decodes with `nativeImage` outside this module, tests
 * inject a stub.
 */
export interface ClipboardAdapter {
  /** Current plain text; `''` when the pasteboard carries none. */
  readText(): Promise<string>
  /** Platform MIME types currently on the clipboard; [] when unreadable. */
  readTypes(): Promise<string[]>
  /** Raw OS pasteboard marker probe (e.g. org.nspasteboard.ConcealedType, com.compuserve.gif). */
  hasRawFormat(rawFormat: string): Promise<boolean>
  /** Payload bytes for one MIME type, or null when absent/empty. */
  readTypeBytes(mimeType: string): Promise<Buffer | null>
  writeText(text: string): Promise<void>
  /** Replace the clipboard with one entry carrying this MIME type. */
  writeTypeBytes(mimeType: string, bytes: Buffer): Promise<void>
  /** Decode bytes into dimensions + a PNG thumbnail; null when undecodable. */
  decodeImage(bytes: Buffer): Promise<ClipboardImagePreview | null>
}

export interface ClipboardMonitorOptions {
  adapter: ClipboardAdapter
  sink: ClipboardEntrySink
  onChanged?: (payload: ClipChangedPayload) => void
  onError?: (error: unknown) => void
  setTimeout?: (handler: () => void, delayMs: number) => MonitorTimerHandle
  clearTimeout?: (handle: MonitorTimerHandle) => void
  now?: () => Date
}

/** Opaque handle from the injected timer; the monitor never inspects it. */
export type MonitorTimerHandle = unknown

/** Apple pasteboard types marking content the user did not ask us to keep. */
export const CONCEALED_FORMATS: Record<string, true> = {
  'org.nspasteboard.ConcealedType': true,
  'org.nspasteboard.TransientType': true,
  'org.nspasteboard.AutoGeneratedType': true,
}

const FAST_INTERVAL_MS = 300
const SLOW_INTERVAL_MS = 750
const ACTIVITY_WINDOW_MS = 30_000
/** A text-free image pasteboard is re-read at most this often, bounding the read cost. */
const IMAGE_POLL_INTERVAL_MS = 1200
/** Raw pasteboard type carrying GIF bytes (used by both the monitor and the copy path). */
export const GIF_FORMAT = 'com.compuserve.gif'
/** Image MIME types we can store, in capture-preference order. */
const IMAGE_MIME_PRIORITY = ['image/gif', 'image/png', 'image/jpeg', 'image/webp', 'image/tiff'] as const
/** Stored formats; MIME types absent here (webp/tiff) are skipped, never mislabeled. */
const MIME_IMAGE_FORMAT: Record<string, ClipImageFormat | undefined> = {
  'image/gif': 'gif',
  'image/jpeg': 'jpg',
  'image/png': 'png',
}
const IMAGE_FILENAME = /\.(?:png|jpe?g|gif|webp|bmp|tiff?|heic|avif)$/i

function isTextFormat(format: string): boolean {
  return format === 'NSStringPboardType' || format.includes('text/plain') || format.startsWith('public.text') || format.includes('plain-text')
}

function isImageFormat(format: string): boolean {
  return format.includes('image') || format.includes('png') || format.includes('tiff') || format.includes('jpeg') || format.includes('gif')
}

export class ClipboardMonitor {
  private readonly adapter: ClipboardAdapter
  private readonly sink: ClipboardEntrySink
  private readonly onChanged: ((payload: ClipChangedPayload) => void) | undefined
  private readonly onError: ((error: unknown) => void) | undefined
  private readonly scheduleTimer: (handler: () => void, delayMs: number) => MonitorTimerHandle
  private readonly cancelTimer: (handle: MonitorTimerHandle) => void
  private readonly now: () => Date

  private running = false
  private inFlight = false
  private timer: MonitorTimerHandle | undefined
  private lastActivityAt = 0
  private currentIntervalMs = FAST_INTERVAL_MS
  private textHash: string | null = null
  private lastImageHash: string | null = null
  private lastImagePollAt = Number.NEGATIVE_INFINITY
  private ownWrites = 0

  constructor(options: ClipboardMonitorOptions) {
    this.adapter = options.adapter
    this.sink = options.sink
    this.onChanged = options.onChanged
    this.onError = options.onError
    this.now = options.now ?? (() => new Date())
    this.scheduleTimer = options.setTimeout ?? ((handler, delayMs) => setTimeout(handler, delayMs))
    this.cancelTimer = options.clearTimeout ?? (handle => { clearTimeout(handle as NodeJS.Timeout) })
  }

  start(): void {
    if (this.running) return
    this.running = true
    this.lastActivityAt = this.now().getTime()
    this.#schedule()
  }

  stop(): void {
    if (!this.running) return
    this.running = false
    if (this.timer !== undefined) this.cancelTimer(this.timer)
    this.timer = undefined
  }

  /** Suppress the next tick so copying from the history is never re-captured. */
  notifyOwnWrite(): void {
    this.ownWrites += 1
  }

  /** Run one capture pass immediately (used by tests and the "copy" path wake-up). */
  async captureNow(): Promise<void> {
    await this.#tickSafely()
  }

  /** Current poll delay: fast while the user is active, slow once idle. */
  getIntervalMs(): number {
    return this.currentIntervalMs
  }

  #schedule(): void {
    const active = this.now().getTime() - this.lastActivityAt < ACTIVITY_WINDOW_MS
    this.currentIntervalMs = active ? FAST_INTERVAL_MS : SLOW_INTERVAL_MS
    this.timer = this.scheduleTimer(() => {
      // Fire-and-forget: a slow tick must not stall the timer chain, and the
      // in-flight flag drops the tick that lands while the previous one runs.
      void this.#tickSafely()
      if (this.running) this.#schedule()
    }, this.currentIntervalMs)
  }

  /** Run one tick at most at a time; failures are reported through `onError`. */
  async #tickSafely(): Promise<void> {
    if (this.inFlight) return
    this.inFlight = true
    try {
      await this.#tick()
    } catch (error) {
      this.onError?.(error)
    } finally {
      this.inFlight = false
    }
  }

  async #tick(): Promise<void> {
    if (this.ownWrites > 0) {
      this.ownWrites -= 1
      return
    }
    const settings = this.sink.getSettings()
    if (!settings.captureEnabled) return

    // Concealment is probed (and rejected) before any payload read so sensitive
    // content is never pulled into the main process at all.
    if (settings.hideSensitive && await this.#isConcealed()) return

    const types = await this.adapter.readTypes()

    // Text-first precedence is deliberate: a payload that carries text AND an
    // image representation (e.g. rich content) is captured as text, matching the
    // donor behaviour and avoiding storing the image rendition of a text copy.
    if (types.some(isTextFormat)) {
      const text = await this.adapter.readText()
      if (text.trim().length > 0) {
        if (!text.includes('\n') && !text.includes('\r') && IMAGE_FILENAME.test(text.trim())) return
        if (Buffer.byteLength(text, 'utf8') > MAX_TEXT_BYTES) return
        const hash = createHash('sha256').update(`text\u0000${text}`).digest('hex')
        if (hash !== this.textHash) {
          this.textHash = hash
          this.#capture({ kind: 'text', text })
        }
        this.#markActivity()
        return
      }
    }

    if (!settings.captureImages) return
    await this.#captureImage(types)
  }

  /** True when the pasteboard carries any of the Apple "do not keep" markers. */
  async #isConcealed(): Promise<boolean> {
    for (const format of Object.keys(CONCEALED_FORMATS)) {
      if (await this.adapter.hasRawFormat(format)) return true
    }
    return false
  }

  /**
   * The format list is only the cheap "is there an image here" probe; the actual
   * capture decision is content-driven. Text-free image pasteboards are read at
   * most once per IMAGE_POLL_INTERVAL_MS.
   */
  async #captureImage(types: string[]): Promise<void> {
    const hasGif = await this.adapter.hasRawFormat(GIF_FORMAT)
    const imageMimes = IMAGE_MIME_PRIORITY.filter(mime => types.includes(mime))
    if (!hasGif && imageMimes.length === 0 && !types.some(isImageFormat)) return
    const at = this.now().getTime()
    if (at - this.lastImagePollAt < IMAGE_POLL_INTERVAL_MS) return
    this.lastImagePollAt = at

    const entry = await this.#readImage(imageMimes, hasGif)
    if (!entry) return
    const hash = createHash('sha256').update(entry.imageBytes as Buffer).digest('hex')
    if (hash === this.lastImageHash) return
    // Only recorded after a successful capture, so a failed read/skip/store throw
    // is retried on a later tick instead of poisoning the gate forever.
    if (this.#capture(entry)) this.lastImageHash = hash
  }

  async #readImage(imageMimes: readonly string[], hasGif: boolean): Promise<ClipEntryInput | null> {
    if (hasGif) {
      const gif = await this.adapter.readTypeBytes(GIF_FORMAT)
      if (gif && gif.length > 0) return this.#buildImageEntry(gif, 'gif')
    }
    for (const mime of imageMimes) {
      const bytes = await this.adapter.readTypeBytes(mime)
      if (!bytes || bytes.length === 0) continue
      const format = MIME_IMAGE_FORMAT[mime]
      // webp/tiff have no first-class store format: skip rather than mislabel.
      if (!format) return null
      return this.#buildImageEntry(bytes, format)
    }
    return null
  }

  /** Attach decoded dimensions/thumbnail when possible; bounds are checked here. */
  async #buildImageEntry(bytes: Buffer, format: ClipImageFormat): Promise<ClipEntryInput | null> {
    if (bytes.length === 0 || bytes.length > MAX_IMAGE_BYTES) return null
    let preview: ClipboardImagePreview | null = null
    try {
      preview = await this.adapter.decodeImage(bytes)
    } catch (error) {
      this.onError?.(error)
    }
    // A GIF this build`s decoder cannot read is still worth storing: keep the raw
    // bytes and omit the preview instead of dropping the capture.
    if (!preview && format !== 'gif') return null
    return {
      kind: 'image',
      imageBytes: bytes,
      imageFormat: format,
      ...(preview ? { imageWidth: preview.width, imageHeight: preview.height, thumbnailPng: preview.thumbnailPng } : {}),
    }
  }

  /**
   * Re-probe the current clipboard and forget the cached fingerprints so the next
   * tick re-records content that is no longer in the store. Called after CLEAR /
   * DELETE emptied a row: without this the cache suppresses re-copying the same
   * content. Never inserts, pushes or writes to the store.
   */
  async resync(): Promise<void> {
    try {
      const types = await this.adapter.readTypes()
      if (types.some(isTextFormat) && (await this.adapter.readText()).trim().length > 0) {
        this.textHash = null
      } else if (types.some(isImageFormat)) {
        this.lastImageHash = null
      } else {
        this.textHash = null
        this.lastImageHash = null
      }
      this.lastImagePollAt = Number.NEGATIVE_INFINITY
    } catch (error) {
      this.onError?.(error)
    }
  }

  /** Insert through the sink; returns whether the entry reached the store. */
  #capture(entry: ClipEntryInput): boolean {
    try {
      const result = this.sink.insertOrResurface(entry)
      this.#markActivity()
      this.onChanged?.({ reason: result.inserted ? 'captured' : 'updated' })
      return true
    } catch (error) {
      if (error instanceof ClipEntryRejectedError) return false
      throw error
    }
  }

  #markActivity(): void {
    this.lastActivityAt = this.now().getTime()
  }
}