/**
 * W1-11 (#1508) — Identity lifecycle contract surface (`@rox/core/identity`).
 *
 * Not to be confused with `@rox/core/platform/identity` (the credential
 * broker), which this package does not touch.
 */

export {
  ACTIVATED_MEMBER_STATUS,
  CHAT_ADMIN_ROLES,
  HELD_NOTIFICATION_DIGEST_HOURS,
  HELD_NOTIFICATION_RULE,
  PENDING_ACTIVATION_CHAT_STATE,
  PLACEHOLDER_ALLOWED_ACTIONS,
  PLACEHOLDER_DENIED_ACTIONS,
  PLACEHOLDER_DORMANT_DAYS,
  PRINCIPAL_KINDS,
  PRINCIPAL_STATUSES,
  WORKSPACE_MEMBER_ROLES,
  WORKSPACE_MEMBER_STATUSES,
  isPrincipalKind,
  isPrincipalStatus,
  isWorkspaceAdmin,
  isWorkspaceMemberRole,
  isWorkspaceMemberStatus,
  membershipAfterActivation,
  placeholderCan,
  principalCanSignIn,
  type HeldNotificationRule,
  type PlaceholderAction,
  type Principal,
  type PrincipalKind,
  type PrincipalStatus,
  type WorkspaceMember,
  type WorkspaceMemberRole,
  type WorkspaceMemberStatus,
} from './principal.ts'

export {
  INVITATION_DAILY_LIMIT_PER_INVITER,
  INVITATION_REMINDER_DAYS,
  INVITATION_ROLES,
  INVITATION_STATUSES,
  INVITATION_TOKEN_ALGORITHM,
  INVITATION_TOKEN_BYTES,
  INVITATION_TTL_DAYS,
  dueInvitationReminder,
  invitationExpiry,
  invitationIsExpired,
  invitationPendingKey,
  inviteDomainAllowed,
  isInvitationRole,
  isInvitationStatus,
  normalizePrimaryEmail,
  type Invitation,
  type InvitationRole,
  type InvitationStatus,
  type InvitationTarget,
  type InviteDomainPolicy,
} from './invitation.ts'

export {
  AGENT_DISPLAY_NAME,
  AGENT_HANDLE_ROOT,
  AGENT_MENTION_PATTERN,
  agentCanJoinThread,
  agentDisplayHandle,
  agentDisplayName,
  agentMentionRef,
  parseAgentMention,
  parseAgentMentions,
  resolveAgentMention,
  type AgentHandleBinding,
  type ParsedAgentMention,
  type ResolveAgentMentionInput,
} from './handle.ts'

export {
  CHAT_CREATION_POLICIES,
  CHAT_INVITE_POLICIES,
  CHAT_MEMBER_PENDING_ACTIVATION,
  CHAT_POSTING_POLICIES,
  CHAT_VISIBILITIES,
  GENERAL_CHAT_FALLBACK_NAME,
  GENERAL_CHAT_INVARIANTS,
  GENERAL_CHAT_SYSTEM_ROLE,
  TEAM_CHAT_COMMANDS,
  TEAM_CHAT_KINDS,
  canCreateChat,
  canInviteToChat,
  canJoinChat,
  canPostToChat,
  canSetVisibility,
  chatJoinMode,
  generalChatDraft,
  isChatCreationPolicy,
  isChatVisibility,
  isGeneralChat,
  isTeamChatCommand,
  isTeamChatKind,
  type BrowsePublicChatsPayload,
  type ChatCreationPolicy,
  type ChatInvitePolicy,
  type ChatPostingPolicy,
  type ChatVisibility,
  type CreateChatPayload,
  type CreateChatPermission,
  type GeneralChatDraft,
  type JoinChatPayload,
  type LeaveChatPayload,
  type SetVisibilityPayload,
  type TeamChat,
  type TeamChatCommand,
  type TeamChatKind,
  type VisibilityChangePermission,
} from './team-chats.ts'

export {
  IDENTITY_COMMAND_TYPES,
  IDENTITY_EVENTS,
  PLACEHOLDER_MERGE_COLLECTIONS,
  generalChatInviteChatIds,
  inboxInviteCard,
  isIdentityCommandType,
  normalizeInviteEmails,
  planPlaceholder,
  planPlaceholderActivation,
  planPlaceholderMerge,
  type ActivatePlaceholderPayload,
  type ActivationStep,
  type ChatMembershipStep as LifecycleChatMembershipStep,
  type EnsurePlaceholderPayload,
  type IdentityCommandType,
  type IdentityEventType,
  type IdentityLifecycleRefusal,
  type InboxInviteCard,
  type InvitePeoplePayload,
  type LifecycleRefusal,
  type MergePlaceholderPayload,
  type MergeStep,
  type PlaceholderMergeCollection,
  type PlaceholderPlan,
} from './lifecycle.ts'