import { describe, expect, it } from 'bun:test'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const renderer = join(import.meta.dir, '../../..')
const read = (path: string) => readFileSync(join(renderer, path), 'utf8')

describe('continue-visual-3 leftover chrome', () => {
  it('routes notes empty, save, toolbar, and menu chrome through t()', () => {
    const notes = read('pages/NotesPage.tsx')
    expect(notes).toContain("t('notes.empty.selectWorkspace')")
    expect(notes).toContain("t('notes.empty.noNote')")
    expect(notes).toContain("t('notes.empty.noNoteHint')")
    expect(notes).toContain("t('notes.empty.loading')")
    expect(notes).toContain("t('notes.toolbar.previousDaily')")
    expect(notes).toContain("t('notes.toolbar.nextDaily')")
    expect(notes).toContain("t('notes.toolbar.attachAsset')")
    expect(notes).toContain("t('notes.toolbar.exportPdf')")
    expect(notes).toContain("t('notes.save.autosaveHint')")
    expect(notes).toContain("t('notes.menu.newInFolder')")
    expect(notes).toContain("t('notes.menu.reveal')")
    expect(notes).not.toContain('Select a workspace to use notes.')
    expect(notes).not.toContain('No note selected')
    expect(notes).not.toContain('Reveal in Finder')
    expect(notes).not.toContain('title="Previous daily note"')
    expect(notes).not.toContain('Save failed')
  })

  it('uses PremiumMenuSelect for connect-remote workspace picking', () => {
    const source = read('components/workspace/AddWorkspaceStep_ConnectRemote.tsx')
    expect(source).toContain('PremiumMenuSelect')
    expect(source).not.toContain('<Select')
    expect(source).not.toContain("from '../ui/select'")
  })

  it('replaces remaining playground native selects with PremiumMenuSelect', () => {
    const variants = read('playground/VariantsSidebar.tsx')
    const app = read('playground/PlaygroundApp.tsx')
    expect(variants).toContain('PremiumMenuSelect')
    expect(variants).not.toMatch(/<select[\s>]/)
    expect(app).toContain('PremiumMenuSelect')
    expect(app).not.toContain("from '@/components/ui/select'")
  })

  it('translates leftover slash, status, filter, and share chrome', () => {
    const slash = read('components/ui/slash-command-menu.tsx')
    const status = read('components/ui/session-status-menu.tsx')
    const filter = read('components/app-shell/CompactSessionListFilter.tsx')
    const chat = read('pages/ChatPage.tsx')
    const tiptap = readFileSync(join(renderer, '../../../../packages/ui/src/components/markdown/TiptapSlashMenu.ts'), 'utf8')
    expect(slash).toContain("t('commands.noCommands')")
    expect(slash).not.toContain('No commands found')
    expect(tiptap).toContain("i18n.t('commands.noCommands')")
    expect(tiptap).not.toContain('No commands found')
    expect(status).toContain("t('status.noneFound')")
    expect(status).not.toContain('No status found')
    expect(filter).toContain("t('sidebar.noMatches')")
    expect(filter).not.toContain('No matches')
    expect(chat).toContain("t('chat.shareSession')")
    expect(chat).toContain("t('chat.sharedSessionOptions')")
    expect(chat).not.toContain("'Share session'")
  })

  it('translates leftover server, table, picker, and notes slash chrome', () => {
    const server = read('pages/settings/ServerSettingsPage.tsx')
    const table = read('components/ui/data-table.tsx')
    const sources = read('components/ui/SourceSelectorPopover.tsx')
    const skills = read('components/ui/SkillSelectorPopover.tsx')
    const models = read('components/settings/SearchableModelInput.tsx')
    const tiptap = readFileSync(join(renderer, '../../../../packages/ui/src/components/markdown/TiptapSlashMenu.ts'), 'utf8')
    expect(server).toContain("t('settings.server.notConfigured')")
    expect(server).toContain("t('common.browse')")
    expect(server).toContain("t('common.reset')")
    expect(server).toContain("t('common.save')")
    expect(server).not.toContain("'Not configured'")
    expect(server).not.toContain('>Browse<')
    expect(table).toContain("t('common.noResults')")
    expect(table).toContain("t('common.previous')")
    expect(table).toContain("t('common.next')")
    expect(table).toContain("t('common.pageOf'")
    expect(table).not.toContain("'No results.'")
    expect(table).not.toContain('>Previous<')
    expect(sources).toContain("t('sourcesList.searchPlaceholder')")
    expect(sources).not.toContain('Search sources...')
    expect(skills).toContain("t('skillsList.searchPlaceholder')")
    expect(skills).not.toContain('Search skills...')
    expect(models).toContain("t('apiSetup.noModelsFound')")
    expect(models).not.toContain('No models found')
    expect(tiptap).toContain("slashTitle('notes.slash.heading1'")
    expect(tiptap).toContain("slashTitle('notes.slash.group.format'")
    expect(tiptap).not.toContain("title: 'Heading 1'")
    expect(tiptap).not.toContain("label.textContent = groupName")
  })
})
