/**
 * W1-15 (#1512) — Cross-functional capability contracts X-13…X-26
 * (TECH-SPEC §20). Named re-export blocks, mirroring `../entities/index.ts`.
 */

export {
  DROP_RULES,
  XFN_CAPABILITIES,
  XFN_CAPABILITIES_WORKBENCH_FLAG,
  XFN_COMMAND_NAMES,
  XFN_IDS,
  XFN_QUERY_NAMES,
  XFN_RISK_CLASSES,
  XFN_UI_COMMAND_NAMES,
  XfnFlagOffError,
  bindXfnContracts,
  bindXfnReferenceHandlers,
  commandAvailability,
  dropAvailability,
  dropPairKey,
  formActionIdempotencyKey,
  formResponseActionRisk,
  formResponsePlan,
  goalWorkRelation,
  isDropKind,
  localActorRef,
  maxRiskClass,
  parseDropRef,
  registryRiskResolver,
  resolveDrop,
  resolveDropMany,
  setXfnRiskResolver,
  unboundXfnCommands,
  xfnAvailability,
  xfnCapability,
  xfnCapabilityForCommand,
  xfnReferenceHandlers,
  type BindXfnOptions,
  type DropDispatchResult,
  type DropResolution,
  type DropRule,
  type XfnAvailability,
  type XfnBindingReport,
  type XfnCapability,
  type XfnCapabilityReason,
  type XfnId,
  type XfnReferenceHandlersOptions,
  type XfnRiskContext,
  type XfnRiskResolver,
} from './commands.ts'

export {
  EMPTY_LOCAL_PINS_STATE,
  LINK_VISIBILITY_RULES,
  LOCAL_PINS_VERSION,
  PIN_EXCLUDED_SURFACES,
  PIN_PRIVATE_RULE,
  PIN_PRIVATE_RULE_ID,
  PIN_RELATION,
  PIN_ROLE,
  filterLinksForViewer,
  isPinLink,
  linkAllowedOnSurface,
  pinAnchorsForOrder,
  pinLinkVisibleTo,
  pinPrivateAllows,
  recordLocalPins,
  registerLinkVisibilityRule,
  sortPins,
  withLocalPin,
  withoutLocalPin,
  type LinkVisibilityInput,
  type LinkVisibilityRule,
  type LocalPinRecord,
  type LocalPinsState,
  type PinAnchor,
  type PinExcludedSurface,
  type PinLink,
} from '../acl/rules/pin-private.ts'

export {
  REMINDER_DUE_CHANNELS,
  REMINDER_DUE_KIND,
  REMINDER_NOTIFICATION_KINDS,
  REMINDER_SCHEMA_VERSION,
  dueReminders,
  isPendingReminder,
  reminderDueNotification,
  reminderSubjectKey,
  type ReminderRecord,
} from './reminder.ts'

export {
  createXfnPorts,
  visiblePins,
  type CreateXfnPortsOptions,
  type XfnActor,
  type XfnPorts,
} from './ports.ts'