import {afterAll,beforeAll,describe,expect,it} from 'bun:test'
import {existsSync} from 'node:fs'
import {resolve} from 'node:path'
import {chromium,expect as playwrightExpect,type Browser,type Page} from 'playwright/test'
const repository=resolve(import.meta.dirname,'../../../../../..'),fixture=resolve(import.meta.dirname,'fixtures/connections-lifecycle')
const executablePath=process.env.CHROMIUM_EXECUTABLE??chromium.executablePath(),endpoint='http://127.0.0.1:5239'
const caseTimeout=Math.min(120000,Math.max(30000,Number(process.env.ROX_CONNECTION_BROWSER_TIMEOUT_MS)||30000))
const expectDOM=playwrightExpect.configure({timeout:15000})
const panel=(page:Page)=>page.getByTestId('connections-page').getByTestId('connection-lifecycle')
const calls=(page:Page,method:string)=>page.evaluate(method=>(window as any).__connectionFixture.calls.filter((call:any)=>call.method===method),method)
const configure=(page:Page,options:any)=>page.evaluate(options=>(window as any).__connectionFixture.configure(options),options)
const select=async(page:Page,index=0)=>{await page.getByTestId('connections-row').nth(index).click();await expectDOM(panel(page)).toHaveAttribute('data-connection-id',index?'c2':'c1')}
const imports=async(page:Page)=>{await page.getByRole('tab',{name:'Imports',exact:true}).click();await page.getByTestId('connections-source-chip').filter({hasText:'github-oauth'}).click()}

describe.skipIf(!existsSync(executablePath))('production connection page and inspector lifecycle',()=>{
 let server:ReturnType<typeof Bun.spawn>|undefined,browser:Browser
 const stop=async()=>{server?.kill('SIGKILL');await browser?.close();await server?.exited}
 beforeAll(async()=>{try{server=Bun.spawn(['node',resolve(repository,'node_modules/vite/bin/vite.js'),'--config',resolve(fixture,'vite.config.ts'),'--port','5239'],{cwd:repository,stdout:'ignore',stderr:'ignore'});const deadline=Date.now()+30000;for(;;){if(server.exitCode!==null)throw Error('Connections fixture exited');try{const response=await fetch(endpoint);if(response.ok){if(!(await response.text()).includes('rox-connections-lifecycle-fixture'))throw Error('Foreign owner occupies fixture port');break}}catch(error){if(error instanceof Error&&error.message.includes('Foreign owner'))throw error}if(Date.now()>deadline)throw Error('Connections fixture startup timeout');await Bun.sleep(100)}browser=await chromium.launch({executablePath,headless:true,args:['--no-sandbox']})}catch(error){await stop();throw error}},45000)
 afterAll(stop,caseTimeout)
 const withPage=async(run:(page:Page)=>Promise<void>)=>{const context=await browser.newContext({viewport:{width:1500,height:1100},reducedMotion:'reduce'}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));try{await page.goto(endpoint);await expectDOM(page.getByTestId('connections-row')).toHaveCount(2);await run(page);expect(errors).toEqual([]);expect(await page.locator('body').innerText()).not.toContain('PRIVATE_DO_NOT_RENDER')}catch(error){throw Error('Production connections fixture failed; pageErrors='+JSON.stringify(errors)+'; body='+await page.locator('body').innerText(),{cause:error})}finally{await context.close()}}
 it('reveals real inspect metadata in both consumers and confirms actual leases before reconnect',async()=>withPage(async page=>{
  await select(page);await expectDOM(panel(page)).toContainText('fingerprint-c1');await expectDOM(page.getByTestId('connection-inspector')).toContainText('version-c1');
  await panel(page).getByRole('button',{name:'Reconnect',exact:true}).click();await expectDOM(panel(page).getByTestId('connection-lifecycle-confirm')).toContainText('lease-1 consumer-1 view github.api');expect((await calls(page,'Reconnect')).length).toBe(0);
  await panel(page).getByRole('button',{name:'Confirm reconnect',exact:true}).click();await expectDOM(panel(page)).toContainText('reconnected');await expectDOM(panel(page)).toContainText('consumer-1: revoked');expect((await calls(page,'Reconnect')).map((row:any)=>row.input)).toEqual([{workspaceId:'workspace-a',connectionId:'c1'}]);
 }),caseTimeout)
 it('keeps move failure explicit and retryable, and preserves existing test, repair and rotate controls',async()=>withPage(async page=>{
  await select(page);await expectDOM(panel(page)).toContainText('version-c1');await panel(page).getByRole('button',{name:'Test',exact:true}).click();await expectDOM(panel(page)).toContainText('fixture-user');await panel(page).getByRole('button',{name:'Repair',exact:true}).click();await expectDOM(panel(page)).toContainText('consumer-1: repaired');await panel(page).getByRole('button',{name:'Rotate',exact:true}).click();await panel(page).getByRole('button',{name:'Confirm rotate',exact:true}).click();await expectDOM(panel(page)).toContainText('consumer-1: rotated');
  await configure(page,{rejectMove:true});await panel(page).getByRole('button',{name:'Move backend',exact:true}).click();await expectDOM(panel(page).getByRole('combobox')).toHaveValue('local-alt');await panel(page).getByRole('button',{name:'Confirm move',exact:true}).click();await expectDOM(panel(page).getByRole('alert')).toBeVisible();await expectDOM(panel(page)).toContainText('version-c1');
  await configure(page,{rejectMove:false});await panel(page).getByRole('button',{name:'Confirm move',exact:true}).click();await expectDOM(panel(page)).toContainText('moved');expect((await calls(page,'Move')).every((row:any)=>row.input.targetBackend==='local-alt')).toBe(true);
 }),caseTimeout)
 it('coalesces confirmed writes and fences an old workspace receipt through A → B → A',async()=>withPage(async page=>{
  await select(page);await panel(page).getByRole('button',{name:'Reconnect',exact:true}).click();await configure(page,{deferReconnect:true});await panel(page).getByRole('button',{name:'Confirm reconnect',exact:true}).evaluate(button=>{(button as HTMLButtonElement).click();(button as HTMLButtonElement).click()});await expectDOM.poll(async()=>(await calls(page,'Reconnect')).length).toBe(1);
  await page.getByRole('button',{name:'Switch workspace'}).click();await expectDOM(page.getByTestId('connections-row')).toHaveCount(2);await page.getByRole('button',{name:'Switch workspace'}).click();await select(page);await expectDOM(panel(page)).toContainText('version-c1');
  await page.evaluate(()=>{const f=(window as any).__connectionFixture,index=f.deferred.findIndex((item:any)=>item.method==='Reconnect');f.settle(index,{consumers:[],leases:[],inspect:{...f.inspection('c1'),versionId:'OBSOLETE_RECEIPT'}})});await expectDOM(panel(page)).toContainText('version-c1');expect(await page.locator('body').innerText()).not.toContain('OBSOLETE_RECEIPT');
 }),caseTimeout)
 it('rejects foreign and secret inspect receipts while latest selection owns both consumers',async()=>withPage(async page=>{
  await configure(page,{deferInspect:true});await select(page);await select(page,1);await page.evaluate(()=>{const f=(window as any).__connectionFixture;f.deferred.forEach((item:any,index:number)=>{if(item.method==='Inspect')f.settle(index,item.input.connectionId==='c1'?{...f.inspection('c1'),versionId:'OBSOLETE_INSPECT'}:f.inspection('c2'))})});await expectDOM(panel(page)).toContainText('version-c2');await expectDOM(page.getByTestId('connection-inspector')).toContainText('version-c2');expect(await page.locator('body').innerText()).not.toContain('OBSOLETE_INSPECT');
  await configure(page,{deferInspect:false,foreignInspect:true});await panel(page).getByRole('button',{name:'Refresh',exact:true}).click();await expectDOM(panel(page).getByRole('alert')).toBeVisible();await expectDOM(panel(page)).not.toContainText('fingerprint-c1');await configure(page,{foreignInspect:false,inspectSecret:true});await panel(page).getByRole('button',{name:'Refresh',exact:true}).click();await expectDOM(panel(page).getByRole('alert')).toBeVisible();await expectDOM(panel(page)).not.toContainText('PRIVATE_DO_NOT_RENDER');
 }),caseTimeout)
 it('cancels late starts, refuses unsafe URLs and secret replies, and cleans a replacement flow on unmount',async()=>withPage(async page=>{
  await imports(page);const oauth=page.getByTestId('github-device-login');await configure(page,{deferStart:true});await oauth.getByRole('button',{name:'Start GitHub device login'}).evaluate(button=>{(button as HTMLButtonElement).click();(button as HTMLButtonElement).click()});expect((await calls(page,'Start')).length).toBe(1);await oauth.getByRole('button',{name:'Cancel GitHub login'}).click();await page.evaluate(()=>{const f=(window as any).__connectionFixture,index=f.deferred.findIndex((item:any)=>item.method==='Start');f.settle(index,{flowId:'late-start',userCode:'ABCD',verificationUri:'https://github.com/login/device',interval:1})});await expectDOM.poll(async()=>(await calls(page,'Cancel')).some((row:any)=>row.input.flowId==='late-start')).toBe(true);await expectDOM(page.getByTestId('github-device-code')).toHaveCount(0);
  await configure(page,{deferStart:false,badUri:true});await oauth.getByRole('button',{name:'Start GitHub device login'}).click();await expectDOM(oauth.getByRole('alert')).toBeVisible();await expectDOM(oauth.getByRole('link')).toHaveCount(0);
  await configure(page,{badUri:false,startSecret:true});await oauth.getByRole('button',{name:'Start GitHub device login'}).click();await expectDOM(oauth.getByRole('alert')).toBeVisible();await expectDOM(page.getByTestId('github-device-code')).toHaveCount(0);
  await configure(page,{startSecret:false});await oauth.getByRole('button',{name:'Start GitHub device login'}).click();await expectDOM(oauth.getByRole('link')).toHaveAttribute('href','https://github.com/login/device?user_code=ABCD-EFGH');const last=(await calls(page,'Start')).length;await page.getByRole('button',{name:'Toggle consumers'}).click();await expectDOM.poll(async()=>(await calls(page,'Cancel')).some((row:any)=>row.input.flowId==='flow-'+last)).toBe(true);
 }),caseTimeout)
 it('owns one poll at a time, honors slow_down and refreshes metadata only for a current import',async()=>withPage(async page=>{
  await imports(page);await configure(page,{deferPoll:true});const oauth=page.getByTestId('github-device-login');await oauth.getByRole('button',{name:'Start GitHub device login'}).click();await expectDOM.poll(async()=>(await calls(page,'Poll')).length).toBe(1);await oauth.getByRole('button',{name:'Check GitHub login'}).evaluate(button=>{(button as HTMLButtonElement).click();(button as HTMLButtonElement).click()});expect((await calls(page,'Poll')).length).toBe(1);
  await page.evaluate(()=>{const f=(window as any).__connectionFixture,index=f.deferred.findIndex((item:any)=>item.method==='Poll');f.slowDownSettledAt=Date.now();f.settle(index,{status:'slow_down',interval:2})});await expectDOM(oauth.getByRole('status')).toHaveText('Slow down GitHub polling');await configure(page,{deferPoll:false,pollResult:{status:'imported',connectionId:'c1'}});await expectDOM(oauth.getByRole('status')).toHaveText('GitHub connection imported');await expectDOM.poll(async()=>(await calls(page,'List')).length).toBe(2);expect((await calls(page,'Poll')).every((row:any)=>row.input.workspaceId==='workspace-a')).toBe(true);const slowDownAt=await page.evaluate(()=>(window as any).__connectionFixture.slowDownSettledAt);expect((await calls(page,'Poll'))[1].at-slowDownAt).toBeGreaterThanOrEqual(2000);
 }),caseTimeout)
 it('does not import an obsolete poll after A → B → A and makes denial and expiry retryable',async()=>withPage(async page=>{
  await imports(page);await configure(page,{deferPoll:true});const oauth=page.getByTestId('github-device-login');await oauth.getByRole('button',{name:'Start GitHub device login'}).click();await expectDOM.poll(async()=>(await calls(page,'Poll')).length).toBe(1);
  await page.getByRole('button',{name:'Switch workspace'}).click();await page.getByRole('button',{name:'Switch workspace'}).click();await oauth.getByRole('button',{name:'Start GitHub device login'}).click();await expectDOM(page.getByTestId('github-device-code')).toBeVisible();await expectDOM.poll(async()=>(await calls(page,'List')).length).toBe(3);const before=(await calls(page,'List')).length;
  await page.evaluate(()=>{const f=(window as any).__connectionFixture,index=f.deferred.findIndex((item:any)=>item.method==='Poll');f.settle(index,{status:'imported',connectionId:'c1'})});await expectDOM(page.getByTestId('github-device-code')).toBeVisible();expect((await calls(page,'List')).length).toBe(before);
  await expectDOM.poll(async()=>(await calls(page,'Poll')).length).toBe(2);await page.evaluate(()=>{const f=(window as any).__connectionFixture,index=f.deferred.findLastIndex((item:any)=>item.method==='Poll');f.settle(index,{status:'denied'})});await expectDOM(oauth.getByRole('status')).toHaveText('GitHub login denied');await expectDOM(page.getByTestId('github-device-code')).toHaveCount(0);
  await configure(page,{deferPoll:false,pollResult:{status:'expired'}});await oauth.getByRole('button',{name:'Start GitHub device login'}).click();await expectDOM(oauth.getByRole('status')).toHaveText('GitHub login expired');await expectDOM(oauth.getByRole('button',{name:'Start GitHub device login'})).toBeEnabled();
 }),caseTimeout)
})
