import type { Rox2GapRow, Rox2ScreenRecord, Rox2ServiceRecord } from './schema.ts'

/** Rail destinations from APP_NAV_DESTINATIONS. Evidence: static source. */
export const ROX2_SCREENS: readonly Rox2ScreenRecord[] = [
  {
    id: 'sessions',
    title: 'Sessions collection + chat',
    files: [
      'apps/electron/src/renderer/components/app-shell/nav-destinations.ts',
      'apps/electron/src/renderer/pages/ChatPage.tsx',
    ],
    evidence: 'statically-confirmed',
    coverage: 'Native session list and ChatPage. Right inspector is partial.',
  },
  {
    id: 'projects',
    title: 'Projects',
    files: [
      'apps/electron/src/renderer/pages/ProjectInfoPage.tsx',
      'packages/server-core/src/handlers/rpc/projects.ts',
    ],
    evidence: 'statically-confirmed',
    coverage: 'Native project info. No Conation GraphqlSoupProject actions.',
  },
  {
    id: 'pages',
    title: 'Pages / canvas',
    files: ['packages/server-core/src/handlers/rpc/pages.ts'],
    evidence: 'statically-confirmed',
    coverage: 'Pages RPC exists. Interactive canvas is still gated.',
  },
  {
    id: 'memory',
    title: 'Memory',
    files: [
      'packages/server-core/src/handlers/rpc/memory.ts',
      'packages/server-core/src/handlers/rpc/memory-proposals.ts',
    ],
    evidence: 'statically-confirmed',
    coverage: 'Memory RPC + proposals. Candidate auto-create is incomplete.',
  },
  {
    id: 'tasks',
    title: 'Tasks / kanban',
    files: [
      'apps/electron/src/renderer/pages/TasksPage.tsx',
      'packages/server-core/src/handlers/rpc/tasks.ts',
      'packages/server-core/src/handlers/rpc/kanban.ts',
    ],
    evidence: 'statically-confirmed',
    coverage: 'Native tasks/kanban. Conation Board is a deep link, not a second board.',
  },
  {
    id: 'sources',
    title: 'Sources',
    files: [
      'apps/electron/src/renderer/pages/SourceInfoPage.tsx',
      'packages/server-core/src/handlers/rpc/sources.ts',
    ],
    evidence: 'statically-confirmed',
    coverage: 'Native MCP/source list.',
  },
  {
    id: 'skills',
    title: 'Skills',
    files: [
      'apps/electron/src/renderer/pages/SkillInfoPage.tsx',
      'packages/server-core/src/handlers/rpc/skills.ts',
    ],
    evidence: 'statically-confirmed',
    coverage: 'Native skills. Conation surfaces skill flag is off and unregistered.',
  },
  {
    id: 'notes',
    title: 'Notes / knowledge',
    files: [
      'apps/electron/src/renderer/pages/NotesPage.tsx',
      'apps/electron/src/renderer/pages/KnowledgeSurfacePage.tsx',
      'packages/server-core/src/handlers/rpc/notes.ts',
      'packages/core/src/knowledge/providers/siyuan/adapter.ts',
    ],
    evidence: 'statically-confirmed',
    coverage: 'Native Notes exist. Knowledge still has a SiYuan provider path. Conation Notes is read-only.',
  },
  {
    id: 'automations',
    title: 'Automations / workflows',
    files: [
      'apps/electron/src/renderer/components/automations/AutomationGraphEditor.tsx',
      'packages/server-core/src/handlers/rpc/automations.ts',
    ],
    evidence: 'statically-confirmed',
    coverage: 'Graph editor exists. Verifiable workflow candidates are not auto-created.',
  },
  {
    id: 'connections',
    title: 'Connections',
    files: [
      'apps/electron/src/renderer/pages/ConnectionsPage.tsx',
      'packages/server-core/src/handlers/rpc/fabric.ts',
    ],
    evidence: 'statically-confirmed',
    coverage: 'Connection fabric UI. Drive/Mail/CRM are not first-class native entities.',
  },
  {
    id: 'settings',
    title: 'Settings hub',
    files: [
      'apps/electron/src/shared/settings-registry.ts',
      'apps/electron/src/renderer/pages/settings/SettingsNavigator.tsx',
    ],
    evidence: 'statically-confirmed',
    coverage: '22 registered settings pages. Conation toggles live under Appearance.',
  },
  {
    id: 'browser',
    title: 'Embedded browser',
    files: [
      'apps/electron/src/renderer/pages/BrowserPanelPage.tsx',
      'apps/electron/src/renderer/components/browser/WebBrowserPanel.tsx',
    ],
    evidence: 'statically-confirmed',
    coverage: 'Native browser pane. Not a Conation iframe.',
  },
  {
    id: 'playground',
    title: 'Playground',
    files: ['apps/electron/src/renderer/playground/registry/types.ts'],
    evidence: 'statically-confirmed',
    coverage: 'Fixture gallery. Must stay labeled fixture, never live.',
  },
  {
    id: 'webui',
    title: 'Web UI',
    files: ['apps/webui/src/App.tsx'],
    evidence: 'statically-confirmed',
    coverage: 'Web client. Parity with desktop is incomplete.',
  },
  {
    id: 'viewer',
    title: 'Viewer share',
    files: ['apps/viewer/src/App.tsx'],
    evidence: 'statically-confirmed',
    coverage: 'Share viewer. Residual hardening is a follow-up.',
  },
  {
    id: 'conation-inspector',
    title: 'Conation inspector host',
    files: [
      'apps/electron/src/renderer/platform/conation/ConationInspectorPanel.tsx',
      'packages/core/src/conation/shell/flags.ts',
    ],
    evidence: 'statically-confirmed',
    coverage: 'Empty inspector contribution, flags default off.',
  },
  {
    id: 'conation-board',
    title: 'Conation Board pane',
    files: [
      'apps/electron/src/renderer/platform/conation/ConationBoardPanel.tsx',
      'apps/electron/src/renderer/platform/conation/conation-board-panels.ts',
    ],
    evidence: 'statically-confirmed',
    coverage: 'Deep link to Conation Board. No second in-app kanban.',
  },
  {
    id: 'conation-fund',
    title: 'Conation Fund pane',
    files: [
      'apps/electron/src/renderer/platform/conation/ConationFundPanel.tsx',
      'apps/electron/src/renderer/platform/conation/conation-fund-panels.ts',
    ],
    evidence: 'statically-confirmed',
    coverage: 'Deep link to Fund canvas. In-app interactive canvas gated.',
  },
  {
    id: 'conation-notes',
    title: 'Conation Notes pane',
    files: [
      'apps/electron/src/renderer/platform/conation/ConationNotesPanel.tsx',
      'packages/core/src/conation/notes/bridge.ts',
    ],
    evidence: 'statically-confirmed',
    coverage: 'Read-only Soup document bridge. Writes omitted.',
  },
  {
    id: 'voice-overlay',
    title: 'Voice overlay',
    files: ['apps/electron/src/renderer/voice-overlay.tsx'],
    evidence: 'statically-confirmed',
    coverage: 'Voice overlay host. Independent of Conation.',
  },
]

export const ROX2_SERVICES: readonly Rox2ServiceRecord[] = [
  {
    id: 'rpc-server-core',
    title: 'server-core RPC handlers',
    files: ['packages/server-core/src/handlers/rpc/index.ts'],
    evidence: 'statically-confirmed',
    coverage: 'Canonical RPC surface. Results are not yet Rox2Result-typed.',
  },
  {
    id: 'conation-soup',
    title: 'Conation Soup GraphQL client',
    files: ['packages/core/src/conation/soup/client.ts'],
    evidence: 'documented',
    coverage: 'Read-only. Writes (CompleteMutationRoot) omitted.',
  },
  {
    id: 'conation-dss',
    title: 'Conation DSS / Drive client',
    files: ['packages/core/src/conation/dss/client.ts'],
    evidence: 'documented',
    coverage: 'Read-only HTTP. Writes and FileProvider omitted.',
  },
  {
    id: 'knowledge-siyuan',
    title: 'SiYuan knowledge provider',
    files: ['packages/core/src/knowledge/providers/siyuan/adapter.ts'],
    evidence: 'statically-confirmed',
    coverage: 'Runtime dependency still present. Native Notes should not require it.',
  },
  {
    id: 'knowledge-inmemory',
    title: 'In-memory knowledge provider',
    files: ['packages/core/src/knowledge/providers/inmemory.ts'],
    evidence: 'statically-confirmed',
    coverage: 'Test/fixture provider. Not a production vault.',
  },
  {
    id: 'calendar',
    title: 'Calendar core',
    files: ['packages/core/src/calendar/index.ts'],
    evidence: 'statically-confirmed',
    coverage: 'Typed calendar package exists. Soup calendar events are not merged.',
  },
  {
    id: 'tasks-personal',
    title: 'Personal tasks',
    files: ['packages/core/src/tasks/personal/index.ts'],
    evidence: 'statically-confirmed',
    coverage: 'Native task model. Not bound to Conation Board.',
  },
  {
    id: 'mindmap',
    title: 'Mindmap / canvas engine',
    files: ['packages/core/src/mindmap/types.ts'],
    evidence: 'statically-confirmed',
    coverage: 'Entity refs exist. Not a full Fund replacement.',
  },
  {
    id: 'identity',
    title: 'Identity / grants',
    files: ['packages/core/src/platform/identity/grants.ts'],
    evidence: 'statically-confirmed',
    coverage: 'Grants exist. Sensitive-action mapping to Rox2Permission is new.',
  },
  {
    id: 'session-apply',
    title: 'SessionApply stub',
    files: ['packages/core/src/platform/session-apply/client.ts'],
    evidence: 'statically-confirmed',
    coverage: 'Flag-gated stub linked to AgentTeamsStore. Not Cordis.',
  },
  {
    id: 'omp-agent',
    title: 'OMP agent backend',
    files: ['packages/shared/src/agent/omp-agent.ts'],
    evidence: 'documented',
    coverage: 'Primary agent runtime. Out of ROX2 data-plane except as actor on events.',
  },
  {
    id: 'electron-transport',
    title: 'Electron transport',
    files: ['apps/electron/src/transport/index.ts'],
    evidence: 'statically-confirmed',
    coverage: 'Shared owner file. Parallel ROX2 waves must not race edits here.',
  },
]

export const ROX2_CONATION_GAPS: readonly Rox2GapRow[] = [
  {
    id: 'GraphqlSoupDocument',
    asIs: 'Read-only Notes bridge filters Soup documents. Native NotesPage uses a separate store.',
    toBe: 'Document actions (open/edit) go through native Notes + Rox2Result. Conation is a source adapter, not an iframe.',
    files: ['packages/core/src/conation/notes/bridge.ts', 'apps/electron/src/renderer/pages/NotesPage.tsx'],
    integration: 'read-client',
    evidence: 'statically-confirmed',
  },
  {
    id: 'GraphqlSoupChat',
    asIs: 'Soup chat type exists on the GraphQL contract. Rox sessions are native transcripts.',
    toBe: 'Do not dual-write chats. Map Conation chat ids as relations onto native sessions when a user links them.',
    files: ['packages/core/src/conation/soup/types.ts', 'apps/electron/src/renderer/pages/ChatPage.tsx'],
    integration: 'none',
    evidence: 'documented',
  },
  {
    id: 'GraphqlSoupProject',
    asIs: 'Soup project type exists. Rox ProjectInfoPage is a separate native model.',
    toBe: 'Project list/read from Soup is an adapter behind native projects RPC.',
    files: ['packages/core/src/conation/soup/types.ts', 'apps/electron/src/renderer/pages/ProjectInfoPage.tsx'],
    integration: 'none',
    evidence: 'documented',
  },
  {
    id: 'GraphqlSoupEmailThread',
    asIs: 'No native Mail surface. Mail is not a first-class entity in Rox UI.',
    toBe: 'Native mail-thread entity + list/read actions with cloud-send permission. No iframe.',
    files: ['packages/core/src/conation/soup/types.ts'],
    integration: 'none',
    evidence: 'new-requirement',
  },
  {
    id: 'GraphqlSoupChannel',
    asIs: 'Soup channel type exists. Messaging settings are Rox-native, not Conation channels.',
    toBe: 'Channel entities in the unified model; posting requires permission.',
    files: ['packages/core/src/conation/soup/types.ts', 'apps/electron/src/renderer/pages/settings/MessagingSettingsPage.tsx'],
    integration: 'none',
    evidence: 'documented',
  },
  {
    id: 'GraphqlSoupChannelMessage',
    asIs: 'Type-only on Soup contract.',
    toBe: 'Messages are events on a channel entity, not a second inbox UI.',
    files: ['packages/core/src/conation/soup/types.ts'],
    integration: 'none',
    evidence: 'documented',
  },
  {
    id: 'GraphqlSoupCall',
    asIs: 'Type-only. No Rox call surface.',
    toBe: 'Optional call entity in the model. Do not ship a fake in-app dialer.',
    files: ['packages/core/src/conation/soup/types.ts'],
    integration: 'none',
    evidence: 'new-requirement',
  },
  {
    id: 'GraphqlSoupCalendarEvent',
    asIs: 'Calendar package is native. Soup events are not merged into it.',
    toBe: 'Merge adapters into packages/core/src/calendar without replacing native store.',
    files: ['packages/core/src/calendar/index.ts', 'packages/core/src/conation/soup/types.ts'],
    integration: 'none',
    evidence: 'statically-confirmed',
  },
  {
    id: 'GraphqlSoupCrmCompany',
    asIs: 'No native CRM surface.',
    toBe: 'CRM company as a native entity list (entity-list), actions behind permission.',
    files: ['packages/core/src/conation/soup/types.ts'],
    integration: 'none',
    evidence: 'new-requirement',
  },
  {
    id: 'GraphqlSoupForeignEntity',
    asIs: 'Opaque foreign entity on Soup. Rox sources are MCP/connections.',
    toBe: 'Map foreign entities onto source/connection refs; do not invent a third catalog.',
    files: ['packages/core/src/conation/soup/types.ts', 'apps/electron/src/renderer/pages/SourceInfoPage.tsx'],
    integration: 'none',
    evidence: 'documented',
  },
  {
    id: 'GraphqlSoupReminder',
    asIs: 'Type-only. Native reminders are incomplete.',
    toBe: 'Reminder entity + calendar relation. Creating one is a live write with permission.',
    files: ['packages/core/src/conation/soup/types.ts'],
    integration: 'none',
    evidence: 'new-requirement',
  },
  {
    id: 'dss-drive',
    asIs: 'Read-only DSS client. Flags default off. No native Drive browser.',
    toBe: 'File entities from DSS list/read. Writes and FileProvider stay blocked until signing exists.',
    files: ['packages/core/src/conation/dss/client.ts', 'packages/core/src/conation/dss/types.ts'],
    integration: 'read-client',
    evidence: 'documented',
  },
  {
    id: 'board-deeplink',
    asIs: 'ConationBoardPanel opens Conation via deep link. Copy says there is no second kanban.',
    toBe: 'Keep a single native KanbanBoard. Conation Board is a source of task entities, not a pane iframe.',
    files: [
      'apps/electron/src/renderer/platform/conation/ConationBoardPanel.tsx',
      'apps/electron/src/renderer/components/app-shell/kanban/KanbanBoard.tsx',
    ],
    integration: 'deep-link',
    evidence: 'statically-confirmed',
  },
  {
    id: 'fund-deeplink',
    asIs: 'Fund pane is a deep link. Interactive canvas disabled pending perf proof.',
    toBe: 'Native mindmap/pages remain the canvas. Fund is an adapter or stays a documented external open.',
    files: [
      'apps/electron/src/renderer/platform/conation/ConationFundPanel.tsx',
      'packages/core/src/mindmap/types.ts',
    ],
    integration: 'deep-link',
    evidence: 'statically-confirmed',
  },
  {
    id: 'shell-flags',
    asIs: 'workbench.conation.* flags default false. Visibility is not background sync.',
    toBe: 'Keep defaults off for network clients. Native entity features stay available without Conation.',
    files: ['packages/core/src/conation/shell/flags.ts', 'apps/electron/src/renderer/pages/settings/ConationShellSettings.tsx'],
    integration: 'flag-off',
    evidence: 'statically-confirmed',
  },
]
