import { test, expect } from '@playwright/test'

const server = 'http://127.0.0.1:4177'

for (const theme of ['light', 'dark'] as const) test(`grouped context is read-only and preserves root/child provenance in ${theme}`, async ({ page, request }, info) => {
  expect((await request.post(`${server}/reset`, { data: {} })).ok()).toBe(true)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto(`/?theme=${theme}`, { waitUntil: 'domcontentloaded' })
  if (theme === 'dark') await expect(page.locator('html')).toHaveClass(/\bdark\b/)
  else await expect(page.locator('html')).not.toHaveClass(/\bdark\b/)
  await page.getByTestId('start-run').click()
  await expect(page.getByTestId('received-count')).toHaveText('2')
  const fixtureResponse = await request.post(`${server}/context-fixture`, { data: {} })
  expect(fixtureResponse.ok()).toBe(true)
  const fixture = await fixtureResponse.json()
  const before = await (await request.get(`${server}/stats`)).json()
  await page.getByTestId('toggle-map').click()
  await page.getByRole('tab', { name: 'Контекст', exact: true }).click()
  const canvas = page.getByTestId('runtime-context-canvas')
  await expect(canvas).toBeVisible()
  const instructions = canvas.locator('[data-testid="runtime-context-group"][data-context-group="instructions"]')
  const instructionRows = instructions.getByTestId('runtime-context-row')
  await expect(instructionRows).toHaveCount(4)
  const header = instructions.getByRole('button').first()
  await expect(header).toHaveAttribute('aria-expanded', 'true')
  await expect(header).toContainText('6')
  await instructions.getByRole('button', { name: 'Ещё 2', exact: true }).click()
  await expect(instructionRows).toHaveCount(6)
  const sourceIds = await instructionRows.evaluateAll(rows => rows.map(row => row.getAttribute('data-source-event-id')))
  expect(sourceIds.every(Boolean)).toBe(true)
  await header.click()
  await expect(header).toHaveAttribute('aria-expanded', 'false')
  await expect(instructionRows).toHaveCount(0)
  await header.click()
  await expect(instructionRows).toHaveCount(6)
  expect(await instructionRows.evaluateAll(rows => rows.map(row => row.getAttribute('data-source-event-id')))).toEqual(sourceIds)
  const context = canvas.locator('[data-testid="runtime-context-group"][data-context-group="context"]')
  const rootSource = context.getByTestId('runtime-context-row').filter({ hasText: 'Root source 1' }).first()
  await expect(rootSource).toHaveAttribute('data-source-agent-id', 'root')
  await expect(rootSource).toHaveAttribute('data-context-snapshot-id', fixture.rootSnapshotId)
  expect(await rootSource.getAttribute('data-source-node-id')).toBeTruthy()
  await rootSource.click()
  const rootBlock = page.getByTestId('runtime-inspector').locator('details.runtime-context-block').filter({ hasText: 'Root source 1' })
  await rootBlock.locator('summary').click()
  await expect(rootBlock.getByText('ROOT_SOURCE_1', { exact: true })).toBeVisible()
  await expect(rootBlock).toContainText('fixture-v1')
  await expect(rootBlock).toContainText('explicit-root-context-fixture')
  await page.screenshot({ path: info.outputPath(`context-root-${theme}.png`), fullPage: true })
  const agent = page.getByRole('combobox', { name: 'Контекст агента', exact: true })
  await agent.selectOption(fixture.agents.child)
  await expect(canvas.locator(`[data-context-snapshot-id="${fixture.rootSnapshotId}"]`)).toHaveCount(0)
  await expect(canvas).toContainText('fixture/child')
  await expect(canvas).not.toContainText('fixture/root')
  const childSource = canvas.getByTestId('runtime-context-row').filter({ hasText: 'Child source 1' }).first()
  await expect(childSource).toHaveAttribute('data-source-agent-id', fixture.agents.child)
  await expect(childSource).toHaveAttribute('data-context-snapshot-id', fixture.childSnapshotId)
  await childSource.click()
  const childBlock = page.getByTestId('runtime-inspector').locator('details.runtime-context-block').filter({ hasText: 'Child source 1' })
  await childBlock.locator('summary').click()
  await expect(childBlock.getByText('CHILD_SOURCE_1', { exact: true })).toBeVisible()
  await expect(childBlock).toContainText('explicit-child-context-fixture')
  await expect(page.getByTestId('runtime-inspector')).not.toContainText('ROOT_SOURCE_1')
  await page.screenshot({ path: info.outputPath(`context-child-${theme}.png`), fullPage: true })
  await agent.selectOption(fixture.agents.missing)
  await expect(canvas.locator(`[data-context-snapshot-id="${fixture.rootSnapshotId}"]`)).toHaveCount(0)
  await expect(canvas.locator(`[data-context-snapshot-id="${fixture.childSnapshotId}"]`)).toHaveCount(0)
  await expect(canvas).not.toContainText('ROOT_EFFECTIVE_PROMPT')
  await expect(canvas).not.toContainText('CHILD_EFFECTIVE_PROMPT')
  const after = await (await request.get(`${server}/stats`)).json()
  expect(after.runtimeStarts).toBe(before.runtimeStarts)
  expect(after.terminalExecutions).toBe(before.terminalExecutions)
  expect(after.providerRequests).toBe(0)
  expect(after.sourceConnections).toBe(1)
  expect(errors).toEqual([])
  await info.attach('context-provenance.json', { body: JSON.stringify({ theme, fixture, sourceIds, before, after, errors }, null, 2), contentType: 'application/json' })
})
