import { test, expect } from '@playwright/test'
const server = 'http://127.0.0.1:4177'
test.beforeEach(async ({ request }) => { expect((await request.post(`${server}/reset`, { data: {} })).ok()).toBe(true) })

test('historical scroll and an actual map-to-chat message anchor retain the dock', async ({ page }, info) => {
  await page.goto('/?history=1', { waitUntil: 'domcontentloaded' })
  const chat = page.getByTestId('runtime-chat-slot')
  const viewport = chat.locator('[data-radix-scroll-area-viewport]').first()
  const olderMessage = chat.getByText('Исторический запрос 5', { exact: true })
  await olderMessage.scrollIntoViewIfNeeded()
  await expect(olderMessage).toBeInViewport()
  const before = await viewport.evaluate(element => element.scrollTop)
  expect(before).toBeGreaterThan(0)
  await page.getByTestId('toggle-map').click()
  await expect(page.getByTestId('runtime-map-dock')).toBeVisible()
  await expect(olderMessage).toBeInViewport()
  await page.getByTestId('toggle-map').click()
  await expect(olderMessage).toBeInViewport()
  await page.getByTestId('start-run').click()
  await expect(page.getByTestId('received-count')).toHaveText('2')
  await page.getByTestId('toggle-map').click()
  await page.getByRole('tab', { name: 'Список событий', exact: true }).click()
  await page.getByRole('listitem').filter({ has: page.getByText('Запрос', { exact: true }) }).first().click()
  await expect(chat.getByText('Сравни два источника и проверь результат.', { exact: true })).toBeInViewport()
  await expect(page.getByTestId('runtime-map-dock')).toBeVisible()
  expect(await page.evaluate(() => (window as unknown as { runtimeDiagnostics: { selectedMessage: string; chatMounts: number } }).runtimeDiagnostics)).toMatchObject({ selectedMessage: 'fixture-user', chatMounts: 1 })
  await page.screenshot({ path: info.outputPath('historical-anchor-dock-preserved.png'), fullPage: true })
})

test('pending credential input and existing draft survive map toggles without a response', async ({ page }, info) => {
  await page.goto('/?credential=1', { waitUntil: 'domcontentloaded' })
  const credential = page.locator('#credential-value:visible').first()
  await expect(credential).toBeVisible()
  await credential.fill('isolated-test-only')
  await page.getByTestId('attach-fixture').click()
  for (let cycle = 0; cycle < 3; cycle++) { await page.getByTestId('toggle-map').click(); await page.getByTestId('toggle-map').click() }
  await expect(credential).toHaveValue('isolated-test-only')
  await expect(page.getByTestId('draft-value')).toHaveText('Существующий черновик')
  await expect(page.getByTestId('attachments-count')).toHaveText('1')
  expect(await page.evaluate(() => (window as unknown as { runtimeDiagnostics: { credentialResponses: number; chatMounts: number; chatSends: number } }).runtimeDiagnostics)).toMatchObject({ credentialResponses: 0, chatMounts: 1, chatSends: 0 })
  await page.screenshot({ path: info.outputPath('pending-credential-preserved.png'), fullPage: true })
})

test('the retained production editor restores pins, branch ports and saved versions', async ({ page }, info) => {
  await page.goto('/?editor=1', { waitUntil: 'domcontentloaded' })
  await page.getByTestId('toggle-map').click()
  await page.getByRole('tab', { name: 'Редактор процесса', exact: true }).click()
  await expect(page.getByTestId('map-toolbar')).toBeVisible()
  await expect(page.getByTestId('map-add-node')).toBeVisible()
  const editor = page.locator('.runtime-editor-slot')
  await expect(editor.locator('.react-flow__node[data-id="decision"]')).toBeVisible()
  await expect(editor.locator('.react-flow__node[data-id="note-true"]')).toBeVisible()
  await expect(editor.locator('.react-flow__node[data-id="note-false"]')).toBeVisible()
  await expect(editor.locator('.react-flow__node[data-id="br_old-branch"]')).toBeVisible()
  const readStorage = () => page.evaluate(() => {
    const keys = (window as unknown as { runtimeEditorStorageKeys: Record<string, string> }).runtimeEditorStorageKeys
    return Object.fromEntries(Object.entries(keys).map(([name, key]) => [name, JSON.parse(localStorage.getItem(key)!)]))
  })
  const before = await readStorage()
  expect(before.pin.nodes['scn_editor-user']).toMatchObject({ x: 20, y: 20, width: 340, height: 210 })
  expect(before.draft.edges.map((edge: { sourceHandle?: string }) => edge.sourceHandle).sort()).toEqual(['decision:false', 'decision:true'])
  expect(before.workflow.versions).toHaveLength(1)
  await page.screenshot({ path: info.outputPath('retained-workflow-editor.png'), fullPage: true })
  await page.getByRole('tab', { name: 'Выполнение', exact: true }).click()
  await page.getByRole('tab', { name: 'Редактор процесса', exact: true }).click()
  await expect(page.getByTestId('map-toolbar')).toBeVisible()
  await page.reload({ waitUntil: 'domcontentloaded' })
  await page.getByTestId('toggle-map').click()
  await page.getByRole('tab', { name: 'Редактор процесса', exact: true }).click()
  const after = await readStorage()
  expect(after.draft.nodes.map((node: { id: string }) => node.id).sort()).toEqual(before.draft.nodes.map((node: { id: string }) => node.id).sort())
  expect(after.draft.edges.map((edge: { sourceHandle?: string }) => edge.sourceHandle).sort()).toEqual(['decision:false', 'decision:true'])
  expect(after.workflow.versions).toHaveLength(1)
  expect(after.pin.nodes['scn_editor-user']).toEqual(before.pin.nodes['scn_editor-user'])
})

test('ROX welcome and the lower composer work at 1920 in dark reduced-motion mode', async ({ page }, info) => {
  await page.setViewportSize({ width: 1920, height: 1080 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/?theme=dark', { waitUntil: 'domcontentloaded' })
  await expect(page.getByTestId('empty-chat-welcome')).toBeVisible()
  await expect(page.getByTestId('starter-prompt-list')).toBeVisible()
  await expect(page.locator('[contenteditable="true"]').first()).toBeVisible()
  await page.screenshot({ path: info.outputPath('welcome-dark-1920-reduced-motion.png'), fullPage: true })
})

test('a historical event requested before snapshot load resolves read-only in its original run', async ({ page, request }, info) => {
  const first = await (await request.post(`${server}/start`, { data: {} })).json()
  for (let step = 2; step < 16; step++) expect((await request.post(`${server}/step`, { data: {} })).ok()).toBe(true)
  const query = { workspaceId: 'fixture-workspace', sessionId: 'fixture-session', rootRunId: first.rootRunId }
  const old = await (await request.post(`${server}/snapshot`, { data: query })).json()
  const contextEvent = old.events.find((event: { kind: string }) => event.kind === 'context.captured')
  expect(contextEvent).toBeTruthy()
  const next = await (await request.post(`${server}/next-run`, { data: {} })).json()
  expect(next.rootRunId).not.toBe(first.rootRunId)
  const before = await (await request.get(`${server}/stats`)).json()
  await page.goto(`/?traceRoot=${encodeURIComponent(first.rootRunId)}&event=${encodeURIComponent(contextEvent.eventId)}`, { waitUntil: 'domcontentloaded' })
  await page.getByTestId('toggle-map').click()
  await expect(page.getByRole('combobox', { name: 'Выбрать запуск' })).toHaveValue(first.rootRunId)
  await expect(page.getByTestId('runtime-inspector')).toBeVisible()
  await expect(page.getByTestId('runtime-inspector')).toContainText('Сравни два источника')
  const after = await (await request.get(`${server}/stats`)).json()
  expect(after.runtimeStarts).toBe(before.runtimeStarts)
  expect(after.terminalExecutions).toBe(before.terminalExecutions)
  expect(after.providerRequests).toBe(0)
  await page.screenshot({ path: info.outputPath('historical-event-cold-snapshot.png'), fullPage: true })
})
