import { test, expect } from '@playwright/test'

const server = 'http://127.0.0.1:4177'
test.beforeEach(async ({ request }) => { expect((await request.post(`${server}/reset`, { data: {} })).ok()).toBe(true) })
test('real ChatDisplay stays mounted while the journal streams into the right dock', async ({ page, request }, info) => {
  const pageErrors: string[] = []
  page.on('pageerror', error => { pageErrors.push(error.message); console.log('Renderer error:', error.message) })
  page.on('requestfailed', request => console.log('Renderer request failed:', request.url(), request.failure()?.errorText))
  await page.goto('/', { waitUntil: 'domcontentloaded' })
  await expect(page.getByTestId('chat-runtime-split')).toBeVisible()
  const editor = page.locator('[contenteditable="true"]').first()
  await expect(editor).toBeVisible()
  await editor.fill('Сохрани этот черновик')
  await page.getByTestId('attach-fixture').click()
  await expect(page.getByTestId('draft-value')).toHaveText('Сохрани этот черновик')
  await expect(page.getByTestId('attachments-count')).toHaveText('1')
  await page.getByTestId('start-run').click()
  await expect(page.getByTestId('received-count')).toHaveText('2')
  await page.getByTestId('step-run').click()
  await expect(page.getByTestId('received-count')).toHaveText('3')
  await page.getByTestId('toggle-map').click()
  await expect(page.getByTestId('runtime-map-dock')).toBeVisible()
  await expect(page.getByTestId('runtime-node').first()).toBeVisible()
  const chatBox = await page.getByTestId('runtime-chat-slot').boundingBox()
  const mapBox = await page.getByTestId('runtime-map-slot').boundingBox()
  expect(chatBox && mapBox && mapBox.x >= chatBox.x + chatBox.width - 2).toBeTruthy()
  expect(chatBox && mapBox && chatBox.width / (chatBox.width + mapBox.width)).toBeCloseTo(.42, 1)
  await page.screenshot({ path: info.outputPath('split-stream-light.png'), fullPage: true })
  for (let cycle = 0; cycle < 3; cycle++) { await page.getByTestId('toggle-map').click(); await page.getByTestId('toggle-map').click() }
  await expect(editor).toHaveText('Сохрани этот черновик')
  await expect(page.getByText('fixture.txt', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => (window as unknown as { runtimeDiagnostics: { chatMounts: number } }).runtimeDiagnostics.chatMounts)).toBe(1)
  expect(await page.evaluate(() => (window as unknown as { runtimeDiagnostics: { chatSends: number } }).runtimeDiagnostics.chatSends)).toBe(0)
  const before = await (await request.get(`${server}/stats`)).json()
  expect(before.runtimeStarts).toBe(1)
  expect(before.providerRequests).toBe(0)
  expect(before.terminalExecutions).toBe(0)
  for (let index = 3; index < 16; index++) { await page.getByTestId('step-run').click(); await expect(page.getByTestId('received-count')).toHaveText(String(index + 1)) }
  await expect(page.getByTestId('runtime-chat-slot').getByText('Оба источника проверены.', { exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath('split-result-light.png'), fullPage: true })
  await page.getByRole('tab', { name: 'Список событий', exact: true }).click()
  await expect(page.getByRole('list', { name: 'Список событий' })).toBeVisible()
  await page.getByRole('searchbox', { name: 'Поиск событий' }).fill('fixture')
  const after = await (await request.get(`${server}/stats`)).json()
  expect(after.runtimeStarts).toBe(1)
  expect(after.terminalExecutions).toBe(1)
  expect(after.providerRequests).toBe(0)
  expect(pageErrors).toEqual([])
})

test('pending permission and draft survive toggles in dark and narrow layouts', async ({ page, request }, info) => {
  page.on('pageerror', error => console.log('Renderer error:', error.message))
  await page.goto('/?theme=dark', { waitUntil: 'domcontentloaded' })
  const editor = page.locator('[contenteditable="true"]').first()
  await editor.fill('Черновик при подтверждении')
  await page.getByTestId('attach-fixture').click()
  await page.getByTestId('start-run').click()
  await expect(page.getByTestId('received-count')).toHaveText('2')
  expect((await request.post(`${server}/approval`, { data: {} })).ok()).toBe(true)
  await expect(page.getByTestId('received-count')).toHaveText('3')
  await page.getByTestId('toggle-map').click()
  await expect(page.getByTestId('runtime-map-dock')).toBeVisible()
  await page.screenshot({ path: info.outputPath('permission-dark.png'), fullPage: true })
  await page.getByTestId('toggle-map').click(); await page.getByTestId('toggle-map').click()
  expect(await page.evaluate(() => (window as unknown as { runtimeDiagnostics: { permissionResponses: number } }).runtimeDiagnostics.permissionResponses)).toBe(0)
  expect(await page.evaluate(() => (window as unknown as { runtimeDiagnostics: { chatMounts: number } }).runtimeDiagnostics.chatMounts)).toBe(1)
  await expect(page.getByTestId('draft-value')).toHaveText('Черновик при подтверждении')
  await expect(page.getByTestId('attachments-count')).toHaveText('1')
  await page.setViewportSize({ width: 1280, height: 800 })
  await expect(page.getByTestId('runtime-map-dock')).toBeVisible()
  const separator = page.getByRole('separator')
  await separator.focus()
  await separator.press('ArrowLeft')
  await page.screenshot({ path: info.outputPath('permission-dark-1280.png'), fullPage: true })
  await page.setViewportSize({ width: 650, height: 800 })
  await expect(page.getByTestId('runtime-chat-slot')).toBeVisible()
  await page.screenshot({ path: info.outputPath('narrow-chat-preserved.png'), fullPage: true })
})

test('empty production chat keeps ROX welcome and suggestions above the lower composer', async ({ page, request }, info) => {
  await page.goto('/', { waitUntil: 'domcontentloaded' })
  await expect(page.getByTestId('empty-chat-welcome')).toBeVisible()
  await expect(page.getByTestId('starter-prompt-list')).toBeVisible()
  const editor = page.locator('[contenteditable="true"]').first()
  const welcome = await page.getByTestId('empty-chat-welcome').boundingBox()
  const suggestions = await page.getByTestId('starter-prompt-list').boundingBox()
  const composer = await editor.boundingBox()
  expect(welcome && suggestions && composer && welcome.y < suggestions.y && suggestions.y < composer.y).toBeTruthy()
  await page.screenshot({ path: info.outputPath('empty-chat-welcome.png'), fullPage: true })
  await page.getByTestId('attach-fixture').click()
  await page.getByTestId('starter-prompt').first().click()
  await expect(editor).not.toBeEmpty()
  await expect(page.getByTestId('attachments-count')).toHaveText('1')
  const diagnostics = await page.evaluate(() => (window as unknown as { runtimeDiagnostics: { chatSends: number; permissionResponses: number } }).runtimeDiagnostics)
  expect(diagnostics.chatSends).toBe(0)
  expect(diagnostics.permissionResponses).toBe(0)
  const stats = await (await request.get(`${server}/stats`)).json()
  expect(stats.runtimeStarts).toBe(0)
  expect(stats.providerRequests).toBe(0)
  await page.getByTestId('start-run').click()
  await expect(page.getByTestId('received-count')).toHaveText('2')
  await expect(page.getByTestId('starter-prompt-list')).toHaveCount(0)
})

