#!/usr/bin/env bun
/**
 * eslint-workspace-ratchet.ts — ESLint coverage ratchet for the DX-03 workspaces.
 *
 * Until now only apps/electron, packages/shared and packages/ui had an ESLint config, and CI
 * linted just the UI token ratchet. This script turns on the shared base config
 * (`scripts/eslint/base-config.mjs`) in the remaining workspaces and gates it against a committed
 * per-file, per-rule baseline, so a workspace with a few hundred existing violations starts
 * green: counts may only go down.
 *
 *   bun scripts/eslint-workspace-ratchet.ts                 # --check the committed baselines
 *   bun scripts/eslint-workspace-ratchet.ts --check --base HEAD^1
 *                                                           # also: a PR's baseline may not grow
 *                                                           #   versus the base commit's copy
 *   bun scripts/eslint-workspace-ratchet.ts --update        # rewrite the baselines (refuses growth
 *                                                           #   unless --allow-increase <workspace>)
 *   bun scripts/eslint-workspace-ratchet.ts --update --workspace core
 *
 * Options:
 *   --check                       default; fail on any (file, rule) count above the baseline, or on
 *                                 a baselined file the run no longer counts (see below)
 *   --update                      write eslint-baselines/workspaces/<name>.json from the current run
 *   --base <ref>                  read the base commit's baselines (`git show <ref>:<path>`) and
 *                                 fail if a PR's baseline raises a count or drops a rule versus it.
 *                                 Also reads `git diff -M -l0 --name-status <ref>` for renames: a
 *                                 move carries its counts (no false growth), a move out of the
 *                                 counted set is a weakening.
 *   --workspace <name>            restrict to these workspaces (repeatable)
 *   --allow-increase <name>       with --update: record growth in exactly these workspaces
 *   --override (or RATCHET_OVERRIDE=1)   report base-baseline growth and dropped counted files
 *                                 without failing
 *   --root <dir>                  repository root (default: this script's parent)
 *
 * The same counting rule as scripts/lint-baseline.ts: tests, fixtures, .d.ts and build output are
 * ignored (both by the shared config and by this script's ignore list), inline config is ignored
 * (`noInlineConfig`) so a disable comment cannot hide a violation, and every message the config
 * reports counts once — except a next-line/same-line directive naming the rule with a non-empty
 * `-- justification`. A baselined file the run no longer counts (the workspace config ignores it,
 * or a rename moved it out of the counted set) has its counts drop as a "decrease"; --check reports
 * it and requires the `eslint-workspace-override` label, --update records it with --allow-increase.
 */

import { existsSync, readFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { spawnSync } from 'node:child_process'
import { ESLint } from 'eslint'
import {
  applyRenames,
  compareCounts,
  compareWithBase,
  expectedFiles,
  formatWeakening,
  gitRenames,
  justifiedDirectives,
  sortCounts,
  staleRenamedPaths,
  totals,
  writeJson,
} from './lint-baseline.ts'
import type { Counts, Rename, Severity } from './lint-baseline.ts'
import { IGNORES, SOURCE_GLOB } from './eslint/base-config.mjs'

const SCRIPT_ROOT = resolve(import.meta.dir ?? dirname(new URL(import.meta.url).pathname), '..')
const BASELINE_DIR = 'eslint-baselines/workspaces'

export interface Workspace {
  name: string
  dir: string
}

/** The DX-03 gated workspaces. Keep in sync with the eslint.config.mjs files they carry. */
export const WORKSPACES: Workspace[] = [
  { name: 'server-core', dir: 'packages/server-core' },
  { name: 'core', dir: 'packages/core' },
  { name: 'webui', dir: 'apps/webui' },
  { name: 'viewer', dir: 'apps/viewer' },
  { name: 'cli', dir: 'apps/cli' },
  { name: 'messaging-gateway', dir: 'packages/messaging-gateway' },
  { name: 'messaging-discord-worker', dir: 'packages/messaging-discord-worker' },
  { name: 'messaging-whatsapp-worker', dir: 'packages/messaging-whatsapp-worker' },
  { name: 'browser-intel', dir: 'packages/browser-intel' },
  { name: 'test-harness', dir: 'packages/test-harness' },
]

const DESCRIPTION =
  'ESLint workspace ratchet (DX-03). Generated by `bun scripts/eslint-workspace-ratchet.ts --update`; ' +
  'per-file, per-rule counts may only go down. See scripts/eslint/base-config.mjs.'

export function baselinePath(root: string, name: string): string {
  return resolve(root, BASELINE_DIR, `${name}.json`)
}

/** What one workspace lint run yields: gated counts, justified exemptions and file coverage. */
export interface WorkspaceRun {
  /** Gated counts, per root-relative file and rule. */
  counts: Counts
  /** Violations exempted by a justified next-line/line directive (informational). */
  exempt: Counts
  /** Every file ESLint linted (root-relative), with or without violations. */
  linted: Set<string>
  /** Every file the ratchet must count (root-relative): the glob minus the shared ignores. */
  expected: string[]
}

/** Lint one workspace with its own flat config; gated counts per root-relative file and rule. */
export async function collectWorkspaceRun(root: string, workspace: Workspace): Promise<WorkspaceRun> {
  const cwd = resolve(root, workspace.dir)
  const configFile = resolve(cwd, 'eslint.config.mjs')
  if (!existsSync(configFile)) throw new Error(`${workspace.dir}/eslint.config.mjs is missing`)
  const eslint = new ESLint({ cwd, overrideConfigFile: configFile, errorOnUnmatchedPattern: false })
  const results = await eslint.lintFiles([SOURCE_GLOB])
  const counts: Counts = {}
  const exempt: Counts = {}
  const linted = new Set<string>()
  const directiveCache = new Map<string, Set<string>>()
  for (const result of results) {
    const file = relative(root, result.filePath).split('\\').join('/')
    if (IGNORES.some((pattern) => new Bun.Glob(pattern).match(file))) continue
    linted.add(file)
    for (const message of result.messages) {
      if (message.fatal) throw new Error(`ESLint could not parse ${file}: ${message.message}`)
      const rule = message.ruleId
      if (!rule) continue
      // The config runs with noInlineConfig, so a disable comment never hides a violation. The one
      // exemption (parity with scripts/lint-baseline.ts): a next-line/same-line directive that
      // names the rule and carries a non-empty `-- justification`.
      let directives = directiveCache.get(result.filePath)
      if (!directives) {
        directives = justifiedDirectives(readFileSync(result.filePath, 'utf8'), 'eslint')
        directiveCache.set(result.filePath, directives)
      }
      const perFile = (directives.has(`${message.line}:${rule}`) ? exempt : counts)[file] ??= {}
      perFile[rule] = (perFile[rule] ?? 0) + 1
    }
  }
  if (linted.size === 0) throw new Error(`${workspace.dir}: no files matched ${SOURCE_GLOB}`)
  return {
    counts: sortCounts(counts),
    exempt: sortCounts(exempt),
    linted,
    expected: expectedFiles(root, [workspace.dir], SOURCE_GLOB, IGNORES, false),
  }
}

/** Gated counts only (see collectWorkspaceRun). */
export async function collectWorkspace(root: string, workspace: Workspace): Promise<Counts> {
  return (await collectWorkspaceRun(root, workspace)).counts
}

/** Rule severities a workspace's flat config would apply (for the baseline's `rules` section). */
export async function workspaceSeverities(root: string, workspace: Workspace): Promise<Record<string, Severity>> {
  const url = pathToFileURL(resolve(root, workspace.dir, 'eslint.config.mjs')).href
  // Dynamic import: the specifier is the per-workspace config path chosen at runtime.
  const loaded = (await import(url)) as { default: unknown }
  const severities: Record<string, Severity> = {}
  for (const entry of [loaded.default].flat() as Array<{ rules?: Record<string, unknown> }>) {
    for (const [rule, setting] of Object.entries(entry.rules ?? {})) {
      const level = Array.isArray(setting) ? setting[0] : setting
      if (level === 'off' || level === 0) {
        delete severities[rule]
      } else {
        severities[rule] = level === 'error' || level === 2 ? 'error' : 'warn'
      }
    }
  }
  return severities
}

export interface WorkspaceBaseline {
  description: string
  rules: Record<string, { severity: Severity; total: number }>
  files: Counts
}

export function buildWorkspaceBaseline(counts: Counts, severities: Record<string, Severity>): WorkspaceBaseline {
  const sums = totals(counts)
  return {
    description: DESCRIPTION,
    rules: Object.fromEntries(
      Object.keys(severities)
        .sort()
        .map((rule) => [rule, { severity: severities[rule]!, total: sums[rule] ?? 0 }]),
    ),
    files: sortCounts(counts),
  }
}

export function readWorkspaceBaseline(file: string): WorkspaceBaseline | null {
  if (!existsSync(file)) return null
  return JSON.parse(readFileSync(file, 'utf8')) as WorkspaceBaseline
}

/** The base commit's baseline (`git show <ref>:<path>`), or null when the base has none. */
export function readBaseBaseline(root: string, ref: string, name: string): WorkspaceBaseline | null {
  const path = `${BASELINE_DIR}/${name}.json`
  const result = spawnSync('git', ['show', `${ref}:${path}`], { cwd: root, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 })
  if (result.status !== 0) {
    const verify = spawnSync('git', ['rev-parse', '--verify', '--quiet', `${ref}^{commit}`], { cwd: root, encoding: 'utf8' })
    if (verify.status !== 0) throw new Error(`base ref ${ref} is not available (fetch it first)`)
    return null
  }
  return JSON.parse(result.stdout) as WorkspaceBaseline
}

export interface StaleCounted {
  file: string
  violations: number
  reason: 'skipped' | 'moved-out'
}

/**
 * Counted files the current run no longer counts, though the baseline still gates them:
 *  - 'skipped': the file matches the source glob but the workspace config no longer lints it (an
 *    `ignores` entry, a narrowed `files` glob, a changed extension) - it left the gate silently.
 *  - 'moved-out': `git diff -M` (vs the base commit) renamed it to a path the run does not lint
 *    (`__tests__/`, `*.test.*`, `*.d.ts`, outside the workspace ...).
 * A plain delete (gone from disk, not a rename source) is not stale: its counts drop as a decrease.
 */
export function staleCountedFiles(
  baselineFiles: Counts,
  linted: Set<string>,
  skipped: string[],
  renames: Rename[] = [],
): StaleCounted[] {
  const skippedSet = new Set(skipped)
  const renamedTo = new Map(renames.map(({ from, to }) => [from, to]))
  const stale: StaleCounted[] = []
  for (const [file, rules] of Object.entries(baselineFiles)) {
    if (linted.has(file)) continue
    const violations = Object.values(rules).reduce((sum, count) => sum + count, 0)
    if (violations === 0) continue
    if (skippedSet.has(file)) stale.push({ file, violations, reason: 'skipped' })
    else {
      const to = renamedTo.get(file)
      if (to !== undefined && !linted.has(to)) stale.push({ file, violations, reason: 'moved-out' })
    }
  }
  return stale.sort((a, b) => a.file.localeCompare(b.file))
}

export function formatStale(stale: StaleCounted[]): string[] {
  return stale.map(({ file, violations, reason }) =>
    reason === 'skipped'
      ? `  ${file}: ${violations} counted violation(s) are no longer linted (config ignore?)`
      : `  ${file}: ${violations} counted violation(s) moved out of the counted set`,
  )
}

function argValue(args: string[], name: string): string | undefined {
  const index = args.lastIndexOf(name)
  return index >= 0 ? args[index + 1] : undefined
}

function argAll(args: string[], name: string): string[] {
  return args.flatMap((arg, index) => (arg === name && index + 1 < args.length ? [args[index + 1]!] : []))
}

function formatChanges(changes: Array<{ file: string; rule: string; baseline: number; current: number }>): string[] {
  return changes.map(({ file, rule, baseline, current }) => `  ${file}: ${rule} ${baseline} -> ${current} (+${current - baseline})`)
}

export async function main(argv: string[], env: Record<string, string | undefined> = process.env): Promise<number> {
  const root = resolve(argValue(argv, '--root') ?? SCRIPT_ROOT)
  const update = argv.includes('--update')
  const baseRef = argValue(argv, '--base')
  const override = argv.includes('--override') || env.RATCHET_OVERRIDE === '1'
  const allowed = new Set(argAll(argv, '--allow-increase'))
  const only = new Set(argAll(argv, '--workspace'))
  for (const name of allowed) if (!WORKSPACES.some((workspace) => workspace.name === name)) throw new Error(`--allow-increase: unknown workspace ${name}`)
  for (const name of only) if (!WORKSPACES.some((workspace) => workspace.name === name)) throw new Error(`--workspace: unknown workspace ${name}`)

  const selected = WORKSPACES.filter((workspace) => only.size === 0 || only.has(workspace.name))
  // Renames vs the base commit: a move carries its counts (no false growth), and a move out of the
  // counted set is a weakening, not a decrease.
  const renames = baseRef ? gitRenames(root, baseRef) : []
  let failed = false
  let total = 0
  let exemptTotal = 0

  for (const workspace of selected) {
    const file = baselinePath(root, workspace.name)
    const run = await collectWorkspaceRun(root, workspace)
    // Files the glob expects but the workspace config silently dropped (ignores / narrowed glob).
    const skipped = run.expected.filter((expected) => !run.linted.has(expected))
    const previous = readWorkspaceBaseline(file)
    const stale = previous ? staleCountedFiles(previous.files, run.linted, skipped, renames) : []

    if (update) {
      const next = buildWorkspaceBaseline(run.counts, await workspaceSeverities(root, workspace))
      if (previous && !allowed.has(workspace.name)) {
        // Renames carry their counts, so a move within the counted set is not growth.
        const refused = compareCounts(applyRenames(previous.files, renames), next.files).increases
        if (refused.length) {
          failed = true
          console.error(`eslint-workspace-ratchet: refusing to record growth in ${workspace.name} (name it with --allow-increase):`)
          console.error(formatChanges(refused).join('\n'))
          continue
        }
        // A counted file leaving the gate (config ignore / move out of the counted set) drops its
        // counts as a "decrease": record it only with the owner's --allow-increase.
        if (stale.length) {
          failed = true
          console.error(`eslint-workspace-ratchet: refusing to drop counted files from ${workspace.name} (name it with --allow-increase):`)
          console.error(formatStale(stale).join('\n'))
          continue
        }
      }
      writeJson(file, next)
      const count = Object.values(totals(next.files)).reduce((sum, value) => sum + value, 0)
      console.log(`eslint-workspace-ratchet: wrote ${relative(root, file)} (${Object.keys(next.files).length} files, ${count} violations)`)
      if (stale.length) {
        console.log(`eslint-workspace-ratchet: ${workspace.name}: dropped ${stale.length} counted file(s) (owner-approved):`)
        console.log(formatStale(stale).join('\n'))
      }
      continue
    }

    // --check
    if (!previous) {
      failed = true
      console.error(`eslint-workspace-ratchet: ${relative(root, file)} is missing; run --update.`)
      continue
    }
    const baseline = previous
    const comparison = compareCounts(baseline.files, run.counts)
    if (comparison.increases.length) {
      failed = true
      console.error(`eslint-workspace-ratchet: ${workspace.name} grew versus its baseline:`)
      console.error(formatChanges(comparison.increases).join('\n'))
    }
    if (comparison.decreases.length) {
      const saved = comparison.decreases.reduce((sum, entry) => sum + entry.baseline - entry.current, 0)
      console.log(`eslint-workspace-ratchet: ${workspace.name} has ${saved} fewer violations than the baseline; lock them in with --update.`)
    }
    total += Object.values(totals(run.counts)).reduce((sum, value) => sum + value, 0)
    exemptTotal += Object.values(totals(run.exempt)).reduce((sum, value) => sum + value, 0)

    // A counted file that left the gate silently (its counts drop as a "decrease", so nothing else
    // fails) needs an owner: report it and require the eslint-workspace-override label.
    if (stale.length) {
      const lines = formatStale(stale)
      if (override) {
        console.log(`eslint-workspace-ratchet: override: ${workspace.name} no longer counts baselined files:`)
        console.log(lines.join('\n'))
      } else {
        failed = true
        console.error(`eslint-workspace-ratchet: ${workspace.name} no longer counts baselined files (needs the eslint-workspace-override label):`)
        console.error(lines.join('\n'))
      }
    }

    if (baseRef) {
      // A PR that moved a counted file must rebaseline: the committed copy still keyed by the old
      // path passes this PR (counts follow the rename) but fails the push-to-main run after the
      // merge, when no --base is given and the new path has no baseline entry.
      const stalePaths = staleRenamedPaths(baseline.files, renames)
      if (stalePaths.length) {
        failed = true
        console.error(`eslint-workspace-ratchet: ${BASELINE_DIR}/${workspace.name}.json still lists renamed files under their old path (renames vs ${baseRef}):`)
        console.error(stalePaths.map(({ from, to }) => `  ${from} -> ${to}`).join('\n'))
        console.error(`  Run \`bun scripts/eslint-workspace-ratchet.ts --update --base ${baseRef} --workspace ${workspace.name}\` and commit the baseline.`)
      }
      const base = readBaseBaseline(root, baseRef, workspace.name)
      if (!base) {
        console.log(`eslint-workspace-ratchet: ${baseRef} has no ${BASELINE_DIR}/${workspace.name}.json yet; skipping the base comparison.`)
      } else {
        const { increases, weakened } = compareWithBase(base, baseline, renames, run.linted)
        if (increases.length || weakened.length) {
          const lines = [...formatChanges(increases), ...weakened.map(formatWeakening)]
          if (override) {
            console.log(`eslint-workspace-ratchet: override: ${workspace.name} baseline grows versus ${baseRef}:`)
            console.log(lines.join('\n'))
          } else {
            failed = true
            console.error(`eslint-workspace-ratchet: ${workspace.name} baseline grows versus ${baseRef} (needs owner review):`)
            console.error(lines.join('\n'))
          }
        }
      }
    }
  }

  if (!update && exemptTotal) console.log(`eslint-workspace-ratchet: ${exemptTotal} violations exempted by justified next-line directives.`)
  if (!update && !failed) {
    console.log(`eslint-workspace-ratchet: OK — ${total} baselined violations across ${selected.length} workspace(s), none new.`)
  }
  return failed ? 1 : 0
}

if (import.meta.main) {
  main(process.argv.slice(2)).then(
    (code) => process.exit(code),
    (error) => {
      console.error(error instanceof Error ? error.stack ?? error.message : error)
      process.exit(2)
    },
  )
}