#!/usr/bin/env bun
/**
 * IPC inventory generator.
 *
 * Emits the frozen `RPC_CHANNELS` snapshot consumed by
 * `apps/electron/src/shared/__tests__/ipc-channels.test.ts`, so the wire-format
 * contract can no longer drift by hand.
 *
 * Usage:
 *   bun run scripts/ipc-inventory.ts           # (re)write the generated artifact
 *   bun run scripts/ipc-inventory.ts --check    # exit 1 when the artifact is stale
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { getAllChannelValues } from '@rox/shared/protocol'

const OUT_FILE = join(
  dirname(fileURLToPath(import.meta.url)),
  '../apps/electron/src/shared/__tests__/ipc-channels.generated.ts',
)

/** Sorted wire-format channel strings — the exact list the test asserts. */
export function collectIpcInventory(): string[] {
  return [...getAllChannelValues()].sort()
}

/** Deterministic source text for the generated artifact. */
export function renderIpcInventory(channels: readonly string[]): string {
  return [
    '// Auto-generated by scripts/ipc-inventory.ts — DO NOT edit by hand.',
    '// Regenerate: bun run scripts/ipc-inventory.ts',
    '',
    'export const EXPECTED_CHANNELS: string[] = [',
    ...channels.map((channel) => `  '${channel}',`),
    ']',
    '',
    `export const EXPECTED_CHANNEL_COUNT = ${channels.length}`,
    '',
  ].join('\n')
}

if (import.meta.main) {
  const channels = collectIpcInventory()
  const rendered = renderIpcInventory(channels)
  if (process.argv.includes('--check')) {
    const current = readFileSync(OUT_FILE, 'utf8')
    if (current !== rendered) {
      console.error(`ipc-inventory: ${OUT_FILE} is stale — run: bun run scripts/ipc-inventory.ts`)
      process.exit(1)
    }
    console.log(`ipc-inventory: ${channels.length} channels (up to date)`)
  } else {
    writeFileSync(OUT_FILE, rendered)
    console.log(`ipc-inventory: wrote ${channels.length} channels to ${OUT_FILE}`)
  }
}