import {afterAll,beforeAll,describe,expect,it} from 'bun:test'
import {existsSync} from 'node:fs'
import {resolve} from 'node:path'
import {chromium,expect as playwrightExpect,type Browser,type Page} from 'playwright/test'
const repository=resolve(import.meta.dirname,'../../../../../..'),fixture=resolve(import.meta.dirname,'fixtures/availability'),endpoint='http://127.0.0.1:5269'
const executablePath=process.env.CHROMIUM_EXECUTABLE??chromium.executablePath(),timeout=60000,check=playwrightExpect.configure({timeout:15000})
const action=(page:Page,code:string)=>page.evaluate(code),calls=(page:Page,kind:string)=>page.evaluate(kind=>(window as any).__knowledgeFixture.calls.filter((entry:any)=>entry.kind===kind),kind)
describe.skipIf(!existsSync(executablePath))('actual Knowledge availability consumers',()=>{
 let server:ReturnType<typeof Bun.spawn>|undefined,browser:Browser,ownedChrome:{pid:number;profile:string}|undefined
 const processText=async(args:string[])=>{const child=Bun.spawn(['ps',...args],{stdout:'pipe',stderr:'ignore'});const value=await new Response(child.stdout).text();await child.exited;return value}
 const stillOwned=async()=>{if(!ownedChrome)return false;const command=(await processText(['-p',String(ownedChrome.pid),'-o','command='])).trim();return command.startsWith(executablePath+' ')&&command.includes('--rox-knowledge-availability-fixture')&&command.includes(ownedChrome.profile)}
 const stop=async()=>{server?.kill('SIGKILL');if(browser){await Promise.race([browser.close().catch(()=>{}),Bun.sleep(5000)]);if(await stillOwned()){process.kill(ownedChrome!.pid,'SIGTERM');await Bun.sleep(500);if(await stillOwned())process.kill(ownedChrome!.pid,'SIGKILL')}}await server?.exited}
 beforeAll(async()=>{try{server=Bun.spawn(['node',resolve(repository,'node_modules/vite/bin/vite.js'),'--config',resolve(fixture,'vite.config.ts'),'--port','5269'],{cwd:repository,stdout:'ignore',stderr:'ignore'});const deadline=Date.now()+30000;for(;;){if(server.exitCode!==null)throw Error('Knowledge fixture exited');try{const response=await fetch(endpoint);if(response.ok){if(!(await response.text()).includes('rox-knowledge-availability-fixture'))throw Error('Foreign fixture port owner');break}}catch(error){if(error instanceof Error&&error.message.includes('Foreign fixture'))throw error}if(Date.now()>deadline)throw Error('Knowledge fixture startup timeout');await Bun.sleep(100)}browser=await chromium.launch({executablePath,headless:true,args:['--no-sandbox','--rox-knowledge-availability-fixture']});const rows=(await processText(['-axo','pid=,command='])).split('\n').map(line=>line.trim().match(/^(\d+)\s+(.*)$/)).filter((row):row is RegExpMatchArray=>!!row&&row[2].startsWith(executablePath+' ')&&row[2].includes('--rox-knowledge-availability-fixture'));if(rows.length!==1)throw Error('Owned Chrome identity unavailable');const profile=rows[0][2].match(/--user-data-dir=\S+/)?.[0];if(!profile)throw Error('Owned Chrome profile unavailable');ownedChrome={pid:Number(rows[0][1]),profile}}catch(error){await stop();throw error}},45000)
 afterAll(stop,timeout)
 const withPage=async(run:(page:Page)=>Promise<void>)=>{const context=await browser.newContext({viewport:{width:1100,height:900}}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));try{await page.goto(endpoint,{waitUntil:'domcontentloaded',timeout});await check(page.getByTestId('tree').getByRole('button',{name:'Saved A',exact:true})).toBeVisible();await check(page.getByTestId('home').getByTestId('knowledge-open-rox-notes')).toBeVisible();await run(page);expect(errors).toEqual([])}catch(error){throw Error('Production Knowledge fixture failed; errors='+JSON.stringify(errors)+'; body='+await page.locator('body').innerText(),{cause:error})}finally{await context.close()}}
 it('offline retains local Recent/Favorites/views, shares one probe, and remount stays fast with zero kernel reads',()=>withPage(async page=>{
   expect(await calls(page,'notebooks')).toHaveLength(0);expect(await calls(page,'title')).toHaveLength(0);await check(page.getByTestId('tree').getByRole('button',{name:'A',exact:true})).toHaveCount(2);expect(await calls(page,'status')).toEqual([{kind:'status',workspaceId:'A',args:{workspaceId:'A',connectionId:'one'}}]);await page.getByTestId('home').getByTestId('knowledge-open-rox-notes').click();expect(await action(page,'window.__knowledgeFixture.routes')).toEqual(['notes']);await action(page,'window.__knowledgeFixture.mount(false);window.__knowledgeFixture.mount(true)');await check(page.getByTestId('tree').getByRole('button',{name:'Saved A',exact:true})).toBeVisible();expect(await calls(page,'status')).toHaveLength(1);expect(await calls(page,'notebooks')).toHaveLength(0)
 }),timeout)
 it('a native change invalidates once and recovers real notebook/title rendering for both consumers',()=>withPage(async page=>{
   await action(page,'window.__knowledgeFixture.running=true;window.__knowledgeFixture.emit()');await check(page.getByTestId('tree').getByRole('button',{name:/Notebook A/})).toBeVisible();await check(page.getByTestId('tree').getByRole('button',{name:'Title A',exact:true})).toHaveCount(2);expect(await calls(page,'status')).toHaveLength(2);expect(await calls(page,'notebooks')).toHaveLength(1);expect(await calls(page,'title')).toHaveLength(1);expect((await calls(page,'title'))[0].args.workspaceId).toBe('A');await check(page.getByTestId('home').getByTestId('knowledge-open-rox-notes')).toHaveCount(0)
 }),timeout)
 it('switching workspace hides old local rows immediately and late old snapshots cannot return',()=>withPage(async page=>{
   await action(page,'window.__knowledgeFixture.hold.add("views");window.__knowledgeFixture.hold.add("status");window.__knowledgeFixture.emit()');await check.poll(()=>calls(page,'views').then(rows=>rows.length)).toBeGreaterThan(2);await action(page,'window.__knowledgeFixture.scope("B")');await check(page.getByRole('button',{name:'Saved A',exact:true})).toHaveCount(0);await check(page.getByRole('button',{name:'A',exact:true})).toHaveCount(0);await action(page,'window.__knowledgeFixture.resolve("views","B",[{id:"view-B",name:"Saved B",domain:"knowledge"}]);window.__knowledgeFixture.resolve("status","B",{running:false})');await check(page.getByTestId('tree').getByRole('button',{name:'Saved B',exact:true})).toBeVisible();await action(page,'window.__knowledgeFixture.resolve("views","A",[{id:"old",name:"Obsolete A",domain:"knowledge"}]);window.__knowledgeFixture.resolve("status","A",{running:true})');await page.waitForTimeout(200);await check(page.getByRole('button',{name:'Obsolete A',exact:true})).toHaveCount(0);expect(await calls(page,'notebooks')).toHaveLength(0);expect(await calls(page,'status')).toHaveLength(3)
 }),timeout)
 it('same-workspace refresh fences old event completions and resets a failed probe without obsolete reads',()=>withPage(async page=>{
   await action(page,'window.__knowledgeFixture.hold.add("views");window.__knowledgeFixture.hold.add("status");window.__knowledgeFixture.emit()');await check.poll(()=>calls(page,'status').then(rows=>rows.length)).toBe(2);await action(page,'window.__knowledgeFixture.hold.clear();window.__knowledgeFixture.label=" fresh";window.__knowledgeFixture.emit()');await check(page.getByTestId('tree').getByRole('button',{name:'Saved A fresh',exact:true})).toBeVisible();await action(page,'window.__knowledgeFixture.resolve("views","A",[{id:"old",name:"Obsolete A",domain:"knowledge"}]);window.__knowledgeFixture.resolve("status","A",{running:true})');await page.waitForTimeout(200);await check(page.getByRole('button',{name:'Obsolete A',exact:true})).toHaveCount(0);expect(await calls(page,'notebooks')).toHaveLength(0);expect(await calls(page,'status')).toHaveLength(3);await check(page.getByTestId('home').getByTestId('knowledge-open-rox-notes')).toBeVisible()
 }),timeout)
 it('missing engine channel still renders local rows and the current Rox Notes route without raw errors',()=>withPage(async page=>{
   await action(page,'delete window.electronAPI.knowledge.engineStatus;window.__knowledgeFixture.emit()');await check(page.getByTestId('tree').getByRole('button',{name:'Saved A',exact:true})).toBeVisible();expect(await calls(page,'notebooks')).toHaveLength(0);expect(await calls(page,'title')).toHaveLength(0);await check(page.getByTestId('home').getByTestId('knowledge-open-rox-notes')).toBeVisible()
 }),timeout)
})
