---
- name: Reload systemd
  listen: reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart observability control
  listen: restart observability control
  ansible.builtin.systemd_service:
    name: observability-control.service
    state: restarted
  when: not ansible_check_mode

