import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const page = readFileSync(join(import.meta.dir, '../MeetingsPage.tsx'), 'utf8')
const detail = readFileSync(join(import.meta.dir, '../MeetingDetail.tsx'), 'utf8')
const readiness = readFileSync(join(import.meta.dir, '../use-local-meeting-readiness.ts'), 'utf8')

describe('meetings page (issue 368)', () => {
  test('distinguishes empty/denied/offline and keeps manual notes', () => {
    expect(page).toContain('data-testid="meetings-page"')
    expect(page).toContain('data-testid="meetings-start"')
    expect(page).toContain('data-testid="meetings-capture-status"')
    expect(page).toContain('data-testid="meetings-search"')
    expect(page).toContain('data-testid="meeting-live-transcript"')
    expect(page).toContain('data-testid="meetings-denied"')
    expect(page).toContain('data-testid="meetings-empty"')
    expect(page).toContain('data-testid="meetings-offline"')
    expect(page).toContain("t('meetings.pageTitle')")
    expect(detail).toContain('data-testid="meeting-manual-notes"')
    expect(detail).toContain("t('meetings.manualNotes')")
    expect(detail).toContain('data-testid="meeting-knowledge-diff"')
    expect(detail).toContain("t('meetings.knowledgeDiff')")
    expect(detail).toContain('data-testid="meeting-materials"')
    expect(detail).toContain('data-testid="meeting-artifact"')
    expect(detail).toContain('data-testid="meeting-artifact-open"')
    expect(detail).toContain('data-testid="meeting-artifact-hash"')
    expect(detail).toContain("t('meetings.materials')")
    expect(detail).toContain('data-testid="meeting-actions"')
    expect(detail).toContain('data-testid="meeting-tracker"')
    expect(detail).toContain('data-testid="proposal-target-link"')
    expect(detail).toContain("t('meetings.actions')")
    expect(detail).toContain("t('meetings.trackerOpen')")
    expect(detail).toContain("t('meetings.trackerVerified')")
    expect(detail).toContain("t('meetings.trackerFixture')")
    expect(page).toContain('AgentReadiness')
    expect(page).toContain('useLocalMeetingReadiness')
    expect(page).not.toContain('@craft-agent/server-core')
    expect(detail).not.toContain('@craft-agent/server-core')
    expect(readiness).not.toContain('@craft-agent/server-core')
    expect(readiness).not.toContain('localStorage')
    expect(readiness).toContain('hasCrmCapability: false')
  })
})
