import { describe, expect, it } from 'bun:test'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const rendererRoot = join(__dirname, '..', '..', '..')
const read = (path: string) => readFileSync(join(rendererRoot, path), 'utf8')

describe('issues 07–09 wiring', () => {
  it('keeps Notes document rails, breadcrumbs and command palette on the real NotesPage', () => {
    const notesPage = read('pages/NotesPage.tsx')
    expect(notesPage).toContain('useNotesRailLayout')
    expect(notesPage).toContain('NotesBreadcrumbs')
    expect(notesPage).toContain('NotesCommandPalette')
    expect(notesPage).toContain('NotesRailSash')
    expect(notesPage).toContain('sanitizePastedMarkdown')
    expect(notesPage).toContain('setHorizontalRule')
    expect(notesPage).toContain('matchWikiLinkCandidates')
    expect(notesPage).toContain('completeWikiCreate')
    expect(notesPage).toContain("t('notes.editor.wikiCreate'")
    expect(notesPage).toContain("t('notes.editor.wikiHint')")
    expect(notesPage).toContain('data-testid="notes-wiki-menu"')
    expect(notesPage).not.toContain('Link to new note "')
    expect(notesPage).toContain('upsertMarkdownComment')
    expect(notesPage).toContain('buildVaultInsights')
    expect(notesPage).toContain('aliasesFromProperties')
    expect(notesPage).toContain('applyLinkSuggestion')
    expect(notesPage).toContain('insertFootnote')
    expect(notesPage).toContain('VaultInsightsPanel')
    expect(notesPage).toContain('getNoteIndexHealth')
    expect(notesPage).toContain('rebuildNoteIndex')
    const inspector = read('pages/notes/NoteInspector.tsx')
    const panel = read('pages/notes/VaultInsightsPanel.tsx')
    expect(inspector).toContain('VaultInsightsPanel')
    expect(inspector).toContain('VaultIndexHealthPanel')
    const health = read('pages/notes/VaultIndexHealthPanel.tsx')
    expect(health).toContain('data-testid="notes-index-health"')
    expect(health).toContain("t('notes.inspector.indexHealth')")
    expect(health).toContain("t('notes.inspector.indexWatching')")
    expect(health).toContain("t('notes.inspector.indexRebuild')")
    expect(panel).toContain("t('notes.inspector.linkSuggestions')")
    expect(panel).toContain("t('notes.inspector.footnotes')")
    expect(panel).toContain('mb-2 flex flex-col gap-1.5')
    expect(panel).toContain('w-full min-w-0')
  })

  it('hosts table, canvas, outline and graph views without replacing Map', () => {
    const notesPage = read('pages/NotesPage.tsx')
    const tabs = read('components/app-shell/EntityViewTabs.tsx')
    expect(tabs).toContain("id: 'table'")
    expect(tabs).toContain("id: 'canvas'")
    expect(notesPage).toContain('<NotesViewHost')
    const host = read('pages/notes/NotesViewHost.tsx')
    expect(host).toContain('data-testid="notes-table-toolbar"')
    expect(host).toContain('data-testid="notes-table-formula"')
    expect(host).toContain('PremiumMenuSelect')
    expect(host).not.toContain('<select')
    expect(host).toContain('addFormula')
    expect(host).toContain('formulaValue')
    expect(host).toContain('data-testid="notes-graph-kind"')
    expect(host).toContain('serializeOutlineFolds')
    expect(host).toContain('filterGraphByEdgeKind')
    expect(host).toContain('toggleNoteViewSort')
    expect(host).toContain('notes-graph-nearby')
    expect(host).toContain('progressiveGraph')
    expect(host).toContain('isolateCanvasForNote')
    expect(host).toContain('moveCanvasNode')
    expect(host).toContain('notes-canvas-fit')
    expect(host).toContain('notesCanvasStorageKey')
    expect(notesPage).toMatch(/<EntityViewTabs[\s\S]{0,5000}map[\s\S]{0,5000}<MindMapHost/)
  })

  it('exposes Fit/Reset/Run, inspector status and sticky/frame/group chrome on session canvas', () => {
    const editor = read('components/session-workbench/SessionWorkflowEditor.tsx')
    expect(editor).toContain("t('entityView.mapRun')")
    expect(editor).toContain("t('entityView.mapAlign')")
    expect(editor).toContain("data-testid=\"session-canvas-inspector\"")
    expect(editor).toContain("handleCreateChrome('sticky')")
    expect(editor).toContain("handleCreateChrome('frame')")
    expect(editor).toContain("handleCreateChrome('group')")
    expect(editor).toContain('!bg-background/45')
  })

  it('wires column keyboard, grouped @ palette and comment rail', () => {
    const ia = read('pages/notes/document-ia.ts')
    const page = read('pages/NotesPage.tsx')
    const chrome = read('pages/notes/NotesDocumentChrome.tsx')
    const reading = read('pages/notes/NotesReadingChrome.tsx')
    expect(ia).toContain('noteColumnKeyboardAction')
    expect(ia).toContain('parseNoteCommandQuery')
    expect(ia).toContain('peopleAndEntitiesFromInsights')
    expect(ia).toContain('notePaletteKeyAction')
    expect(ia).toContain('noteCommentKeyboardAction')
    expect(page).toContain('noteColumnKeyboardAction')
    expect(page).toContain('notePaletteKeyAction')
    expect(page).toContain('peopleAndEntitiesFromInsights')
    expect(page).toContain('onJumpToQuote')
    expect(chrome).toContain('notes-command-palette')
    expect(chrome).toContain('groupNoteCommands')
    expect(reading).toContain('notes-comments-compose')
    expect(reading).toContain('notes.comments.submitHint')
    expect(reading).toContain('notes.comments.jumpToQuote')
    expect(reading).toContain('NotesCommentComposer')
    expect(reading).toContain('notes-comment-highlights')
    expect(reading).toContain('notes-comment-tooltip')
    expect(page).toContain('NOTES_AI_MODEL')
    expect(page).toContain('notes-bound-chat')
    expect(page).toContain('composerTop')
  })

  it('exposes playground stories for inspector, wiki, palette, comments and formula table', () => {
    const notes = read('playground/registry/notes.tsx')
    expect(notes).toContain("id: 'notes-table'")
    expect(notes).toContain("id: 'notes-graph'")
    expect(notes).toContain("id: 'notes-inspector'")
    expect(notes).toContain("id: 'notes-wiki'")
    expect(notes).toContain("id: 'notes-palette'")
    expect(notes).toContain("id: 'notes-comments'")
    expect(notes).toContain('VaultInsightsPanel')
    expect(notes).toContain('matchWikiLinkCandidates')
    expect(notes).toContain('NotesCommandPalette')
    expect(notes).toContain('NotesComments')
    expect(notes).not.toContain('<select')
  })
})
